### PR TITLE
chore: convert some requires to import statements

### PR DESCRIPTION
**Pull request by aboyton**
This doesn't turn it on everywhere as doing so made some of the tests to fail.

### CODE REVIEW

**Comment by JamesHenry** [comment]
Thanks for looking to contribute, @aboyton! I'm afraid I don't understand the goal of this PR, and it is fundamentally broken. You are adding imports and exports to node .js files, that will not work. Also `"resolveJsonModule": true` will alter the structure of the build output, so has significant repercussions.

Thanks again supporting the project

**Comment by aboyton** [comment]
All good. I was looking for an easy thing to get started on the project again and noticed that #67 had a comment

>i had to disable some of recommended rules, and we should fix issues reported by them.

and so I figured I'd try see if I could turn some of them on. I wasn't sure if this would break anything or not, I ran the tests and then figured why not see if this was correct or useful. Sorry to waste your time.

**Comment by JamesHenry** [comment]
Oh no at all, I really appreciate the offer of help! I'm afraid the new setup is just a little too new for us to have figured out good contributing guidance etc.

We'll definitely improve on that and hopefully we'll see some more PRs from you in the near future :)

**Comment by armano2** [comment]
idea of turning off `@typescript-eslint/no-var-requires` in js only files seems valid

we will ahve to fix few of errors only

**Pull request closed without merging**
