### PR TITLE
Adding yarn install documentation

### PR DESCRIPTION
**Pull request by HolgerJeromin**

### CODE REVIEW

**Review by bradzacher — CHANGES_REQUESTED** [review]
there's no specific requirement to use `yarn` here.
I (and other maintainers) use yarn because opinions - but there's not any specific reason it needs to be used.

You can get around in this repo perfectly fine with `npm`/`npx`.

**Comment by HolgerJeromin** [comment]
> there's no specific requirement to use yarn here.

One line below the documentation uses yarn.
IMO the steps to build this project should be easy to follow and complete.

> You can get around in this repo perfectly fine with npm/npx.

I would be fine with using npm, but this file documents the use of yarn.

**Comment by bradzacher** [comment]
I don't think instructing users to install yarn is the correct documentation.
Happy to instead improve these docs to show the `npm`/`npx` commands in addition.

**Comment by HolgerJeromin** [comment]
> I don't think instructing users to install yarn is the correct documentation.
> Happy to instead improve these docs to show the npm/npx commands in addition.

Ok. 
I will close the PR because moving an foreign package from a unknown package system (yarn) to another little known package system (npm) is out of scope for me.

**Pull request closed without merging**
