### PR TITLE
fix(scope-manager): fix incorrect handling of class decorators and class method default params

### LINKED ISSUE #2941: @typescript-eslint/no-use-before-define
```javascript
class A {
  constructor (printName) {
    this.printName = printName
  }

  openPort(printerName = this.printerName) {
    this.tscOcx.ActiveXopenport(printerName)

    return this
  }
}
```

image

image

### LINKED ISSUE #2942: A lot of no-undef in Vue @Component decorators after parser update
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

.eslintrc.js:
```js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    "plugin:vue/essential",
    "eslint:recommended",
    "@vue/typescript/recommended",
    "@vue/prettier",
    "@vue/prettier/@typescript-eslint",
  ],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    "no-console": process.env.NODE_ENV === "production" ? "warn" : "off",
    "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
  },
  overrides: [
    {
      files: [
        "**/__tests__/*.{j,t}s?(x)",
        "**/tests/unit/**/*.spec.{j,t}s?(x)",
      ],
      env: {
        jest: true,
      },
    },
  ],
};
```

App.vue:
```vue
@Component({
  components: {
    AppBar,
  },
})
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": ["webpack-env", "jest", "vuetify"],
    "paths": {
      "@/*": ["src/*"]
    },
    "lib": ["esnext", "dom", "dom.iterable", "scripthost"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": ["node_modules"]
}
```

**Expected Result**

When I use `"@typescript-eslint/parser": "4.13.0"` - tests are passing, no lining errors.

**Actual Result**
When I use `"@typescript-eslint/parser": "4.14.0"` - tests are failing, because of the lining errors:
```
> vue-cli-service lint **/*.{js,jsx,vue,ts,tsx,json} "--no-fix" "--max-warnings" "0"

error: 'components' is not defined (no-undef) at src/App.vue:48:3:
  46 | 
  47 | @Component({
> 48 |   components: {
     |   ^
  49 |     AppBar,
  50 |   },
  51 |   data: (): {


error: 'data' is not defined (no-undef) at src/App.vue:51:3:
  49 |     AppBar,
  50 |   },
> 51 |   data: (): {
     |   ^
  52 |     tabs: InterfaceTab[];
  53 |     cssVars: { "--min-drawer-width": string };
  54 |   } => ({


error: 'tabs' is not defined (no-undef) at src/App.vue:52:5:
  50 |   },
  51 |   data: (): {
> 52 |     tabs: InterfaceTab[];
     |     ^
  53 |     cssVars: { "--min-drawer-width": string };
  54 |   } => ({
  55 |     tabs: Object.keys(topLevelTabs).map((x) => ({
```

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.14.0` |
| `TypeScript`                | `4.1.3` |
| `ESLint`                    | `7.18.0` |
| `node`                      | `14.15.4` |

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #2941
Fixes #2942

This was a regression introduced by #2751

### CODE REVIEW

**Comment by astlaurent1** [comment]
@bradzacher We ran into this issue when installing latest today, which gave us v14.0. By any chance would you be able to create the v14.1 with this fix?

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint#package-versions

This will be released on Monday. If you need it sooner, it's available on the `canary` tag

**Comment by Machine-Maker** [comment]
Is this the fix for 
image
(getting `no-undef`s in decorators.

I tried installing the canary tag, and im still getting the `no-undef`s. (`yarn add -D @typescript-eslint/scope-manager@canary`)

**Comment by bradzacher** [comment]
> I tried installing the canary tag, and im still getting the no-undefs. (yarn add -D @typescript-eslint/scope-manager@canary)

You need to install the new version of the packages you're actually using - not a transient dependency.

Our packages all intentionally have their dependencies pinned to a specific version to ensure the state is consistent.
By installing just scope-manager, all you've done is installed that package locally - the old version is still installed and used at lint time because of the pinning..

**Comment by simllll** [comment]
We are suffering from this issue too, is there a new released already planned? Would be great :-) Thanks for your great project and all your efforts!

**Pull request merged**
