### PR TITLE
feat(eslint-plugin): Regenerate recommended config

### LINKED ISSUE #353: ban-ts-ignore is not in "plugin:@typescript-eslint/recommended" despite the docs saying so.
It should be recommended according to https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules. But simply extending `plugin:@typescript-eslint/recommended` does not enable the rule.

Adding the rule explicitly in `eslintrc.js` works though.

**Repro**

Repro to follow.

**Expected Result**

**Actual Result**

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.4.2` |
| `@typescript-eslint/parser`        | `1.4.2` |
| `TypeScript`                       | [`3.3.3333`](https://github.com/Microsoft/TypeScript/issues/30032) 😄 |
| `ESLint`                           | `5.15.1` |
| `node`                             | `11.11.0` |
| `yarn`                              | `1.13.0` |

### PR DESCRIPTION
**Pull request by bradzacher**
Also fix the bugs in the generation script.

Fixes #353

### CODE REVIEW

**Comment by mysticatea** [comment]
Would you ensure this will be released in the next major version? (semantic-release or conventional commits seem to require `BREAKING CHANGE:` text in the commit message)

**Comment by j-f1** [comment]
Should we add a check in CI that regenerates the config and ensures that it isn’t changed from the committed version?

**Comment by ldrick** [comment]
This PR is related and fixed in #313 too

**Comment by bradzacher** [comment]
@ldrick yeah I know, but your changes are a lot heavier and require some discussion from the core team first.
I wanted to wait, but I thought that as this was much smaller, I could slip it in quickly to correct the config before your PR is discussed and merged.

----

@j-f1 I thought about doing that right now, but I wanted this to be a tiny PR to slip in quickly to fix the issue.
I was thinking we could wait for #313 to be merged before setting up that CI script.
Hoping that we can discuss and merge that PR reasonably quickly.

----

@mysticatea - is adding new rules to the recommended config considered a breaking change?
Removing them from recommended would certainly be breaking, but isn't adding new rules a backwards compatible feature addition?

If it is breaking, then either:
- we're going to either be waiting a long time to add new rules to the recommended set (because we don't hugely want to release breaking changes to just do that one thing).
- or we're going to get super high version numbers because of the number of rules that are being added (there's 10 open PRs to add new rules, if each of those is released individually and added as recommended at the same time, we'll be at v11 [yes, I doubt we'd add all of them to recommended, and I doubt they'll be released individually, but the point still stands]).

**Comment by mysticatea** [comment]
> Should we add a check in CI that regenerates the config and ensures that it isn’t changed from the committed version?

It's better, but I didn't request such a check. I just wanted to make sure it because the commit message didn't contain any sign about breaking changes.

> is adding new rules to the recommended config considered a breaking change?

Definitely yes. It's a breaking change because the CI builds which use the recommended config gets reporting the new errors.

**Comment by bradzacher** [comment]
We should make note of the elsint semver policy in our readmes for future reference.

I'll close this then, considering we're doing a breaking change, we can wait for #313

**Pull request closed without merging**
