### PR TITLE
fix(eslint-plugin): fix crash in no-unnecessary-type-assertion

### PR DESCRIPTION
**Pull request by armano2**
Rule crashes when i try to use it in this project

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
This seems representative of a parse/conversion error. I’m fine with this as a fix but I want to take a look at your test cases and figure out what’s going wrong.

**Comment by armano2** [comment]
@uniqueiniquity i tried to setup this rule inside this project and i got a lot of false-positives with `any`, than i tried to disable any by using option and its started crashing. 
```
((Syntax as any).ArrayExpression = 'foo')
```
Syntax has no type in this case

**Comment by JamesHenry** [comment]
@uniqueiniquity Shall I wait to approve this so that you can look into it? I imagine that will make it easier to track?

**Comment by uniqueiniquity** [comment]
@JamesHenry looking now

**Comment by uniqueiniquity** [comment]
@armano2 @JamesHenry I've addressed the issue in in #226; it was an issue in convert after all :)

**Pull request closed without merging**
