### PR TITLE
feat(eslint-plugin): [explicit-function-return-type] allowHigherOrderFunctions (#193)

### LINKED ISSUE #193: [explicit-function-return-type] request option for curried arrow functions
## Proposal

Additional option for `explicit-function-return-type` ignores all but the final returned function when multiple fat-arrows appear in a function expression before a shared body.

```JSON
{
  "rules": {
    "@typescript-eslint/explicit-function-return-type": [
      "error",
      {
        "allowCurrying": true
      }
    ]
  }
}
```

## Purpose

In functional programming, currying is a common pattern. With this pattern a function taking multiple parameters is instead modeled as a unary (1-parameter) function that returns a unary function that returns a unary function, .etc. With arrow functions, you can express this quite elegantly, but the intermediate return types are (usually) not of meaningful importance.

## Example
Good: Explicit return given for last function returned by expression.
```TS
const foo = ( bar: string ) => ( baz: string ) => ( buz: string ) => ( biz: string ) : string =>
    `${ bar } ${ baz } ${ buz } ${ biz }`

const fiz = foo( 'bar' )( 'baz' )( 'buz' )( 'biz' )
```
Bad: Applied all parameters, but still failed to express a return type.
```TS

const badFoo = ( bar: string ) => ( baz: string ) => ( buz: string ) => ( biz: string ) =>
    `${ bar } ${ baz } ${ buz } ${ biz }`
```

Note that in the example, there are technically 4 different functions in the `foo` expression. But from a conceptual level, you can think of it as 1 function that must be called 4 times to apply all the parameters.

The type of `foo( 'bar' )` is "`foo` with the first parameter fixed as `'bar'`". Trying to express that explicitly through the type system is a painful exercise in meaningless verbosity. 

However, once *all* the parameters are given, it still makes sense to enforce an explicit return type for the final returned value.

### PR DESCRIPTION
**Pull request by Svish**
The last comment of #193 said that you were _Accepting PRs from the community (we love new contributors!!)_, and I really wanted #193 implemented, so... I gave it a shot, and... it _seems_ to work? All the existing tests and the 3 new ones I wrote for this seems to run fine at least? 🤔 🎉

Fixes #193

### CODE REVIEW

**Comment by Svish** [comment]
Really don't understand why 4 out of 5 of the Azure Pipeline checks failed after I updated the docs, but all were green before. 😕

**Comment by Svish** [comment]
All green again. Weird... 🤷‍♂️

**Comment by Svish** [comment]
That's fair. So you have some examples of what else should pass/fail with this new option?

**Comment by Svish** [comment]
That's fair. So you have some examples of what else should pass/fail with this new option?

**Comment by bradzacher** [comment]
Should probably support all of these cases, as no doubt people will ask for them down the line.
```ts
function FunctionDeclaration() {
  return function FunctionExpression_Within_FunctionDeclaration() {
    return function FunctionExpression_Within_FunctionExpression() {
      return () => { // ArrowFunctionExpression_Within_FunctionExpression
        return () => { // ArrowFunctionExpression_Within_ArrowFunctionExpression
          // etc
        }
      }
    }
  }
}

function FunctionDeclaration() {
  return () => { // ArrowFunctionExpression_Within_FunctionDeclaration
    // etc
  }
}
```

**Comment by Svish** [comment]
@JamesHenry Thanks to the examples provided by @bradzacher and some time looking at them through https://astexplorer.net, I think I figured out how to implement it for all(?) cases now (i.e. not just for `ArrowFunctionExpression`). The tests seem to run fine at least. Branch updated. 🙂👍

**Comment by Svish** [comment]
@bradzacher I see you already added an approval, but just so it's said: Docs have been updated with function example, and I added two tests to cover a missing branch in my changes.

I also looked into adding a test to cover [the very last uncovered branch](https://github.com/typescript-eslint/typescript-eslint/blob/1651e47ce68b9e9ea82297fe77916f908e448f79/packages/eslint-plugin/src/rules/explicit-function-return-type.ts#L226) in the file, but I'm pretty sure it's actually impossible to hit that branch?

We only get to the `if` when `node` is either `FunctionExpression` or `ArrowFunctionExpression`, which seems to always have a parent of `ExpressionStatement`? And even if that were to not be the case, there should still be a parent of `Program`?

So, to get the coverage up to 100% (and for others not to waste time trying to cover that branch too) I added an `istanbul ignore else` there.

**Comment by Svish** [comment]
@JamesHenry Could you explain what the difference is?

I don't mind changing the name though. What do you think @bradzacher?

**Comment by bradzacher** [comment]
IIRC technically currying is more the concept of functions which automatically return functions if you don't pass all of the required arguments, instead of explicitly defined functions returning functions.

In that regard, calling these higher order functions is technically more correct.

I think that either will work - people will probably understand either way.
But in case they don't, probs best to change it to something like `allowHigherOrderFunctions`.

**Comment by Svish** [comment]
@JamesHenry @bradzacher Alrighty, the option has now been renamed to technically more correct `allowHigherOrderFunctions`, and documentation and code adjusted accordingly. 🙂

**Comment by Svish** [comment]
@JamesHenry Is it good now? Anything else preventing a ✔ from you as well? Would really like to get this PR merged in, closed and released so I can make use of this new option in our project. 🙂

**Comment by Svish** [comment]
> I know I'm being the naming police on this, but this still isn't really currying that `allowCurrying` is allowing.
> 
> The implementation is more broad than that, it is allowing any higher order function pattern.
> 
> I think that is probably what is most valuable anyway, so it's just the name that needs to change, so that users aren't confused and think it checks explicitly for currying patterns.
> 
> I'm not married to it, but `allowHigherOrderFunctions` ?

@JamesHenry Your requested change was fixed over a week ago now. Is there still more you'd like to be changed, or is it good now?

**Pull request merged**
