### PR TITLE
chore: removed commitlint

### LINKED ISSUE #4962: Repo maintenance: remove commitlint
https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/

I have turned this option on - so now single commit PRs will use the PR title isntead of the commit message.
Now that means there's no reason for us to have commitlint installed or setup as a husky hook.
It's been a pet-peeve for a while now that local commits must follow the semantic commit standard - and I often bypass validations because of it!

We should remove the commit linter entirely.

Relatedly - it looks like we lost our CI job which validated the PR title - we should have validation setup for it there so that we can ensure that PR titles match the required format.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #4962
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Removes the `commitlint` package and lines that reference it.

Also removes `commitizen` and `cz-conventional-changelog`. I don't see anything still using them?

### CODE REVIEW

**Comment by bradzacher** [comment]
we can add some config to enable the signal for the PR title
https://github.com/zeke/semantic-pull-requests#configuration
File: `.github/semantic.yml`
```yaml
enabled: true
titleOnly: true
scopes:
  - ast-utils
  - ...
types:
  - feat
  - fix
  - docs
  - chore
  - test
  - revert
```

**Comment by bradzacher** [comment]
alternately we could setup our own action instead of using the app
https://github.com/amannn/action-semantic-pull-request

**Comment by armano2** [comment]
while at it we should remove `git-cz`

**Review by armano2 — APPROVED** [review]

**Review by bradzacher — APPROVED** [review]

**Comment by bradzacher** [comment]
Spun off the action discussion as a new issue #5085 5110

**Pull request merged**
