### PR TITLE
fix(eslint-plugin): [no-shadow] fix false-positive on enum declaration

### LINKED ISSUE #2360: [no-shadow] False positive for enum
**Repro**

I created a repo to reproduce the problem https://github.com/restrry/typescript-eslint-scope-bug

```JSON
{
  "rules": {
    "@typescript-eslint/no-shadow": "error"
  }
}
```

```TS
enum Direction {
    left = 'left',
    right = 'right',
}
```

**Expected Result**
No errors reported.

**Actual Result**
`  1:6  error  'Direction' is already declared in the upper scope  @typescript-eslint/no-shadow`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.0.0-alpha.5` |
| `@typescript-eslint/parser`        | `4.0.0-alpha.5` |
| `TypeScript`                       | `3.9.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `10.21.0` |
| `npm`                              | `N/A` |
| `yarn`                              | `1.21.1` |

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #2360

### CODE REVIEW

**Comment by bradennapier** [comment]
did this regress or is it not released yet?  all enums report `no-shadow` for me still on latest versions of everything.

**Comment by Kenadia** [comment]
> did this regress or is it not released yet? all enums report `no-shadow` for me still on latest versions of everything.

@bradennapier You may need to set the following rules:

```js
'no-shadow': 'off',
'@typescript-eslint/no-shadow': ['error'],
```

**Comment by derekparsons718** [comment]
It's unfortunate that the changelog does not indicate that the `no-shadow` rule was added. This PR is listed as a bugfix in the changelog, and makes it sound like the bug was simply fixed, instead of indicating that a new rule must be added to your config:

image

Not sure if this is something you want to address, but as more people make the switch to v4 I think it would help to have the changelog show that there is a new rule that replaces eslint's `no-shadow` -- probably in the "features" section of v4.0.0, the same way that `consistent-type-imports` is listed as a new rule.

There have already been several issues created because users don't know that the new rule is available when they upgrade.

**Comment by bradzacher** [comment]
The changelog is just an auto-generated log of commits bundled in each release.

Prefer the github release notes which are curated and explain in detail:
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0

**Comment by derekparsons718** [comment]
Totally makes sense. I just didn't realize that was where I needed to look, and apparently at least a few other people had the same problem, so I thought I would point it out :)

**Pull request merged**
