### PR TITLE
fix(eslint-plugin): [no-invalid-this] crash when used with eslint 8.7.0

### LINKED ISSUE #4444: no-invalid-this issue exception after upgrading to eslint 8.7.0
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-invalid-this": "warn"
  }
}
```

```TS
export function buttonChangeAddress(callback: UiButtonCallbackType): string { // eslint-disable-line promise/prefer-await-to-callbacks
```

**Expected Result**

no error thrown

**Actual Result**

After upgrading to eslint 8.7.0!

```bash
> eslint --cache --report-unused-disable-directives "./**/*.{js,jsx,ts,tsx}"


Oops! Something went wrong! :(

ESLint: 8.7.0

TypeError: rules.FunctionDeclaration is not a function
Occurred while linting /Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/components/addAddressDialog/index.ts:30
Rule: "@typescript-eslint/no-invalid-this"
    at FunctionDeclaration (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-invalid-this.js:51:23)
    at ruleErrorHandler (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/linter.js:1079:28)
    at /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/eslint/lib/linter/linter.js:1110:32
````

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.9.1` |
| `@typescript-eslint/parser`        | `5.9.1` |
| `TypeScript`                       | `4.5.4` |
| `ESLint`                           | `8.7.0Z` |
| `node`                             | `16.13.2` |

### PR DESCRIPTION
**Pull request by ota-meshi**
## PR Checklist

-   [x] Addresses an existing issue: fixes #4444
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Changed not to call the deleted method to prevent the `no-invalid-this` rule from crashing. As far as I can see the implementation of the core rule, I think it works fine.

### CODE REVIEW

**Comment by ota-meshi** [comment]
The `no-extra-semi` rule has also changed and needs to be fixed. I will open PR.
https://github.com/eslint/eslint/pull/15287

**Comment by bradzacher** [comment]
@ota-meshi - feel free to fix it in this PR as well for ease of updating.

**Comment by ota-meshi** [comment]
I reverted the version of eslint to make it easier to merge this PR.
We can later upgrade the eslint v8.7.0 with #4458.
We can see from the previous action result that `no-invalid-this` changed in this PR works with eslint v8.7.0.
https://github.com/typescript-eslint/typescript-eslint/runs/4837743893

**Comment by ota-meshi** [comment]
I find it difficult for me to prevent a loss of coverage as the code covered changes with each version of eslint 😅

**Review by bradzacher — APPROVED** [review]
thanks for this!

**Pull request merged**
