### PR TITLE
feat(eslint-plugin): add new rule restrict-plus-operands

### PR DESCRIPTION
**Pull request by armano2**
This PR implement rule `restrict-plus-operands`

- [x] implement rule
- [x] add tests
- [x] add documentation

continuation of https://github.com/bradzacher/eslint-plugin-typescript/pull/230

### CODE REVIEW

**Comment by bradzacher** [comment]
(shouldn't this be a feat?)

**Comment by armano2** [comment]
it should, i have some concerns about performance for now, i will have to digg in a little to check if this is not related to ts-estree

**Comment by JamesHenry** [comment]
I think looking to land this after the first release would be best 👍

**Comment by armano2** [comment]
i did profiling on this rule, and there is no performance impact generated by our code, TypeCheker is not fast, and most likely there is some room to improve it in `ts-estree`, but i did not found any direct issue in this rule iteself

**Comment by JamesHenry** [comment]
Ok great, thanks

**Pull request merged**
