### PR TITLE
chore: update sponsors

### PR DESCRIPTION
**Pull request by JamesHenry**
💸

### CODE REVIEW

**Review by JoshuaKGoldberg — COMMENTED** [review]
Lol. Is 420hubs an actual consumer sponsoring us to help out work, or is this just advertising?

(nothing against their content either way, 420 blaze it, I just worry about sponsor listings being used as cheap as space...)

**Review by bradzacher — COMMENTED** [review]
@JoshuaKGoldberg how are these sorted here / on the website?

Is it sorted by recency? Should we sory by total donated or something?

**Comment by JoshuaKGoldberg** [comment]
I can take a look again tomorrow. The last few entries have been... Odd.

**Comment by JoshuaKGoldberg** [comment]
Status update: yeah, these are definitely bogus accounts. I'm going to try to add some logic to prevent accounts that have very many negative transactions, or some similar logic.

**Comment by bradzacher** [comment]
We could probably just do something dumb like add an un-advertised minimum amount for a user to appear on our website?

**Pull request closed without merging**
