### PR TITLE
feat(eslint-plugin-tslint): add fixer for config rule

### PR DESCRIPTION
**Pull request by johnwiseheart**
Fixes: https://github.com/typescript-eslint/typescript-eslint/issues/1340

Add a fixer for the tslint config rule.

This was easier than expected - maybe I'm missing something? I'm not convinced this is tested enough, please give me any suggestions you have. I could maybe add an additional test for the `prefer-const` rule, which has a tslint fixer.

### CODE REVIEW

**Comment by johnwiseheart** [comment]
Hmm, its unclear to me what I need to do to fix the snapshots. The original commit was red and I tried to fix it, but looks like I fixed it wrong.

**Comment by armano2** [comment]
@johnwiseheart there should not be `;` in `packages/eslint-plugin-tslint/tests/fixture-project/4.ts`

first run failed due to integration test not unit test

see `tests/integration/fixtures/typescript-and-tslint-plugins-together/test.js.snap` 
you can regenerate it or just add changes:
```diff
      Object {
        "column": 20,
        "endColumn": 20,
        "endLine": 1,
+        "fix": Object {
+          "range": Array [
+            19,
+            19,
+          ],
+          "text": ";",
+        },
        "line": 1,
        "message": "Missing semicolon (tslint:semicolon)",
        "messageId": "failure",
        "nodeType": null,
        "ruleId": "@typescript-eslint/tslint/config",
        "severity": 2,
      },
```

**Comment by johnwiseheart** [comment]
Hmm, it looks like this time it failed for unrelated reasons. Tried running things locally, but because of my network it doesn't work by default (I have a self-signed cert in the chain) so hopefully rerunning it will be faster than my trying to figure that out.

**Comment by armano2** [comment]
ok, restarted, for some reason it failed on downloading node 11 😕

**Comment by johnwiseheart** [comment]
Sweet, good to merge from my end! Don't think I have permissions, so would appreciate it if you could hit the button 😄

**Comment by bradzacher** [comment]
sorry, forgot to hit it after waiting for the CI to finish

**Pull request merged**
