### PR TITLE
test: basic setup for benchmarks

### PR DESCRIPTION
**Pull request by armano2**
update:

**Single File: restrict-plus-operands**
```
tslint x 2.42 ops/sec ±5.84% (11 runs sampled)
eslint x 2,177 ops/sec ±8.03% (78 runs sampled)
Fastest is eslint
```

**Multi File: restrict-plus-operands**
```
tslint x 2.76 ops/sec ±2.33% (12 runs sampled)
eslint x 896 ops/sec ±2.58% (85 runs sampled)
Fastest is eslint
```

**Single File: no-empty-interface**
```
tslint x 1,636 ops/sec ±0.79% (90 runs sampled)
eslint x 2,584 ops/sec ±3.82% (76 runs sampled)
Fastest is eslint
```

**Multi File: no-empty-interface**
```
tslint x 1,202 ops/sec ±1.29% (90 runs sampled)
eslint x 1,018 ops/sec ±2.79% (82 runs sampled)
Fastest is tslint
```

https://github.com/typescript-eslint/typescript-eslint/issues/130#issuecomment-456996150

@aboyton @JamesHenry @uniqueiniquity @scottohara #55

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
@armano2 That's definitely a bug on me, then. The intent was absolutely to preserve the `Program`... that's kinda the whole point. Thanks for finding that. I can definitely look into this, but probably won't have time until early next week.

**Comment by JamesHenry** [comment]
@armano2 Is this marked as DO NOT MERGE because you are still working on it? Or do you not think we should merge it in general?

**Comment by JamesHenry** [comment]
Seems like it might be good to have a consistent benchmark to iterate against when fixing the performance issue

**Comment by armano2** [comment]
i'm still working on it, and i'm unsure if we should merge it :)

**Comment by j-f1** [comment]
Should we rename “DO NOT MERGE” to “WIP” and just close PRs we don’t plan to merge?

**Comment by armano2** [comment]
i did some profiling on all steps, and running parser take alot of time

```
typescript-estree x 19,657 ops/sec ±1.79% (84 runs sampled)
parser x 8,640 ops/sec ±2.16% (81 runs sampled)
```

parser is way way slower than it should, i have some profiles and i will continue to investigate

**Comment by bradzacher** [comment]
speeds are looking better!

**Comment by JamesHenry** [comment]
Speaking with @uniqueiniquity we have some code in right now designed with the long running (e.g. in editor/IDE) process in mind.

It would be ideal if we could add some benchmark around "watch" performance as well, although I appreciate that is less straightforward

**Comment by bradzacher** [comment]
Closing this for housekeeping purposes.

**Pull request closed without merging**
