### PR TITLE
feat(eslint-plugin): added new rule no-console

### PR DESCRIPTION
**Pull request by lonyele**
Hi!, I ported `no-console` from ESLint. It seems like [ESLint](https://eslint.org/docs/rules/no-console) and [TSLint](https://palantir.github.io/tslint/rules/no-console/) has different structure for options, but I chose ESLint style since it looks nicer in my opinion. 

As I see other PRs, newly implemented rules without ✅ may change their rule name or the internal details(event merged with other rule), so any feedbacks are needed here(it is almost my first time working on lint rule or tooling in general) Thanks in advance!

### CODE REVIEW

**Comment by bradzacher** [comment]
Hi @lonyele - what is new in this implementation of the rule?
What typescript-specific changes have you made to this rule when compared to the base eslint rule?

**Comment by lonyele** [comment]
I think nothing is really added? Hm... then `Typescript-specific` and rules that doesn't exist in ESLint should be implemented here? I thought any rules without ✅ on it are the ones to be implemented(you know I'm really new don't know what needs to be done here) Can you guide me what rules to be implemented?

**Comment by bradzacher** [comment]
In terms of tslint rules that can be implemented, rules with this symbol are the ones that we are looking for:
🛑 = unimplemented

We are generally looking for use cases for rules to be implemented from tslint. We don't just want to be pulling rules across by moving through the list, because we want to make sure people are actually going to use the rule.

A better choice for implementing rules is anything from the list of issues logged here:

requests for new rules:
https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+is%3Aopen+label%3A%22enhancement%3A+new+plugin+rule%22+-label%3A%22has+pr%22

requests for new options on existing rules:
https://github.com/typescript-eslint/typescript-eslint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22enhancement%3A+plugin+rule+option%22+-label%3A%22has+pr%22+

requests for "extensions" of rules from base eslint:
https://github.com/typescript-eslint/typescript-eslint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+-label%3A%22has+pr%22+label%3A%22enhancement%3A+new+base+rule+extension%22+

**Comment by lonyele** [comment]
Thanks a lot! I was trying to find the easy one for me to get to know what it is like in this repo and ended up found this one...(how naive my intention was) anyway, I'll try it!

**Pull request closed without merging**
