### PR TITLE
feat(eslint-plugin): add new import-order rule [CURRENT]

### PR DESCRIPTION
**Pull request by rathpc**
Forked from https://github.com/aboyton/typescript-eslint to keep this going and get things merged.

This PR will address feedback from the existing PR (https://github.com/typescript-eslint/typescript-eslint/pull/256) and any further feedback

### CODE REVIEW

**Comment by ark120202** [comment]
There are some other features `Organize Imports` command does, like removing unused imports, sorting `export from` and removing line feeds between imports. Probably they aren't required for the initial version, but maybe it would make sense to add a note to docs and rename this rule to `organize[d]-imports` to open path to implementing these features in the future?

**Comment by rathpc** [comment]
> There are some other features `Organize Imports` command does, like removing unused imports, sorting `export from` and removing line feeds between imports. Probably they aren't required for the initial version, but maybe it would make sense to add a note to docs and rename this rule to `organize[d]-imports` to open path to implementing these features in the future?

I can definitely take care of that!

**Comment by rathpc** [comment]
So I am digging into the code that was previously written and it doesn't seem to accommodate relative paths whatsoever which is probably why there were no previous tests for those.

I will need to play around with this when I have more time, I was hoping this would be a quick turnaround.

**Comment by bradzacher** [comment]
I think that there are two options for this rule.

1) we leverage the typescript language service's implementation of import ordering.
1) we duplicate the logic to emulate the same ordering implied by the ts language service.

Someone was saying that it's exposed as a private (hidden) API from typescript, so we might be able to leverage it directly so we don't have to duplicate the code. (option 1)

Otherwise, this rule should just take the above existing code, and convert it so it uses the ts-estree's AST nodes instead of ts's AST nodes, so it doesn't require type information.

I'm okay with either - I doubt that the import ordering service impl changes much if at all, so it's probably low maintenance to duplicate it, and it probably is good for us to decouple.

**Comment by rathpc** [comment]
ok, so for the purposes of our needs, we ended up just using `eslint-plugin-simple-import-sort` to handle import cleanup. It is not perfect and does not autofix on paste like `ordered-imports` used to with tslint but it does a pretty close job of what we needed.

With that being said I probably wont have the time to make further changes to this fork and PR. However if someone wants to fork my changes to finish this up, feel free!

**Comment by bradzacher** [comment]
I'll go ahead and close this PR.
There are refs to it in the original. No sense having two open.

Thanks for giving it a go!

**Pull request closed without merging**
