### PR TITLE
feat(typescript-estree): support `const` modifiers for type parameters

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## PR Checklist

- [x] Addresses an existing open issue: partial of #6380
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Based on #6570

Supports https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#const-type-parameters

TODO:

- [x] When https://github.com/typescript-eslint/typescript-eslint/pull/6599 is merged, adds test fixtures.

### CODE REVIEW

**Review by bradzacher — APPROVED** [review]
the change and fixtures LGTM!

**Comment by bradzacher** [comment]
> When #6599 is merged, adds test fixtures.

@sosukesuzuki what fixtures need to be added? Looks like it's pretty good coverage?

**Comment by sosukesuzuki** [comment]
> what fixtures need to be added? Looks like it's pretty good coverage?

Ah sorry, nothing. The PR description is written before adding fixtures.

**Comment by bradzacher** [comment]
Sweet - this is perfect then! We can get this in for the next release and we'll have 5.0 support!!

**Comment by sosukesuzuki** [comment]
Thank you for reviewing & merging this!

**Pull request merged**
