### PR TITLE
fix(eslint-plugin): [no-extra-semi] false negatives when used with eslint 8.3.0

### PR DESCRIPTION
**Pull request by ota-meshi**
## PR Checklist

-   [ ] Addresses an existing issue: fixes #000
-   [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

This PR modifies to call the changed method name of the `no-extra-semi` core rule.

This issue was found while working on #4448.
https://github.com/typescript-eslint/typescript-eslint/pull/4448#issuecomment-1014222118

### CODE REVIEW

**Comment by ota-meshi** [comment]
I need to include the #4448 change to fix the CI errors.

**Comment by ota-meshi** [comment]
I merged the main branch into this PR.

**Comment by WikiRik** [comment]
Will you enable the codepath additions from #4448 in here? Or will that happen in a third PR?

**Comment by ota-meshi** [comment]
> Will you enable the codepath additions from #4448 in here? Or will that happen in a third PR?

I will not add it in this PR. I think it needs a feature request.

**Comment by WikiRik** [comment]
So we need a feature request for the code you have added in the previous PR but commented out because you wanted to update the ESLint version here?

I think I might not have been clear enough in my previous message. I am just talking about un-commenting lines 714 and 715 of the eslint-rules typings file. Or is that not a working solution for #4444?

**Comment by ota-meshi** [comment]
For the same reason as #4448, I find it difficult to prevent loss of coverage for this PR.

**Comment by ota-meshi** [comment]
@WikiRik 
Code Path Analysis has long existed as an API for ESLint.
https://eslint.org/docs/developer-guide/code-path-analysis

However, the rules provided by typescript-eslint do not currently have rules that use the API (directly), so no type definition is needed either.
For now the `@typescript-eslint/no-invalid-this` rule doesn't even have to use it directly.

If you want to create a rule that uses Code Path Analysis and want to use the type definition provided by typescript-eslint, you'll need to request a feature.

**Comment by WikiRik** [comment]
Ah, so if I understand correctly it's not part of the solution for #4444. Then it's all good to me. Thanks for your work on these issues!

**Comment by bradzacher** [comment]
@WikiRik we don't need to worry about doing anything to the extension rule. The new code-path analysis selectors do not change the overrides we need to apply.

If it did - then the tests would be failing, which they are not.

In a nuttshell - previously the rule used explicit node selectors on things like functions to trigger the analysis. Our extension rule didn't touch that logic - it just augmented it so it could track `this` parameters and prevent the rule's `ThisExpression` selector appropriately.

Now the base rule uses the codepath selectors instead, but the overall logic doesn't change, thus nothing to change on our end aside from making sure we don't call undefined functions.

**Pull request merged**
