### PR TITLE
feat(eslint-plugin): [no-unnec-cond] check optional chaining

### PR DESCRIPTION
**Pull request by jridgewell**
This adds type checking around the the new optional-chaining feature. With this, it becomes invalid to start an optional chain when the base value is known to be not-nullish.

```js
// Good
declare const foo: string | null;
declare const bar: null | (() => {});
foo?.length;
foo?.slice();
bar?.();

// Bad
declare const baz: string;
declare const qux: (() => {});
baz?.length;
baz?.slice();
baz.slice?.();
qux?.();
```

### CODE REVIEW

**Comment by jridgewell** [comment]
Done.

**Comment by jridgewell** [comment]
Updated the docs to get the tests to pass.

**Comment by StephanBijzitter** [comment]
Please note: the release notes use the pull request title, so I updated my config to include `no-unnec-cond` and it didn't very much like it. Was a bit confusing :-)

**Comment by bradzacher** [comment]
Sorry, ESLint enforces commit message length when doing squash merges. It's also nice to keep things short enough (72 characters) so that the commit history on github doesn't truncate the message.

It's one of the pains of using semantic commit messages; it takes a lot of the character budget to do `feat(eslint-plugin): `

**Comment by StephanBijzitter** [comment]
No worries, we have the same issue ourselves :-)

The way we solve it is when squash-merging a pull request, we edit the body of the commit message to make it match again

**Pull request merged**
