### PR TITLE
fix(typescript-estree): enable error codes TS1085 and TS8017 for legacy octal literals

### PR DESCRIPTION
**Pull request by armano2**
This PR adds test cases for numeric values, and fixes issue with legacy octal number in non strict mode.

### CODE REVIEW

**Comment by armano2** [comment]
i'm starting to think, that it will be better if typescript itself will support this, instead of making us do special case fo it

**Comment by JamesHenry** [comment]
@uniqueiniquity What are you thoughts on this?

**Comment by sandersn** [comment]
@uniqueiniquity and I looked over the history of number parsing in Typescript and it looks like it's never really supported octal literals. `077` was always parsed to have the value 77. This wasn't even a [problem for us inside the compiler](https://github.com/Microsoft/TypeScript/issues/10101) until literal types were introduced. And the way we resolved the problem was not to support old-style octal syntax, but to put an error saying that the standard form was required. So I don't think we'll add correct support for old-style octal syntax in the value space either.

Out of curiosity, why does typescript-eslint need to support this syntax?

**Comment by armano2** [comment]
we don't have to, i just found issue in alignment tests with babel/estree.
@JamesHenry should we enable TS1085 instead?

**Comment by JamesHenry** [comment]
Yeah sounds good, @armano2

Thanks for sharing the background @sandersn!

**Pull request merged**
