### PR TITLE
fix(eslint-plugin): [consistent-indexed-object-style] do not autofix if interface has extends

### LINKED ISSUE #3007: [consistent-indexed-object-style] autofix deletes extended interfaces
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/consistent-indexed-object-style": ["error", "record"]
  }
}
```

```TS
interface A {
  a: unknown;
}

interface B extends A {
  [index: number]: unknown;
}
```

**Expected Result**

no change

**Actual Result**

```ts
interface A {
  a: unknown;
}

type B = Record<number, unknown>;
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.14.2` |
| `@typescript-eslint/parser`        | `4.14.2` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.19.0` |
| `node`                             | `14.15.4` |

### PR DESCRIPTION
**Pull request by armano2**
Disable reporting when interface has extends

fixes #3007

### CODE REVIEW

**Review by bradzacher — CHANGES_REQUESTED** [review]
this doesn't just prevent a fix - this also prevents reporting.
I don't think that's correct.

We can still report and leave it to the user to fix.

Or we can just fix it to an intersection type:
```ts
interface B extends A { [i: string]: number }
// fix to
type B = A & Record<string, number>;
```

**Comment by armano2** [comment]
we can't really fix,
```
interface B extends A { [i: string]: number }
// fix to
type B = A & Record<string, number>;
```

this is not same code, in many cases it may behave differently

**Comment by bradzacher** [comment]
I think we should still report on this and have the user figure out the best way to action.
It's not going to be clear to most people why this case isn't covered, and it'll look like a bug in the rule.

We can document it in the rule docs, but most people don't read those too deeply...

**Comment by armano2** [comment]
there is one more case that can cause issues,  when intereface has more than one extends
```ts
interface TypeB extends TypeA, TypeC {
	[i: string]: number
}
```

**Comment by armano2** [comment]
> I think we should still report on this and have the user figure out the best way to action.

ok, just changed it

**Review by bradzacher — APPROVED** [review]
thanks!

**Pull request merged**
