### PR TITLE
feat(eslint-plugin): [no-misused-object-likes] add rule

### LINKED ISSUE #6807: Rule proposal: Prevent `Object.values(...)` usage with `Map`
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Using `Object.values(...)`, `Object.keys(...)`, `Object.entries(...)` with a `Map` object is a foot-gun because it will return empty `[]` regardless of the map contents and is most likely a mistake. These sorts of mistakes are easy to get into during refactors. This issue is spawning from a real-life refactor mistake -> https://github.com/vector-im/element-web/issues/24995#issuecomment-1490776260

Related StackOverflow question: https://stackoverflow.com/questions/72315392/how-to-prevent-the-mistake-of-calling-object-values-on-a-map

As @bergus mentions from the SO question, it's possible to extend `Map` to make a subclass that returns something with the object utilities but this seems a lot more niche compared to the big problem of running them on base `Map` objects. AFAICT, it's not possible to use TypeScript on its own to catch this sort of thing because practically everything inherits from `Object` and function arguments in TypeScript are contravariant (accepts supertypes but doesn't accept subtypes).

### Fail Cases

```typescript
const map = new Map([[ 1, 'one' ],[ 2, 'two' ]]);

// Rule would error for each of these usages, as using these object utilities
// on a Map will just return empty results and is probably a mistake
Object.keys(map); // -> []
Object.values(map); // -> []
Object.entries(map); // -> []
```

### Pass Cases

```typescript
const myObject = { 1: 'one', 2: 'two' };
Object.keys(myObject); // -> ['1', '2']
Object.values(myObject); // -> ['one', 'two']
Object.entries(myObject); // -> [[ 1, 'one' ],[ 2, 'two' ]]

const map = new Map([[ 1, 'one' ],[ 2, 'two' ]]);
map.keys(); // -> ['1', '2']
map.values(); // -> ['one', 'two']
map.entries(); // -> [[ 1, 'one' ],[ 2, 'two' ]]
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by abrahamguo**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6807
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Based on #9369.

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
👋 Just checking in @abrahamguo, anything we can help with?

**Comment by abrahamguo** [comment]
Nothing I need at the moment! I should be able to get back to this PR in the next few days.

**Comment by abrahamguo** [comment]
No, unfortunately I haven't had time to work on these lately, so I'm happy to pass the torch!

**Comment by JoshuaKGoldberg** [comment]
You got it - thanks for getting this started!

Closing out this PR for now. To anybody reading this: feel free to use this as a reference. If you end up taking on any code from the PR, please include a co-authored-by attribution. Cheers!

**Pull request closed without merging**
