### PR TITLE
fix(typescript-estree): update TS version range

### PR DESCRIPTION
**Pull request by kentcdodds**
Ref: https://github.com/typescript-eslint/typescript-eslint/pull/3112#issuecomment-788200742

### CODE REVIEW

**Review by bradzacher — APPROVED** [review]
thanks!

**Comment by kentcdodds** [comment]
Looks like the release failed: https://github.com/typescript-eslint/typescript-eslint/runs/2007336501?check_suite_focus=true

**Comment by bradzacher** [comment]
nah that release is just the canary release.

the actual npm release is weekly (monday morning) or manual.
In this case we did a manual release.
https://www.npmjs.com/package/@typescript-eslint/eslint-plugin/v/4.16.1

The canary release always fails on the first commit after the weekly release because the weekly release makes a commit to bump the version, which triggers the automatic canary and releases it as `xx-alpha.0`.
Then lerna tries to make the first commit after that commit `xx-alpha.0` as well, hence it fails.

**Comment by kentcdodds** [comment]
Ah, cool! Thanks 👍

**Pull request merged**
