### PR TITLE
docs: added Konamimojisplosion easter egg to website

### LINKED ISSUE #4126: Investigate adding some kind of easter egg to the website
I talked with folks on Slack and it looks like the same Konamimojisplosion on codecademy.com websites is ok to add: https://github.com/Codecademy/konamimojisplosion.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

-   [x] Addresses an existing issue: fixes #4126
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md) were taken

## Overview

Adds https://github.com/Codecademy/konamimojisplosion as a Docusaurus client module. A fun little easter egg!

### CODE REVIEW

**Comment by bradzacher** [comment]
```
$ eslint . --ext .js,.ts
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

WHAT DID YOU DO?
(going to rerun the job)

**Review by bradzacher — COMMENTED** [review]
okay.. so something is causing ESLint to OOM on the CI.

**Comment by JoshuaKGoldberg** [comment]
🙃

**Comment by JoshuaKGoldberg** [comment]
How unfortunate 🙃.

A note: this is the first PR that exercises typed linting in `packages/website`. 754cfe9 was necessary to fix an existing config mishap where the tsconfig path was wrong.

**Comment by bradzacher** [comment]
does it OOM locally? it might just be CI?
I can take a closer look on the weekend

**Comment by JoshuaKGoldberg** [comment]
Same timeline... I'll draft this for now.

**Comment by bradzacher** [comment]
well apparently that js change fixed the linter!
the netlify deploy failed though:

```
11:28:46 AM: [success] [webpackbar] Server: Compiled with some errors in 49.46s
11:28:46 AM: ReferenceError: document is not defined
11:28:46 AM: Unable to build website for locale "en".
11:28:47 AM: Error: Failed to compile with errors.
11:28:47 AM:     at /opt/build/repo/node_modules/@docusaurus/core/lib/webpack/utils.js:202:24
11:28:47 AM:     at /opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:554:14
11:28:47 AM:     at processQueueWorker (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:491:6)
11:28:47 AM:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by Josh-Cena** [comment]
Client modules are still evaluated server-side: https://github.com/facebook/docusaurus/issues/4268

So you still need to guard against SSR🤷‍♂️

**Comment by JoshuaKGoldberg** [comment]
Ha, yeah, that's reasonable. I think there's a sub-bug that could be reported on the original call stack not being preserved:

```
2:28:46 PM: [success] [webpackbar] Server: Compiled with some errors in 49.46s
2:28:46 PM: ReferenceError: document is not defined
2:28:46 PM: Unable to build website for locale "en".
2:28:47 PM: Error: Failed to compile with errors.
2:28:47 PM:     at /opt/build/repo/node_modules/@docusaurus/core/lib/webpack/utils.js:202:24
2:28:47 PM:     at /opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:554:14
2:28:47 PM:     at processQueueWorker (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:491:6)
2:28:47 PM:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
2:28:47 PM: error Command failed with exit code 1.
2:28:47 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'll take the advice in that issue, thanks!

**Review by bradzacher — APPROVED** [review]

**Pull request merged**
