### PR TITLE
chore: bump Nx to 15

### LINKED ISSUE #6141: Repo: Bump Nx to the latest version
### Suggestion

We're on Nx 14 right now. Nx 15 is available. Let's upgrade!

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6141
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Runs `nx migrate latest` and accepts all changes. Also removes our sorta-invalid-JSON `"//": ...` comment entries in the `package.json` so automation won't mangle them in the future.

<details>
<summary>Aside: this is what our migrations file looked like from `nx migrate latest`</summary>

```json
{
  "migrations": [
    {
      "cli": "nx",
      "version": "15.0.0-beta.1",
      "description": "Replace implicitDependencies with namedInputs + target inputs",
      "implementation": "./src/migrations/update-15-0-0/migrate-to-inputs",
      "package": "nx",
      "name": "15.0.0-migrate-to-inputs"
    },
    {
      "cli": "nx",
      "version": "15.0.0-beta.1",
      "description": "Prefix outputs with {workspaceRoot}/{projectRoot} if needed",
      "implementation": "./src/migrations/update-15-0-0/prefix-outputs",
      "package": "nx",
      "name": "15.0.0-prefix-outputs"
    },
    {
      "cli": "nx",
      "version": "15.0.12-beta.1",
      "description": "Set project names in project.json files",
      "implementation": "./src/migrations/update-15-1-0/set-project-names",
      "package": "nx",
      "name": "15.1.0-set-project-names"
    }
  ]
}
```

</details>

Co-authored-by: @JamesHenry

### CODE REVIEW

**Review by bradzacher — DISMISSED** [review]
dependencies-balmer

**Review by JamesHenry — CHANGES_REQUESTED** [review]
> Except for mangling our sorta-invalid-JSON "//": ... comment entries in the package.json 😄

It's suddenly occurred to me that after this PR goes in, we will have this same problem with my automated migration github action (because this PR going in will stop renovate ignoring nx 15 bumps)

So I would say ideally we need to figure out a path forward on that before merging.

Do we think we can live without those comments? If not we will have to add some extra logic to the workflow to try and revert them after nx migrate reserializes the package.json

**Comment by JoshuaKGoldberg** [comment]
I'm down to just remove the comments.

**Comment by JoshuaKGoldberg** [comment]
I'm ok with just removing the comments. I think the code is rather self-evident.

**Review by JamesHenry — APPROVED** [review]

**Comment by JamesHenry** [comment]
Nice, thanks @JoshuaKGoldberg!

Btw now that we have the `name` field in project.json as the source of truth, we could potentially skip the `@typescript-eslint/` in all the names that Nx will use.

That would allow us to do `nx lint utils` instead of `nx lint @typescript-eslint/utils`. Less typing ftw?

**Comment by JamesHenry** [comment]
Applied that change here: https://github.com/typescript-eslint/typescript-eslint/pull/6160

**Pull request merged**
