### PR TITLE
chore(website): made the button contrast with outline and shadow

### LINKED ISSUE #5211: Docs: first homepage "Get Started" button background has low color contrast
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Screenshot of the Get Started button with blue fill on a dark blue background

Although the button's white text has enough color contrast against the blue button fill, the fill itself isn't very contrasted against the medium/dark blue background. That means users might not know what is or isn't safe to click on (interactive button or non-interactive background).

Suggested remediation: add some kind of outline/shadow to the button. Which is a nice design idea in general, to make it stand out more.

Discussed on stream with @BenDMyers on Twitch: https://www.twitch.tv/videos/1498962341. See https://benmyers.dev/blog/fix-low-contrast-text for a description of low contrast issues.

### Affected URL(s)

https://typescript-eslint.io

### PR DESCRIPTION
**Pull request by Aryan-Bhatt-pro**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #5211
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Made the button contrast with outline and shadow. Now the user will be able to see the button clearly and will trust that its safe to click it.

### CODE REVIEW

**Comment by Aryan-Bhatt-pro** [comment]
Hello, please let me know if the PR is satisfying the conditions. If in the case of rejection of the PR please let me know what went wrong so that I can improve on that.

**Comment by Josh-Cena** [comment]
This makes the button much, much less legible than before:

image

Also someone else is already working on it 😄 https://github.com/typescript-eslint/typescript-eslint/pull/5313 Next time, before submitting the PR, make sure there isn't another one addressing the same thing.

**Comment by bradzacher** [comment]
Yeah, sorry @Aryan-Bhatt-pro - #5313 was raise by another contributor yesterday!

**Comment by Aryan-Bhatt-pro** [comment]
Oh ok.
Sure will take care of that next time :)
Thanks for providing the clarity.

Regards
Aryan Bhatt

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Pull request closed without merging**
