### PR TITLE
feat(eslint-plugin): add no-unused-vars-experimental

### LINKED ISSUE #54: [no-unused-vars] false positive when generic param name masks name in parent scope
**Repro**

```JSON
{
  "rules": {
    "no-unused-vars": "off",
    "typescript/no-unused-vars": "error"
  }
}
```

```TS
type Foo = number

function test<Foo>(bar: Foo) {
    return bar
}
```

**Expected Result**
error that `type Foo` is not defined

**Actual Result**
all is good

**Additional Info**

There is few issues there:
- markVariableAsUsed is iterating over all variables even if found first one,
- type parameters are not validated

**Versions**

| package                    | version |
| -------------------------- | ------- |
| `eslint-plugin-typescript` | `1.0.0-rc.1` |
| `typescript-eslint-parser` | `internal` |
| `typescript`               | `3.1.1` |

### LINKED ISSUE #111: [no-unused-vars] does not count JSX as usage
**Repro**

```JSON
{
  "extends": ["plugin:@typescript-eslint/recommended"],
  "plugins": ["@typescript-eslint/eslint-plugin"],
  "rules": {
    "react/jsx-filename-extension": [1, {
      "extensions": [".ts", ".tsx", ".js", ".jsx"]
    }],
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
}
```

```TS
import React from 'react'; // 'React' is defined but never used. [@typescript-eslint/no-unused-vars]
import Document from 'next/document';
import {
  ServerStyleSheet
} from 'styled-components';

export default class MyDocument extends Document {
  public static async getInitialProps(ctx): DefaultDocumentIProps {
    const sheet = new ServerStyleSheet();

    const originalRenderPage = ctx.renderPage;
    ctx.renderPage = () => originalRenderPage({
      enhanceApp: App => props => sheet.collectStyles(<App {...props} />) // 'App' is defined but never used. [@typescript-eslint/no-unused-vars]
    });

    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: [...initialProps.styles, ...sheet.getStyleElement()]
    };
  }
}

```

**Expected Result**
Rule not trigger if a variable used as jsx
**Actual Result**
Rule trigger if a variable used as jsx
**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.0.0` |
| `@typescript-eslint/parser`        | `1.0.0` |
| `TypeScript`                       | `^3.2.4` |
| `ESLint`                           | `^5.12.1` |
| `node`                             | `v10.11.0` |
| `npm`                              | `6.4.1` |

### LINKED ISSUE #316: [no-unused-vars] False negative if param name matches function name in namespace
Hiya! Thanks for all the hard work on this project; I really appreciate how easy it's been to add Typescript linting to my existing ESLint config in a mixed language repo.

I upgraded a project from 1.3.0 to 1.4.1 and noticed a new error in a namespace that doesn't look right to me. I'm relatively new to Typescript (so please forgive me if I'm missing something basic here), but here's what I've got:

**Repro**

https://gist.github.com/mcous/3c80c5b0b901edb971014cd05a97a987

```js
module.exports = {
  root: true,
  extends: ['plugin:@typescript-eslint/recommended'],
  rules: {
    '@typescript-eslint/no-unused-vars': 'error',
  },
}
```

```TS
// types.d.ts
declare namespace Foo {
    function foo(foo: string): void // 'foo' is defined but never used.
}
```

**Expected Result**

No errors

**Actual Result**

```
error  'foo' is defined but never used  @typescript-eslint/no-unused-vars
```

**Additional Info**

- @typescript-eslint/eslint-plugin@1.3.0 - no errors
- @typescript-eslint/eslint-plugin@1.4.0 - error
- @typescript-eslint/eslint-plugin@1.4.1 - error

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.4.1` |
| `@typescript-eslint/parser`        | `1.4.1` |
| `TypeScript`                       | `3.3.3333` |
| `ESLint`                           | `5.14.1` |
| `node`                             | `8.11.2` |
| `npm`                              | `6.8.0` |

### LINKED ISSUE #363: [no-unused-vars] false positive for imported type alias
**Repro**

```JSON
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "prettier/babel",
    "prettier/react"
  ],
  "rules": {
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-parameter-properties": "off",
    "@typescript-eslint/no-unused-vars": ["on", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^ignored?$" }]
  },
}
```

```TS
import { KyInput, KyOptions, unwrap } from 'use-ky'

export function observeKy<T>(input: KyInput, options: KyOptions, unwrap: unwrap<T>): Observable<T> {
  if (input === null) {
    return observableOf<T>()
  }
```

**Expected Result**

All good

**Actual Result**

```
(alias) type unwrap<T> = (a: ResponsePromise) => Promise<T>
import unwrap

'unwrap' is defined but never used.eslint(@typescript-eslint/no-unused-vars)
```
**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.4.2` |
| `@typescript-eslint/parser`        | `1.4.2` |
| `TypeScript`                       | `3.3.3333` |
| `ESLint`                           | `5.15.2` |
| `node`                             | `10.7.0` |
| `yarn`                              | `1.12.1` |

### LINKED ISSUE #557: [no-unused-vars] False positive when using decorators
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/indent": ["error", 2],
    "@typescript-eslint/member-delimiter-style": [
      "warn",
      {
        "multiline": {
          "delimiter": "none",
          "requireLast": true
        },
        "singleline": {
          "delimiter": "semi",
          "requireLast": false
        }
      }
    ],
    "@typescript-eslint/explicit-function-return-type": "off",
    "no-console": "warn"
  }
}
```

```TS
const Decorator = () => {}
const Entity = () => {}

@Decorator(returns => Entity)
class Test {
  public test() {
    return 1 + 1
  }
}
new Test()
```

**Expected Result**
Decorator parameter should not create unused var warning

**Actual Result**
```'returns' is defined but never used.```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.9.0` |
| `@typescript-eslint/parser`        | `1.9.0` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.3.1` |
| `yarn`                              | `1.16.0` |

### LINKED ISSUE #571: [no-unused-vars] False positive with parameter decorators
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        "vars": "all",
        "args": "none"
      }
    ]
  }
}
```

```TS
// Create a parameter decorator
const log = function(target: Object, method: string, index: number) {
  console.log('decorating %s[%d]', method, index); 
}

class MyService {
  constructor(@log public x: string) {}
}
```

**Expected Result**

No violation of `unused-vars` is reported.

**Actual Result**

It complains that `log` is declared but not used.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.4.2` |
| `@typescript-eslint/parser`        | `1.4.2` |
| `TypeScript`                       | `3.4.5` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.1.0` |
| `npm`                              | `6.9.0` |

### LINKED ISSUE #696: [no-unused-vars] Inconsisitent behaviour with shadowed type name
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-unused-vars": ["error"]
  }
}
```

```TS
import { SomeType } from 'foo';
export function fn0(SomeType: SomeType){}

type AnotherType;
export function fn1(AnotherType: AnotherType){}

export function fn2(NonExistedType: NonExistedType) {}
```

**Expected Result**
All pass the rule or none of them pass the rule

**Actual Result**
Import is not OK, but the rest is fine even though the first parameter is not used.
When type node is visited, the parameter is marked as used..😰 see: https://github.com/typescript-eslint/typescript-eslint/issues/363

**Additional Info**
I know it's not possible to implement this rule without type information which will slow down the linting a lot.. But it should be possible to make the behavior consistent?

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `X.Y.Z` |
| `@typescript-eslint/parser`        | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `ESLint`                           | `X.Y.Z` |
| `node`                             | `X.Y.Z` |
| `npm`                              | `X.Y.Z` |

### LINKED ISSUE #937: [no-unused-vars] False positive for a class in declared namespace
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-unused-vars": ["error"]
  }
}
```

```TS
declare namespace shaka {
    class Player {
        public constructor();
        public destroy(): Promise<void>;
    }
}
export class C {
    public player: shaka.Player;

    public constructor() {
        this.player = new shaka.Player();
    }
}
```

**Expected Result**

No errors

**Actual Result**

error  'Player' is defined but never used @typescript-eslint/no-unused-vars

**Additional Info**

Very similar code but without namespace has no issues:

```typescript
declare class Player {
    public constructor();
    public destroy(): Promise<void>;
}

export class C {
    public player: Player;

    public constructor() {
        this.player = new Player();
    }
}
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.0.0` |
| `@typescript-eslint/parser`        | `2.0.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.2.0` |
| `node`                             | `11.14.0` |
| `npm`                              | `6.7.0` |

### LINKED ISSUE #965: [no-unused-vars] No error for unused class members
**Repro**

```JSON
{
  "rules": {
        "@typescript-eslint/no-unused-vars": [
            "error",
            {
                "vars": "all",
                "args": "after-used",
                "ignoreRestSiblings": false
            }
        ]
  }
}
```

```TS
class Foo {
   private bar: number= 0;
   private baz: boolean = false;

   public add() {
       this.bar++;
   }

   public decrease() {
       this.bar--;
   }

   private qux() {
       console.log('unused');
   }
}
```

**Expected Result**

Error for `baz` and `qux`.

**Actual Result**

No errors

**Additional Info**

It only catch unused vars inside the functions and args, but not for class members.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.1.0` |
| `@typescript-eslint/parser`               | `2.1.0` |
| `TypeScript`                              | `3.5.3` |
| `ESLint`                                  | `6.3.0` |
| `node`                                    | `8.11.3` |
| `npm`                                     | `6.11.2` |

### LINKED ISSUE #1011: [@typescript-eslint/no-unused-vars] Typeguard variable marked as unused
**What code were you trying to parse?**

```ts
declare type UserId = string // read as a refined type
const isUserId = (s: string): s is UserId => true
```

**What did you expect to happen?**
`w` should not be marked as unused.
**What actually happened?**
error  'w' is defined but never used @typescript-eslint/no-unused-vars
**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin-tslint` | `2.3.1` |
| `@typescript-eslint/parser`               | `2.3.1` |
| `TypeScript`                              | `3.6.3` |
| `ESLint`                                  | `6.4.0` |
| `node`                                    | `10.15.3` |
| `npm`                                     | `6.11.3` |

### LINKED ISSUE #1062: [no-unused-vars] ignores local tokens (type,interface)
**Repro**

```JSON
{
  "rules": {
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": "warn"
  }
}
```

```TS
// Expect Warning ✅
import { SomeType } from './types'

// Expect Warning ❌
interface ImNotUsed { }
// Expect Warning ❌
type NotUsedAsWell = unknown

type Empty = void

export const dummy = (): Empty => { console.log('dummy') }
```

**Expected Result**

local tokens `ImNotUsed`, `NotUsedAsWell` marked as unused

**Actual Result**

`ImNotUsed`, `NotUsedAsWell`  is ignored

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.2.0` |
| `@typescript-eslint/parser`        | `2.2.0` |
| `TypeScript`                       | `3.6.4` |
| `ESLint`                           | `6.3` |
| `node`                             | `10` |
| `npm`                              | `X.Y.Z` |

### PR DESCRIPTION
**Pull request by bradzacher**
Creates a new, experimental version of `no-unused-vars`.
This version leverages typescript's checker to report the unused vars, which saves us from having to build and maintain

Changes from `no-unused-vars`:
- Rule will only work inside a file that typescript deems to be either a commonjs or es6 module file.
    - This is because a lot of typescript's logic gates the unused variable checking behind [this function](https://github.com/microsoft/TypeScript/blob/fb50920a67dfbe75a2f2fac363f8bd89a25cbb08/src/compiler/utilities.ts#L951-L953). I'd link to the ts source, but it's in [`checker.ts`](https://github.com/microsoft/TypeScript/blob/d957b1c8c268b263832687b88eeec699f8866d8e/src/compiler/checker.ts) which is too big for github to render.
- Completely changed the rule options.
    - I think supporting all of the old options will be hard because Typescript has hardcoded support for ignoring underscore prefixed imports, function arguments, type parameter declarations, and object destructuring variables.
    - I ultimately decided on minimal changes to the underlying typescript checker functionality for simplicity, and because most people seem to like it.

Fixes #54
Fixes #111
Fixes #316
Fixes #363
Fixes #557
Fixes #571
Fixes #696
Fixes #937
Fixes #965
Fixes #1011
Fixes #1062

### CODE REVIEW

**Comment by Jamesernator** [comment]
If this requires type information I'd be objected to adopting this change. Currently we're not using the `no-unused-vars` because of the issue mentioned in #696 and instead depend on it as part of the TypeScript build instead.

We don't use any of the type-info requiring rules because they slow down eslint immensely and it makes eslint editor plugins basically unusable.

**Comment by bradzacher** [comment]
@Jamesernator - please have another look at the PR description, as well as the commit history on this PR (specifically 573070b).

There is a breaking change to `typescript-eslint` to allow this rule to be used WITHOUT providing `project`.

Additionally - if you've got an example codebase, or can provide data to help us diagnose exactly where slowness is - please comment on #389.

**Comment by uniqueiniquity** [comment]
@bradzacher This looks really good. I'll wait to actually approve until it's left WIP status, but I definitely support keeping around the node maps regardless of the `project` option. Your usage of the TS API looks fine to me, though I only really saw the point where you get semantic diagnostics from the program.

**Comment by ark120202** [comment]
One feature of `no-unused-vars` that was useful even with `noUnusedLocals` and `noUnusedParameters` enabled is `caughtErrors: 'all'` (to enforce use of optional catch binding). TypeScript intentionally decided not to make a diagnostic there, leaving it to a linter (see https://github.com/microsoft/TypeScript/issues/19601).

Apparently standard `no-unused-vars` with `{ varsIgnorePattern: '^(?!error$)', caughtErrors: 'all' }` options works there (assuming catch binding is always named `error`).

I think it would be good to do one of these things:
* Add a new rule to enforce it
* Add a special case in `@typescript-eslint/no-unused-vars`, but it would require to add a way to disable all diagnostic-based warnings (for people using compiler options)
* Add a note in docs recommending to use a standard rule instead

**Comment by bradzacher** [comment]
> Add a note in docs recommending to use a standard rule instead
This isn't an option because there are so many false positives.

I would go with implementing a new rule to check unhandled exception
I don't really want to mix logic within this new implementation - i.e. I'd want the trigger for all errors reported by this implementation to be from typescript diagnostics.

---

The usages that I've seen within the TS community is that they love the `noUnused*` compiler options, but they _hate_ that they are build blocking errors. This implementation fixes that problem.

I thought about continuing the work to complete the TS specific scope analyser (which would fix the base impl of rule, and a few other rules), but I figured that this was significantly less work, and a lot more interesting because it's aligned with what typescript does by default.

**Comment by ark120202** [comment]
> I would go with implementing a new rule to check unhandled exception

:+1:, that's my preferred option as well

> The usages that I've seen within the TS community is that they love the `noUnused*` compiler options, but they hate that they are build blocking errors.

One thing I'd like to say there is that I've personally always seen TypeScript as a linter. Ignoring any errors to run tests is really convenient during a refactor. There has been a discussion in https://github.com/typescript-eslint/typescript-eslint/issues/122#issuecomment-462972192, but since then ts-node got a [--disableExit](https://github.com/TypeStrong/ts-node/pull/818) option. Maybe it would make sense to get some more feedback on the reason why people have to use `noEmitOnError` now?

**Comment by bradzacher** [comment]
> Maybe it would make sense to get some more feedback on the reason why people have to use noEmitOnError now?

A lot of the time people have `noEmitOnError` on by default because it prevents emitting broken code during watch rebuild cycles. Otherwise things like webpack will happily hot reload broken code to your browser causing hard failures instead of nice reloaded screens.

It's the same philosophy that `create-react-app`'s typescript integration has - they don't use the `noUnused*` options because they are build blocking non-errors, so instead they use our version of `no-unused-vars` (which has false positives).

As another point - it's also generally easier to have a single tsconfig instead of having both a production one, and a development one. Because you don't want to output broken code to prod, you have `noEmitOnError` on in your single config.

This philosophy probably stems from the ambiguity of what tsconfig extensions do (it merges `compilerOptions` objects together, but it feels like it should overwrite because `include`/`exclude`/`files` overwrite).

**Comment by Lonli-Lokli** [comment]
When this feature might be released?
It;s pretty annoying to have a lot of excludes in varsIgnorePattern (https://github.com/typescript-eslint/typescript-eslint/issues/571) for the project with decorators (actually for all Angular projects)

**Comment by akoidan** [comment]
@bradzacher is there any way to make it work with vue-tempaltes? When a variables is used in the `<template` with vue-property-decorator

**Comment by bradzacher** [comment]
Uhh.. not easily, no.
I didn't design this with vue's custom build chain in mind (as I wrote this before I knew anything about how ridiculously custom vue's build chain is).

This rule would have to be updated to support the `eslintUsed` property that rules like `vue/no-unused-vars` rely upon to function.

**Comment by mik-jozef** [comment]
> This rule would have to be updated to support the `eslintUsed` property that rules like `vue/no-unused-vars` rely upon to function.

Is this planned to be solved/is there an issue somewhere for this? I couldn't find any.

**Comment by bradzacher** [comment]
nope. please file an issue if it's something important to you.
happy to accept a PR as well.

**Comment by lsotoangeldonis** [comment]
> > This rule would have to be updated to support the `eslintUsed` property that rules like `vue/no-unused-vars` rely upon to function.
> 
> Is this planned to be solved/is there an issue somewhere for this? I couldn't find any.

Don't know if helps, but this worked for me using vue and typescript:

**Pull request merged**
