### PR TITLE
chore: support typescript 3.6

### LINKED ISSUE #932: Security alert eslint-utils
Dear repository contributors,

today I got an email by GitHub that one of my dependencies is vulnerable and thus should be updated.

I took a look and found out that `@typescript-eslint/parser` uses v1.3.1 of `eslint-utils` which has been found vulnerable.

Please update it to at least v1.4.1 as that version fixed the vulnerability.

Thanks!

### LINKED ISSUE #935: Explicitly support TypeScript 3.6
At the moment when running eslint I get a warning about typescript version.
The maximum supported is 3.6.0, but there is a minor version 3.6.2 that have some fixes.
This warning should not be issued if there is only a minor revision change, a minor version bump should not issue any warning

**What code were you trying to parse?**

```sh
eslint file.ts
```

**What did you expect to happen?**

No warnings

**What actually happened?**

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.6.0

YOUR TYPESCRIPT VERSION: 3.6.2

Please only submit bug reports when using the officially supported version.

=============

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.0.0` |
| `TypeScript`                | `3.6.2` |
| `ESLint`                    | `6.3.0` |
| `node`                      | `12` |
| `npm`                       | `6.11.2` |

### PR DESCRIPTION
**Pull request by bradzacher**
plus bump other deps
Fixes #932 
Fixes #935

Ignored a bunch of new ast-alignment failures from both bumping `@babel/parser` to 7.5.5, as well as ts to 3.6.x

### CODE REVIEW

**Comment by deser** [comment]
Should you remove `tslint` from deps? :)

**Comment by bradzacher** [comment]
Which deps? Unless I'm mistaken tslint only exists in the root project deps, which are dev-only deps. It's required for testing `eslint-plugin-tslint`.

**Comment by deser** [comment]
Ok, thanks for explaining

**Comment by JamesHenry** [comment]
@bradzacher Let's add it to the things we ignore for now, we can loop back to the AST alignment testing later.

Let me know once this is ready to go and we'll get it merged!

**Pull request merged**
