### PR TITLE
chore: enable unicorn/prefer-spread

### PR DESCRIPTION
**Pull request by abrahamguo**
## PR Checklist

- [x] Addresses an existing open issue: fixes part of #9623 
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ ] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Enable `unicorn/prefer-spread` ([docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-spread.md)).

I particularly like the replacements of the style `a.concat(b)` => `[...a, ...b]` because I like that `a` and `b` are given "equal weight" visually when they are both spread into a new array, whereas with `concat` one is before the `concat` and one is inside the `concat` and so visually they don't have "equal weight".

### CODE REVIEW

**Comment by kirkwaiblinger** [comment]
I agree with all these changes except the ones that use `[...expr]` instead of `Array.from(expr)`

**Comment by abrahamguo** [comment]
My thoughts are — it's better to use a language construct (`...`) rather than a function (`Array.from`) when available. It's shorter as well 🤷‍♂️

**Review by kirkwaiblinger — DISMISSED** [review]
Ok, works for me 🙂

**Review by JoshuaKGoldberg — APPROVED** [review]
I also like this :)

**Pull request merged**
