### PR TITLE
chore: group jest versions in renovate config

### LINKED ISSUE #7537: Repo: Group jest versions in the renovate config?
### Suggestion

We just got a while bunch of Jest PRs pinning to 29.6.3:

* #7528
* #7529
* #7530
* #7531
* #7532
* #7533

Maybe we should group them in Renovate config, so they're all sent as one PR?

For reference, we already do this for a few other groups of related packages:

https://github.com/typescript-eslint/typescript-eslint/blob/1d26d87b3c6869da00ecadac6f68b3fc7c83208d/.github/renovate.json5#L59-L63

### PR DESCRIPTION
**Pull request by peanutenthusiast**
## PR Checklist

- [x] Addresses an existing open issue: fixes #7537 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I updated the jest config to match the babel config, as suggested here: https://github.com/typescript-eslint/typescript-eslint/issues/7537#issuecomment-1693273153

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
> ```md
> - [✔️ ] Addresses an existing open issue: fixes #7537 
> ```

Psst - these should be filled out with just `[x]`. It's a GitHub feature: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists. Though I do appreciate using emojis 😄

**Comment by peanutenthusiast** [comment]
Hi @bradzacher and @JoshuaKGoldberg , I wanted to check in with you both to gauge any additional changes necessary for this PR!

**Review by bradzacher — APPROVED** [review]
this looks good to me - sadly there's no way to test it.
so we'll just land it and see what happens :)

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/7651

Looks like it worked just fine!
Thanks heaps!!

**Pull request merged**
