### PR TITLE
fix(eslint-plugin): [return-await] don't error for `in-try-catch` if the return is in a `catch` without a `finally`

### LINKED ISSUE #2344: [return-await] await should be required in catch block only when it has a finally block
**Repro**

```ts
async function main(){
  try {
    throw "foo"
  } catch(e) {
    return Promise.resolve("bar");
  }
}
```

```JSON
{
  "rules": {
    "no-return-await": ["error"],
    "@typescript-eslint/return-await": ["error", "in-try-catch"]
  }
}
```

**Expected Result**

No error

**Actual Result**

Returning an awaited promise is required in this context. (line 5)

**Additional Info**

This issue can cause this rule to be in conflict with eslint's `no-return-await`. Adding the await to resolve `@typescript-eslint/return-await` will then trigger `no-return-await`

> `function hasErrorHandler(node)`: Determines whether a thrown error from this node will be caught/handled within this function rather than immediately halting this function. For example, a statement in a `try` block will always have an error handler. A statement in a `catch` block will only have an error handler if there is also a `finally` block.
> <https://github.com/eslint/eslint/blob/master/lib/rules/no-return-await.js#L51-L58>

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `3.7.1` |
| `@typescript-eslint/parser`        | `3.7.1` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `7.5.0` |
| `node`                             | `12.16.1` |
| `yarn`                              | `1.22.4` |

### PR DESCRIPTION
**Pull request by soobing**
Fixes #2344

Added below two TC, and fixed.
- if you return a promise within a catch, and there is no finally, then it must not be awaited.
- if you return a promise within a finally, then it must not be awaited.

### CODE REVIEW

**Comment by bradzacher** [comment]
So the issue in question isn't that the code was erroring - it's that it shouldn't error.

The code should work in the following way for `in-try-catch` mode:
- if you return a promise within a `try`, then it must be awaited.
- if you return a promise within a `catch`, and there ***is no*** `finally`, then it ***must not*** be awaited.
- if you return a promise within a `catch`, and there ***is a*** `finally`, then it ***must*** be awaited.
- if you return a promise within a `finally`, then it ***must not*** be awaited.

**Comment by soobing** [comment]
Aha.. thanks for the kind explanation.
I will try again.

**Comment by soobing** [comment]
@bradzacher 
Hi, I tried again. Please review my code 😋. 
I Also change this PR's description https://github.com/typescript-eslint/typescript-eslint/pull/2356#issue-462762406

**Comment by soobing** [comment]
@bradzacher hi, could you review again? I don't know How to ask review again so I am mentioning 🦊

**Review by bradzacher — CHANGES_REQUESTED** [review]
The code LGTM.
Thanks for your work!

Could you please update the docs for the `in-try-catch` option?

Specifically, could you make it very clear how it works, doing something like this will be good.

-----

## `in-try-catch`

Requires that a returned promise must be `await`ed in `try-catch-finally` blocks, and disallows it elsewhere. Specifically:

- if you `return` a promise within a `try`, then it must be `await`ed.
- if you `return` a promise within a `catch`, and there ***is no*** `finally`, then it ***must not*** be `await`ed.
- if you `return` a promise within a `catch`, and there ***is a*** `finally`, then it ***must*** be `await`ed.
- if you `return` a promise within a `finally`, then it ***must not*** be `await`ed.

**Comment by soobing** [comment]
@bradzacher Thanks for review!
I updated the docs and also added some example.

**Comment by dbalde** [comment]
Hello World

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for your work

**Pull request merged**
