### PR TITLE
docs: modify type description

### PR DESCRIPTION
**Pull request by XinChou16**
## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ ] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

fix docs type error

### CODE REVIEW

**Comment by XinChou16** [comment]
look at this, https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/parser/README.md#parseroptionsprograms

so there should be program ? @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
Aha, that does look like a docs typo - yes!

**Comment by JoshuaKGoldberg** [comment]
Interesting - so we do have `interface ParseAndGenerateServicesOptions extends ParseOptions` inside the `typescript-estree` package, that contains a `programs?: ts.Program[]`.

https://github.com/typescript-eslint/typescript-eslint/blob/efc147b04dce52ab17415b6a4ae4076b944b9036/packages/typescript-estree/src/parser-options.ts#L166-L171

But, that's not the same as what the parser README is describing. I think this rolls up into #5090: this area of code isn't quite documented for end users.

**Comment by XinChou16** [comment]
OK，I got it, thanks a lot.

**Pull request closed without merging**
