### PR TITLE
fix(eslint-plugin): [return-await] handle nested functions correctly

### PR DESCRIPTION
**Pull request by MichaelBelousov**
fix for #3600

### CODE REVIEW

**Comment by MichaelBelousov** [comment]
@bradzacher is the apparent Nx Cloud Report something that is blocking this PR?

**Comment by MichaelBelousov** [comment]
@bradzacher sorry for bothering, but it's been silent so I don't know where we're at with this one. Is this slated for review?

**Comment by bradzacher** [comment]
> [The core maintainers work on this in their personal time, so please understand that it may not be possible for them to review your work immediately.](https://github.com/typescript-eslint/typescript-eslint/pull/3601#issuecomment-873238939)

https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md#addressing-feedback-and-beyond

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for fixing this!

**Pull request merged**
