### PR TITLE
fix(ast-spec): NewExpression argument can be SpreadElement now

### LINKED ISSUE #5421: Bug: NewExpression doesn't allow SpreadElement as argument
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

`NewExpression` and `CallExpression` are basically identical in terms of arguments list. Among others, you're perfectly fine with spreading arguments in both of them:

```ts
class A { constructor(...args: unknown[]) {} }
const a = new A(...someArray);

const F = (...args: unknown[]) => {}
const f = F(...someArray);
```

That is reflected in `CallExpression` type:
https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/ast-spec/src/expression/CallExpression/spec.ts#L7-L10
With `CallExpressionArgument` being:
https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/ast-spec/src/unions/CallExpressionArgument.ts#L4

At the same time, `NewExpression` typing allows only `Expression` arguments:
https://github.com/typescript-eslint/typescript-eslint/blob/d2394f810960fda07b9c8affd47b769d16f4b8cb/packages/ast-spec/src/expression/NewExpression/spec.ts#L7-L10
`SpreadElement` is not there, even though it is legal to spread arguments in constructor call ([playground](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&showAST=ts&code=MYGwhgzhAECC0G8CwAoa1gHsB2EAuATgK7B6YEAUAdDWAQOYQBc0R2A1tpgO7YDaAXQCUiaAF9UElKiy480OgWgBeaHwCMAGmgAmbQGYBqGTnwKV0bAFNucarQIEhqIA))

### Fail

```typescript
n/a
```

### Pass

```typescript
n/a
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by burtek**
## PR Checklist

-   [x] Addresses an existing open issue: fixes #5421
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

NewExpression argument can be SpreadElement now. See https://github.com/typescript-eslint/typescript-eslint/issues/5421 for details

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks for the quick fix!

Is this technically a breaking change @bradzacher?

**Comment by burtek** [comment]
> LGTM, thanks for the quick fix!

No problem, was surprised when I found this

> Is this technically a breaking change @bradzacher?

If you don't mind, how would this change be a breaking change? I don't see any case how this might break existing code, but obviously I must be missing something?

**Comment by bradzacher** [comment]
Technically it is breaking because someone could previously have code like

```ts
declare function acceptsExpr(node: Expression): void;

declare const newExpr: NewExpression;

acceptsExpr(newExpr);
```

Which will now have a TS error - thus breaking as the users build could break due to the new version.

Though in general we don't classify this sort of correctness change as breaking because the above code is already broken, and all we've done is expose that broken code to the user.

**Comment by burtek** [comment]
Right, thanks!

**Comment by burtek** [comment]
@JoshuaKGoldberg @bradzacher sooo, in terms of merging...? Don't wanna look like I'm making you hurry or something, just making sure you don't forget about this PR after the conversation 😆 as far as I know there is a release each monday?

**Comment by JoshuaKGoldberg** [comment]
😄 no worries on the ping, you raise a good question! Per Brad's point on this generally only breaking already-broken code I think it's safe to go. But I'll defer to @bradzacher here, as Brad's done much more than me with the AST & managing technical breakage.

**Comment by JoshuaKGoldberg** [comment]
P.S. @burtek - I appreciate you keeping this branch up-to-date, but you don't have to if you don't want. 😄

**Review by bradzacher — APPROVED** [review]
lgtm - thanks for doing this!

**Comment by burtek** [comment]
> P.S. @burtek - I appreciate you keeping this branch up-to-date, but you don't have to if you don't want. 😄

Good to know :D Github said branch is out of date, I thought it's necessary xD

**Pull request merged**
