### PR TITLE
fix(eslint-plugin): [no-magic-numbers] Support negative numbers

### LINKED ISSUE #1070: [no-magic-numbers] False positive for negative readonly class properties
**Repro**
```JSON
{
  "rules": {
    '@typescript-eslint/no-magic-numbers': [
            'error',
            {
                'ignore': [-1, 0, 1, 2],
                'ignoreEnums': true,
                'ignoreNumericLiteralTypes': true,
                'ignoreReadonlyClassProperties': true
            }
        ],
    'no-magic-numbers': 'off',
  }
}
```

```TS
export class Class
{
    public static readonly NEGATIVE_NUMBER = -127;
}
```

**Expected Result**
No `@typescript-eslint/no-magic-numbers` error for either number

**Actual Result**
`[@typescript-eslint/no-magic-numbers] No magic number: -127.` but not for the positive number

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.3.2` |
| `@typescript-eslint/parser`        | `2.3.2` |
| `TypeScript`                       | `3.6.3` |
| `ESLint`                           | `6.5.1` |
| `node`                             | `v10.16.3` |
| `npm`                              | `6.12.0` |

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #1070

### CODE REVIEW

**Comment by bradzacher** [comment]
did we want to handle explicitly positive numbers at the same time?
It's probably a rare case, but it might be worth chucking the handling in to make sure nobody ever complains about it?

(I don't use this rule, so IDK if it's worth the effort)
WDYT?

**Comment by a-tarasyuk** [comment]
@bradzacher 

There are several Unary Operators which can potentially cause issues and which are all applied to numbers

```TS
class A {
  public readonly A = +127;
  public readonly B = -127;
  public readonly C = ~127;
  public readonly D = ++127;
  public readonly D = --127;
}
```

Does that make sense to handle all of them?

**Comment by bradzacher** [comment]
I don't think that people will use anything other than +/- when delcaring a constant.

`++`/`--` form an UpdateExpression instead.
`~` is a bitwise operator which I don't think is useful for defining magic number constants.

**Comment by a-tarasyuk** [comment]
@bradzacher ok, added `+`.

**Comment by orlov-vo** [comment]
It seems like it doesn't work in enums:

```ts
enum Status {
    NONE = 0,
    START = 1,
    ERROR_DNS = -2,
    ERROR_INSTALL = -6
}
```

**Comment by bradzacher** [comment]
Please raise a new issue. Commenting on an old, closed PR is  bad way to let us know of bugs.

**Pull request merged**
