### PR TITLE
fix(eslint-plugin): [type-annotation-spacing] report excess spaces as error

### LINKED ISSUE #1001: [type-annotation-spacing] Number of spaces aren't enforced
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/type-annotation-spacing": "error"
  }
}
```

```TS
class Foo {
    private bar:          Bar;
}
```

**Expected Result**
Error for member filed `bar`, that have more than one space after colon.

**Actual Result**
No error

**Additional Info**
The current rule enforces the spaces as described, but it doesn't enforce how much spaces there is.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.1.0` |
| `@typescript-eslint/parser`               | `2.1.0` |
| `TypeScript`                              | `3.5.3` |
| `ESLint`                                  | `6.3.0` |
| `node`                                    | `8.11.3` |
| `npm`                                     | `6.11.2` |

### PR DESCRIPTION
**Pull request by darcien**
Fixes #1001

### CODE REVIEW

**Comment by darcien** [comment]
> code itself looks good, but we should probably handle extra spacing on both sides of the delimiter.

Aaah right, I'll update it.

**Comment by darcien** [comment]
For the tests, I'm not sure how many test cases I should add though.

If I added too many, the test will be failing.

Something like this:
```
Summary of all failing tests
 FAIL  tests/rules/type-annotation-spacing.test.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    tests/rules/type-annotation-spacing.test.ts:1044:11 - error TS2322: Type 'string' is not assignable to type '"expectedSpaceAfter" | "expectedSpaceBefore" | "unexpectedSpaceBefore"'.

    1044           messageId: 'unexpectedSpaceBefore',
                   ~~~~~~~~~

      ../../node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/RuleTester.d.ts:21:5
        21     messageId: TMessageIds;
               ~~~~~~~~~
        The expected type comes from property 'messageId' which is declared here on type 'TestCaseError<"expectedSpaceAfter" | "expectedSpaceBefore" | "unexpectedSpaceBefore">'

```

**Comment by bradzacher** [comment]
It's a really weird error, I know - it's a weird way that typescript reports the error.
That type error usually occurs because there is something wrong with the test you've added - either there's a typo in a prop name, a missing property, or similar.
I usually narrow it down by commenting out tests one-by-one until I find out which one has the error.

**Comment by armano2** [comment]
@darcien i did some testing and this type issue got solved (is no longer present in experimental-utils/typescript)

after running this rule it seems to try to add spaces after `:` by default (in our case this is conflicting with prettier)

```
      node:
        | TSESTree.VariableDeclarator
        | TSESTree.Parameter
        | TSESTree.ClassProperty,
```

becomes:

```
      node: | TSESTree.VariableDeclarator
        | TSESTree.Parameter
        | TSESTree.ClassProperty,
```

**Comment by bradzacher** [comment]
> in our case this is conflicting with prettier

We should probably add the `prettier/@typescript-eslint` config to our codebase.
Prettier is not expected to play nicely with formatting rules.

**Pull request closed without merging**
