### PR TITLE
fix(eslint-plugin): [no-base-to-string] handle intersection types

### LINKED ISSUE #2162: [no-base-to-string] complains about intersection types
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-base-to-string": <default>
  }
}
```

```TS
export interface Brand {}
export function test(v: string & Brand): string {
  return `${v}`; // v will evaluate to '[object Object]' when stringified
}
```

**Expected Result**

The error shown in the comment is reported.

**Actual Result**

The error should not be reported, because `v` is known to be a `string`.

**Additional Info**

This is a very simplified case just to allow quick reproduction. In practice I encountered this using [branded types from the io-ts library](https://github.com/gcanti/io-ts/blob/master/index.md#branded-types--refinements). Note that their technique can be used with other types, not just strings.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.31.0` |
| `@typescript-eslint/parser`        | `2.31.0` |
| `TypeScript`                       | `3.8.3` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.16.1` |
| `npm`                              | `6.14.2` |

### PR DESCRIPTION
**Pull request by bogdanb**
Fixes #2162 [no-base-to-string] complains about intersection types

### CODE REVIEW

**Comment by bogdanb** [comment]
Hi guys! I’m not sure exactly what’s going on with the code coverage test. Either I’m not understanding its report, or I missed something about how the tests work. I expected better coverage from those tests. Any hints?

(Also, I’d appreciate some hints on how to lint a local project using the patched code instead of the ones from npm.)

**Comment by bradzacher** [comment]
Codecov comments sometimes do weird things.
What you want to look at is the codecov UI

https://codecov.io/gh/typescript-eslint/typescript-eslint/pull/2170/diff?src=pr&el=tree#diff-cGFja2FnZXMvZXNsaW50LXBsdWdpbi9zcmMvcnVsZXMvbm8tYmFzZS10by1zdHJpbmcudHM=

**Comment by bogdanb** [comment]
@bradzacher Hi Brad! Is there a way I could get something like that codecov diff locally? It does not look the way I expected from the tests I added, so I’d like to run a lot of small tests to figure out what’s going on, and I don’t want to spam the pull request with a dozen tiny commits just to get that diff.

**Comment by bradzacher** [comment]
yup! just run the tests and it'll output the coverage to a folder in the plugin root. There'll be some HTML files in there, drag n drop the index file onto chrome and you can view it.

**Comment by bogdanb** [comment]
OK, I got the patch coverage to 100%, mostly by simplifying the logic. I couldn’t figure out a way to generate an intersection where some of the fields have Usefulness.Sometimes.

By the way, unless I’m mistaken the rule currently accepts code like this:
```
function(v: unknown) { return `${v}`}
function<A>(v: A) { return `${v}`}
```

I think both of those should be rejected. I could insert an issue & pull request for the first one, at least. (The second one needs more care, to allow things like <A extends string>.) I wanted to finish this one first, and also get a second opinion.

By the way, I see a message that the branch is out-of-date with the base branch, which offers me a button to update the branch. Should I trust that it does the right thing? Should I merge the changes by hand? Should I ignore it?

**Comment by bradzacher** [comment]
The "Update branch" button will simply merge master into your branch.
It will do the right thing. If there are merge conflicts, it will list them all and give you a UI to resolve them.

It's safe to use it.

---

I would definitely consider raising an issue for `unknown` and untyped generics.

**Pull request merged**
