### PR TITLE
fix(eslint-plugin): update peer dep for parser

### PR DESCRIPTION
**Pull request by timdorr**
This is breaking installing the latest plugin version.

### CODE REVIEW

**Comment by timdorr** [comment]
BTW, I submitted this via VS Code Web, so I might be missing lots of important steps. Just wanted to get this PR in quickly. Feel free to discard and do your own thing! :)

**Comment by timdorr** [comment]
Thanks for the assist, @JoshuaKGoldberg!

**Comment by JoshuaKGoldberg** [comment]
Thanks for hopping on this! Probably one of the fastest community bug fixes we've ever seen. 😄

**Comment by timdorr** [comment]
Thanks! I was lucky that I caught it because I was upgrading deps *right* in-between `parser@7.0.0` and `eslint-plugin@7.0.0` being published.

**Pull request merged**
