### PR TITLE
feat(eslint-plugin): add option to no-object-literal-type-assertion rule

### PR DESCRIPTION
**Pull request by armano2**
This PR adds new option to `no-object-literal-type-assertion` to disable it when used in call or new expression.

@IlyaSemenov
fixes: #66

### CODE REVIEW

**Comment by JamesHenry** [comment]
@armano2 Conflicts now just FYI

**Comment by armano2** [comment]
i don't like name of option here: `allowInCallExpression` is not fully ok, this will allow to use type assertion in  new and call expression....

**Comment by j-f1** [comment]
`allowAsParameter`?

**Comment by scottohara** [comment]
There may be another use case here that needs consideration: return values.

Consider the following code:

```ts
// Returns either Thing or Partial<Thing>

function getNewOrExistingThing(id?: number): Thing | Partial<Thing> {

  // if an id was not passed, return a Partial<Thing> (new)
  if (isNaN(id)) return { ... } as Partial<Thing>;

  // otherwise, return a Thing (existing)
  return { ... } as Thing;
}
```

Unlike the `const x = { ... } as T` -> `const x: T = { ... }` case, there is no equivalent workaround for return values.

Would the proposed `allowAsParameter` option also allow for the return value scenario above, or should there be a `allowAsReturn` option as well?

**Comment by j-f1** [comment]
Since TypeScript uses a structural type system, the returned object will pass the type check as long as it has all the required properties of `Thing` or `Partial<Thing>`.

**Comment by JamesHenry** [comment]
@scottohara Following on from @j-f1 comment, I am not sure about your example.

- You have explicitly written the return type, so performing a type assertion as part of the return statement won't affect that
- (as j-f1 said) your return type will be satisfied by at least one property on the interface being present, so it isn't necessary to pass type checking within the function either

Let's take the example where there is no extra `Partial` involved:

https://typescript-play.js.org/#code/PQ18ZXTMAQDkDyAVOBxJSAiAoXAlgHYAuApgE4BmAhgMZlwoAWxA5nAN65y9xUB7AQC44AIyEAbMjSIBuHnzE0KoiQOmyFAX3xUArkTokCAonDZkSCMgHckFAKIAPAgGcTRNi3YAKAJSiPl5cihRW+hTm3Hx8giJwJBT6ZIracDRuTKxeOvh0Zh6JORwAvBZWNvZOrh7swWwBCriwrW3tHXAAQo4oKI4ASvjE5NT0jA2hsfFqUjLyirzKquJzWri6uAZGJmYV1nYOLu6e3iUATAFBJVNwBURFJNfscOUxsfxCokkpaQq84RIkXMJDyuHujwur32VSOtVODSaQA

I would say that the second form is what you would do - allowing the type assertion is really not desirable and so having a linting option to allow it doesn't seem to make sense to me. Please let me know if I am missing something.

In the rare case where you do need the type assertion behaviour as a return value, using an `eslint-disable` comment is probably a good thing - it shows to other readers of the code (including yourself in the future) that you acknowledge you are overriding linter feedback and helps flag it up as an unusual case.

Let me know what you think

**Comment by scottohara** [comment]
@JamesHenry - thank you for your playground example, and as usual you are 100% spot on.

The second form does indeed (at the cost of one extra `const` declaration) both avoid the need for a type assertion on the return value, **and** conveys the developer's intent far better.

**Comment by JamesHenry** [comment]
I'll cut a full release after this goes in, we've merged in quite a few fixes since v1 now

**Comment by armano2** [comment]
@JamesHenry its way easier now to test and fix issues (when we have control over all packages)

**Comment by JamesHenry** [comment]
Awesome, that was the hope :) I am very happy with how our monorepo is shaping up!

I've released https://github.com/typescript-eslint/typescript-eslint/releases/tag/v1.1.0

**Pull request merged**
