### PR TITLE
chore: share parser fixtures where applicable for unit tests

### PR DESCRIPTION
**Pull request by JamesHenry**

### CODE REVIEW

**Comment by JamesHenry** [comment]
Hmm runs fine locally, but it doesn't seem to like the relative path traversal on Travis

**Comment by JamesHenry** [comment]
Yeah was thinking along the same lines eventually, but still very confused why this doesn't already work!

I'll update it to be a package

**Comment by JamesHenry** [comment]
@armano2 It actually hasn't helped :/ I can't look into this any more today, anybody else is welcome to take a look, otherwise I will pick this up again tomorrow

**Comment by JamesHenry** [comment]
@armano2 I am working on this - did you not see my commit?

**Comment by JamesHenry** [comment]
Your commit doesn't conflict with mine, so all good - but I have a major push coming shortly 👍

**Comment by armano2** [comment]
**** sorry didn't notice it

**Comment by JamesHenry** [comment]
I've fixed the issues by getting rid of all the old shelljs stuff

**Pull request merged**
