### PR TITLE
fix(eslint-plugin): enable react/jsx-curly-brace-presence lint rule in website package

### LINKED ISSUE #5878: Repo: Enable react/jsx-curly-brace-presence lint rule in website package
### Suggestion

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md

We don't yet have this lint rule enabled in the `packages/website` directory/package. But it'd be nice to have turned on!

### PR DESCRIPTION
**Pull request by shogohida**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5878 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

### CODE REVIEW

**Comment by shogohida** [comment]
I couldn't run lint locally for some reason so I decided to make a draft pull request to see which code I need to fix after `react/jsx-curly-brace-presence` is enabled.

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, glad to see no issues were detected here! Thanks for sending this in! ✨

**Comment by shogohida** [comment]
Thanks for merging! Your support helped me a lot. I hope to contribute more so see you next time!

**Comment by bradzacher** [comment]
cc @JoshuaKGoldberg - PR naming.
-> used `fix` instead of `chore`
-> package namespace was `eslint-plugin` instead of being empty

It showed up in the release logs!

**Comment by JoshuaKGoldberg** [comment]
Oh dangit sorry! I keep messing up on this 😞

**Pull request merged**
