### PR TITLE
feat(eslint-plugin): [prefer-readonly-parameter-types] include parameter name in message

### PR DESCRIPTION
**Pull request by rhysd**
With current error message of prefer-readonly-parameter-types rule, users cannot know which parameter is complained when there are multiple parameters in the same line until they count the column number of parameters by themselves.

For example:

```
function foo(a: readonly number[], b: number[], readonly c: number[]) {
}
```

When the rule reports an error for `b` parameter, 

```
1:36  error  Parameter should be a read only type  @typescript-eslint/prefer-readonly-parameter-types
```

the user cannot know which parameter is complained until counting columns of the parameters.

By this commit, parameter name is included in the error message if it can be extracted from the node.

```
1:36  error  Parameter 'b' should be a read only type  @typescript-eslint/prefer-readonly-parameter-types
```

### CODE REVIEW

**Comment by rhysd** [comment]
Sure. Thanks for the quick check.

**Comment by rhysd** [comment]
@bradzacher I added check for `data` property of error message to existing test cases.

codecov fails because coverage is slightly down. This is because there is no test case where the `actualParam` node is not an identifier:

https://github.com/typescript-eslint/typescript-eslint/blob/579e22d292c841d011fba22ba42086c5bea78593/packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts#L90-L92

But I could not add test for the case since I don't know when the node is other than identifier.

**Comment by bradzacher** [comment]
> I don't know when the node is other than identifier.

There are the following cases for parameters:
https://github.com/typescript-eslint/typescript-eslint/blob/925403884de256463f0a2a27dad2b61ff26e3da2/packages/typescript-estree/src/ts-estree/ts-estree.ts#L428-L434

AssignmentPattern:
```ts
function foo(arg: number = 1) {}
```

RestElement
```ts
function foo(...arg: someType[]) {}
```

ArrayPattern
```ts
function foo([arg]: string[]) {}
```
ObjectPattern
```ts
function foo({arg}: {arg: string}) {}
```

**Comment by rhysd** [comment]
Thank you for the help. I will try to add some tests.

**Comment by rhysd** [comment]
@bradzacher I believe this PR can be reviewed again.

I added several test cases as https://github.com/typescript-eslint/typescript-eslint/pull/1710#issuecomment-596354993 kindly indicated. I also added implementation to extract parameter name from `RestElement` and `AssignmentPattern`. Now the error message can show a proper parameter name from `...args: T[]` and `arg: T = expr`.

**Comment by rhysd** [comment]
@bradzacher I rebased this branch onto the latest master. Please let me know if I should do anything :)

**Pull request closed without merging**
