### PR TITLE
docs(eslint-plugin): [no-throw-literal] fix typo in example

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I just accidentally opened example in the playground and noticed that there is an extra semicolon

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Ha, nice catch - thanks!

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Ah the CI is failing - could you format the file please? `yarn format --write` should do the trick. Thanks!

_(I can soon if you don't have time - I just don't want to take authorship away 🙂)_

**Comment by auvred** [comment]
Fixed it, I also removed eslint comments as they are not needed here (?)

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 thanks!

**Pull request merged**
