### PR TITLE
chore(eslint-plugin): [no-floating-promises] Make the error msg more descriptive

### PR DESCRIPTION
**Pull request by ParikshitChavan**
## WHY

The existing error msg for `no-floating-promises` could use a bit more clarity

```Promises must be handled appropriately.```

ref: https://stackoverflow.com/questions/43980188/what-could-this-be-about-tslint-error-promises-must-be-handled-appropriately?answertab=votes#tab-top

## WHAT

Make the no-floating-promises error msg more descriptive

Update the error msg to 

```Expressions of type Promise must end with a call to .catch or a call to .then with a rejection handler.```

and in case that void is ignored

```Expressions of type Promise must end with a call to .catch or a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator.```

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Btw @ParikshitChavan most PRs generally are asked to correspond to an existing issue to make make sure the change is something that would be accepted before you spend too much time working on it. This one is a definite win IMO, so just a heads up for next time. 🙂

**Comment by JoshuaKGoldberg** [comment]
Ah you're absolutely right, apologies! I should have read the error messages before assuming 😅 . Looking into the seemingly unrelated failures now...

**Comment by ParikshitChavan** [comment]
@JoshuaKGoldberg please drop a final review after I merged your suggestion so that I can merge this PR. thank you!

**Comment by ParikshitChavan** [comment]
oh I cant merge the PR myself. makes sense. Please merge whenever you can. 

Thank you.

**Comment by JoshuaKGoldberg** [comment]
I only recently started reviewing PRs so I'll defer to bradzacher on this one :)

**Comment by bradzacher** [comment]
There is a general expectation that users read the docs for the rule. In vscode there's a quick link in the IDE message (click on the message ID), or use the "actions" lightbulb to click the show documentation action.

I personally prefer short-and-sweet error messages; but I understand that some users want more verbose error message with information up-front.

So I'm happy to merge this change.

**Pull request merged**
