### PR TITLE
test(eslint-plugin): [no-unused-vars]: add valid test for declare global

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
Added a test case that I kind of expect to pass and actually fails.

I'm not actually certain that this should pass. I couldn't find documentation for `declare global {}` specifically, but it seems like it's a special name, perhaps.

**Comment by mightyiam** [comment]
Also, any variables declared inside the `global`, perhaps they should also be excluded from `no-unused-vars`? For example:

```ts
declare global {
  const __karma__: {
    info(info: unknown): void
  }
}
```

Currently, the `  const __karma__: {` line also triggers the same rule. Should it, or should everything in a `global` be ignored for this rule?

**Comment by bradzacher** [comment]
Nothing within a declared namespace should get marked as unused due to this block here:

https://github.com/typescript-eslint/typescript-eslint/blob/ec7449d133e1bbca76a7df4e4b325e9bda547fb1/packages/eslint-plugin/src/rules/no-unused-vars.ts#L222-L239

**Comment by mightyiam** [comment]
@bradzacher I have it inside a `.ts` file:

https://github.com/snabbdom/snabbdom/blob/fb0af959295f90dff6b1dd2c9f8b7cb26fec1827/src/test/benchmark/core.ts#L19-L26

**Comment by mightyiam** [comment]
Oh, I see that this discussion is already in #2519. Will comment there.

**Pull request closed without merging**
