### PR TITLE
chore: add discord and stackoverflow as links to issue template

### PR DESCRIPTION
**Pull request by bradzacher**
IDK if this is the best as it adds more noise
But people can't easily find these options right now without jumping through some hoops.

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
We'll see how this goes 😄

**Comment by JoshuaKGoldberg** [comment]
(once lint passes)

**Comment by Josh-Cena** [comment]
Another possibility: add a "community" page to the website, and only add a link to that page. The benefit is we won't be constantly updating the issue wizard.

**Comment by JoshuaKGoldberg** [comment]
> Another possibility: add a "community" page to the website, and only add a link to that page. The benefit is we won't be constantly updating the issue wizard.

Agreed! Filed #7736.

**Pull request merged**
