### PR TITLE
feat(eslint-plugin): add `no-meaningless-void-operator` rule

### PR DESCRIPTION
**Pull request by jtbandes**
Report an error on `void x` when `x` is of type `void`, `undefined`, or `never` (and automatically delete the void operator).

This rule was first implemented (by me) in https://github.com/foxglove/eslint-plugin. As it could be generally useful I'm proposing to add it to @typescript-eslint/eslint-plugin.

### CODE REVIEW

**Review by bradzacher — CHANGES_REQUESTED** [review]
The rule makes sense to me, and the code LGTM.

One change required: It's not correct or safe to autofix `void (never)` to `(never)`.
Because `typeof void (never) === undefined`, but `typeof never === never`.

This could cause TS build errors - which breaks the cardinal rule of ESLint fixers (don't break the build).

Example - imagine that the client code and server response are out-of-sync due to the client not having refreshed their browser:
```ts
function foo(arg: 'a' | 'b') {
  switch (arg) {
    case 'a':
      return 'ayyy';

    case 'b':
      return 'beee';

    default:
      return void arg;
  }
}

function getPayloadFromServer(): 'a' | 'b' {
  return 'c'; // oops - the client code is behind the server code
}
foo(getPayloadFromServer()); // returns `undefined`
```
If you remove the  `void` here it'll instead return `'c'` - which is a change in runtime behaviour.

Obviously the code above is pretty dumb and likely wouldn't exist in production, but it's valid code that we have to be weary of.

---

I'm happy for the never check to be behind an option, however the `never` fix would have to be a suggestion fixer instead of an autofixer (as it's potentially unsafe)

**Comment by jtbandes** [comment]
Added a `checkNever` option which is false by default.

**Comment by jtbandes** [comment]
Hi @bradzacher – anything else you need from me here? Thanks for your time 🙂

**Review by bradzacher — APPROVED** [review]
thanks for this!

**Pull request merged**
