### PR TITLE
docs: fix example imports of consistent-type-exports

### PR DESCRIPTION
**Pull request by frankie303**
## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Fixed example imports of `consistent-type-exports` section

### CODE REVIEW

**Comment by bradzacher** [comment]
Fixed... how?
The examples were all written around having `.js` extensions.
It's valid TS to do so - esp in ESM.

**Comment by frankie303** [comment]
@bradzacher I didn't know that it's possible to define types in js files

**Comment by auvred** [comment]
.js files cannot declare TS types (although they can use JSDoc). This is about TypeScript's module resolution: https://www.typescriptlang.org/docs/handbook/modules/theory.html

**Comment by frankie303** [comment]
thanks @auvred for the link!

**Pull request closed without merging**
