### PR TITLE
feat(eslint-plugin): add rule switch-final-break

### PR DESCRIPTION
**Pull request by eranshabi**
migrated `switch-final-break` from tslint
https://palantir.github.io/tslint/rules/switch-final-break/

### CODE REVIEW

**Comment by bradzacher** [comment]
I'm wondering if this "belongs" in the plugin.
This particular rule has nothing to do with typescript syntax specifically, and doesn't require type information.
I think that this could easily be a rule within base eslint.

**Comment by octogonz** [comment]
> I think that this could easily be a rule within base eslint.

The semantics are very close to https://github.com/eslint/eslint/issues/7697.  Looks like that issue was eventually closed because nobody volunteered to create a PR.

**Comment by platinumazure** [comment]
If you think this should be added into core ESLint, please feel free to create a new issue in ESLint and we can reevaluate. Thanks!

**Comment by eranshabi** [comment]
migrated PR to eslint: https://github.com/eslint/eslint/pull/12094

**Pull request closed without merging**
