### PR TITLE
docs(eslint-plugin): missing info how to use sections, cjson -> jsonc

### LINKED ISSUE #2555: [no-implied-eval,no-throw-literal,no-empty-function] Documentation missing information that eslint no-implied-eval should be turned off.
- [ ] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Go to:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-implied-eval.md
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-throw-literal.md
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-empty-function.md
Same rules exist for eslint:
https://eslint.org/docs/rules/no-implied-eval
https://eslint.org/docs/rules/no-throw-literal
https://eslint.org/docs/rules/no-empty-function

**Expected Result**

There should be snippet showing that eslint equivalent should be disabled when using @typescript-eslint/rule (it is done this way in all other cases) i.e.:
```
{
  // note you must disable the base rule as it can report incorrect errors
  "comma-spacing": "off",
  "@typescript-eslint/comma-spacing": ["error"]
}
```

**Actual Result**

There is no information if eslint equivalent should be turned off when using plugin.

### PR DESCRIPTION
**Pull request by radarsu**
Fixes #2555

### CODE REVIEW

**Comment by tadhgmister** [comment]
would you mind editing the initial comment to say "Fixes #2555", that way when this gets merged it will automatically close the relevant issue.  Thanks for this 👍

**Comment by radarsu** [comment]
Done.

**Comment by tadhgmister** [comment]
you can still have additional info, just prefixing the issue label with "fixes" means GitHub does linking stuff like on the original issue page doing a control+f for "inked a pull request that will close this issue" and "Linked pull requests" show the relevant places.  Also means it auto-closes the issue so you don't have to do it manually. ([or forget](https://github.com/typescript-eslint/typescript-eslint/issues/2192#issuecomment-686800862)) 😄

**Review by bradzacher — APPROVED** [review]
thanks for doing this!

**Pull request merged**
