### PR TITLE
feat(eslint-plugin): Add semi [extension]

### LINKED ISSUE #409: [semi] Doesn't seem to apply to class members
**Repro**

```JSON
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "extends": [
    "airbnb-base",
    "plugin:@typescript-eslint/recommended"
  ],
  "rules": {
    "semi": ["error", "never"],
  }
}
```

```ts
import { FreeCamera } from 'babylonjs'

export default class PanCamera extends FreeCamera {
  public invertX: boolean = false // valid
  public invertY: boolean = false; // also valid

  public pan(deltaX: number, deltaY: number): void {
    this.position.x += deltaX * (this.invertX ? -1 : 1) // valid
    this.position.y += deltaY * (this.invertY ? -1 : 1); // invalid
  }
}
```

**Expected Result**
Error for `semi` on line 5 (invertY)

**Actual Result**
Nothing

**Additional Info**
I want to disallow semicolons globally in my Typescript project, but I noticed that the rule isn't being applied to class members. It works in other places in the same file but not for that specific case.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.6.0` |
| `@typescript-eslint/parser`        | `1.6.0` |
| `TypeScript`                       | `3.4.1` |
| `ESLint`                           | `5.3.0` |
| `node`                             | `9.11.2` |
| `npm`                              | `5.6.0` |

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #409, #123, #366

### CODE REVIEW

**Comment by MayhemYDG** [comment]
Great! Looking forward to the next release, I'll finally be able to remove our dependency on the tslint plugin, which we only used for the `semicolon` rule.

**Comment by JamesHenry** [comment]
@MayhemYDG We release on every commit to master, you can check out the README for more details

**Comment by Bkucera** [comment]
I think semicolons are still not detected in interface/object type definitions:

```typescript
type foo = {
  bar:string;
  baz:number;
}; // <--- only this semicolon is caught
```

**Comment by bradzacher** [comment]
@Bkucera - feel free to raise an issue with more concrete examples and config, and we can look into it.

Old merged PR's aren't great for this kind of discussion.

**Pull request merged**
