### PR TITLE
feat(eslint-plugin): [promise-function-async] Allow any and unknown as return values

### PR DESCRIPTION
**Pull request by madbence**
refs #369 

i guess it could be improved, but it solves the most obvious issues.

### CODE REVIEW

**Comment by madbence** [comment]
@bradzacher i think the PR is ready to be merged

**Comment by sindresorhus** [comment]
> As suggested in the issue, could you please gate this behind an option which defaults to off (otherwise this is a technically breaking change).

It's weird to add an option where the default is something [nobody would want](https://github.com/typescript-eslint/typescript-eslint/issues/369#issuecomment-475215879). This is IMHO just a bug fix.

I recommend just doing breaking releases more often.

**Comment by bradzacher** [comment]
Breaking releases are a bit of a pain for users and a lot of users miss them because they don't get matched by the default version range `^`, and users don't often run something like `yarn outdated`. Even then a lot of users shy away from major bumps because it involves reading documentation.

the fewer breaking changes released, the easier it is to keep the userbase coherent.

In essence I see no reason to major bump unless it's unavoidable, or it's a really bad for a majority of users.
As this is a relatively new rule which also requires type info, I don't think a large portion of the users use it yet (though I don't have stats on that assumption).

**Comment by sindresorhus** [comment]
Any chance this could be merged?

**Pull request merged**
