### PR TITLE
feat(eslint-plugin): `prefer-consistent-enums` rule

### PR DESCRIPTION
**Pull request by brianconnoly**
Added new rule — `prefer-consistent-enums`

Enum members can have members of different types
Enums with string initializers can be used as object to iterate over them using `Object.keys` / `Object.values`

```ts
enum Status {
  Open = 'open',
  Closed = 'closed',
}

Object.values(Status); // ['open','closed']
```

But if member with number initializer will be added (or without one) — results of `Object.keys` / `Object.values` will have additional auto generated items

```ts
enum Status {
  Pending,
  Open = 'open',
  Closed = 'closed',
}

Object.values(Status); //  ["Pending", 0, "open", "closed"]
```

```ts
enum Status {
  Pending = 123,
  Open = 'open',
  Closed = 'closed',
}

Object.values(Status); //  ["123", "Pending", "open", "closed"]
```

This can lead to bugs, so this rule can prevent them by requiring enums to have consistent member types

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
LGTM in general, thanks for sending! Requesting changes on the error message and auto-fixer.

**Comment by osdiab** [comment]
Should this be merged?

**Comment by JoshuaKGoldberg** [comment]
@osdiab I'd requested changes that haven't yet been addressed. @brianconnoly do you still have the time to work on this?

**Comment by bradzacher** [comment]
At this point the PR is now 6 months stale. Closing for housekeeping.
This is not a rejection - anyone is free to re-raise the PR to continue this work!

**Pull request closed without merging**
