### PR TITLE
docs(eslint-plugin): fix typo in example codeFix typo in example code

### PR DESCRIPTION
**Pull request by nullromo**
## PR Checklist
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken
## Overview
Just a minor typo fix to avoid confusion in terms of what the rule is doing.

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
😄

**Review by armano2 — APPROVED** [review]

**Review by JoshuaKGoldberg — APPROVED** [review]
Ha, nice spot. Thanks!

**Comment by JoshuaKGoldberg** [comment]
Well, I'm stumped.

@nullromo would it be possible for you to rebase your branch off the latest typescript-eslint `main` and force push?

**Comment by armano2** [comment]
> Well, I'm stumped.
> 
> @nullromo would it be possible for you to rebase your branch off the latest typescript-eslint `main` and force push?

this errors occurs at random, james was investigating it

**Pull request merged**
