### PR TITLE
ci: generate contributors automatically monthly

### PR DESCRIPTION
**Pull request by JounQin**
related to https://github.com/typescript-eslint/typescript-eslint/pull/3064#pullrequestreview-591578479

### CODE REVIEW

**Comment by JounQin** [comment]
cc @JamesHenry Any news?

**Review by JamesHenry — APPROVED** [review]
Great, thanks @JounQin!

**Comment by JounQin** [comment]
https://github.com/typescript-eslint/typescript-eslint/runs/2480548262?check_suite_focus=true#step:9:9

@JamesHenry It seems broken due to protected branch, should it be allowlisted or create a PR automatically instead?

**Comment by JamesHenry** [comment]
Thanks @JounQin I'll make some updates to it

**Comment by JamesHenry** [comment]
I have managed to use the `create-pull-request` action to work around the protected branch point. As part of that I had to switch the token used to the existing PAT because the built in token by design does not trigger any subsequent checks: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs

Here is an example of the output of the action: https://github.com/typescript-eslint/typescript-eslint/pull/3343

**Pull request merged**
