### PR TITLE
fix(eslint-plugin): remove imports from typescript-estree

### LINKED ISSUE #705: eslint-plugin should not import from typescript-estree
**Repro**
`@typescript-eslint/eslint-plugin` should not import from `@typescript-eslint/typescript-estree`, since it does not have a direct dependency on this package.  Instead, it should only import from `@typescript-eslint/experimental-utils`.

This issue is hidden when using a package manager which flattens dependencies like `npm`, since `@typescript-eslint/parser` does have a dependency on `@typescript-eslint/typescript-estree`, and `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` are typically used together.

However, when using a package manager like `pnpm` which [does not flatten dependencies](https://pnpm.js.org/docs/en/faq.html#pnpm-does-not-work-with-your-project-here), `@typescript-eslint/eslint-plugin` fails with the following error:

```
Error: Cannot find module '@typescript-eslint/typescript-estree'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Git\typescript-eslint-test\node_modules\.registry.npmjs.org\@typescript-eslint\eslint-plugin\1.12.0_db854cf46887ef4aa7b9323cccc417a5\node_modules\@typescript-eslint\eslint-plugin\dist\rules\prefer-readonly.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Repro steps:

```
git clone https://github.com/mikeharder/typescript-eslint-test

npm install
npm run lint (works fine)

git clean -xdf
npm install -g pnpm
pnpm install
npm run lint (fails)
```

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.12.0` |
| `@typescript-eslint/parser`        | `1.12.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `10.16.0` |
| `npm`                              | `6.9.0` |
| `pnpm`                              | `3.5.7` |

### PR DESCRIPTION
**Pull request by mikeharder**
- Fixes #705

### CODE REVIEW

**Comment by mikeharder** [comment]
@bradzacher: Are you suggesting the following change at this location?

https://github.com/typescript-eslint/typescript-eslint/blob/76b89a50489217ced0250a046969b557cc2e6a6a/packages/eslint-plugin/src/rules/prefer-readonly.ts#L5

```
- import { TSESTree, AST_NODE_TYPES } from '@typescript-eslint/typescript-estree';
+ import { TSESTree, AST_NODE_TYPES } from '@typescript-eslint/experimental-utils'; 
```

If so, should this rule be changed in the same way?

https://github.com/typescript-eslint/typescript-eslint/blob/4edf0d71ef0a8a3370165e804dd693033d6207bc/packages/eslint-plugin/src/rules/prefer-regexp-exec.ts#L1

Finally, what about this rule?

https://github.com/typescript-eslint/typescript-eslint/blob/af70a5932f8032cde13f4a0c98d6657cdb40b441/packages/eslint-plugin/src/rules/triple-slash-reference.ts#L2-L7

**Comment by bradzacher** [comment]
yes, that's what I mean!

`experimental-utils` was setup to be the one-stop-shop for plugins written in typescript - it depends on `typescript-estree` and re-exports the relevant pieces, so that should be the only one ever used by the plugin.

Unfortunately VSCode's auto importer likes to suggest packages that aren't direct dependencies, and it's hard to catch that error in reviews. There are some lint fixes in the pipeline to catch this in future.

It looks like you already have done it, but could you please make sure that there are no results for this grep `from '@typescript-eslint/typescript-estree` in the `eslint-plugin`?

**Comment by mikeharder** [comment]
@bradzacher: The 3 rules I linked above are the only I found with `from '@typescript-eslint/typescript-estree`.  The first two should be easy to fix by replacing `typescript-estree` with `experimental-utils`, but `triple-slash-reference.ts` looks more difficult since it's importing types which don't appear to be exported from `experimental-utils`.

**Comment by bradzacher** [comment]
Having a look, all 3 should be from the `TSESTree` export in `experimental-utils`

```ts
 import { 
   Literal,                    // TSEStree.Literal
   Node,                       // TSESTree.Node
   TSExternalModuleReference,  // TSEStree.TSExternalModuleReference
 } from '@typescript-eslint/typescript-estree/dist/ts-estree/ts-estree'; 
```

**Comment by mikeharder** [comment]
I think I know the changes required then, will update this PR.

**Comment by mikeharder** [comment]
@bradzacher: I believe I have updated this PR with the changes you requested.

**Pull request merged**
