### PR TITLE
feat(typescript-eslint): allow infinitely deep array nesting in config function and extends

### PR DESCRIPTION
**Pull request by bradzacher**
## PR Checklist

- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This has been a pet peeve of mine for a long while now and I've been meaning to action it as a big DevX improvement.

This PR simply allows users to infinitely nest arrays in the `tseslint.config` utility input AND in the `extends` key.

The docs updates are proof enough of how much this simplifies things.

Note that [ESLint upstream is planning on allowing nested arrays](https://github.com/eslint/rfcs/pull/126) which is what spurred me to build it right now.

### CODE REVIEW

**Comment by kirkwaiblinger** [comment]
Oh, _hell_ yes ❤️

**Comment by Josh-Cena** [comment]
You would need to add this to the config reference docs otherwise LGTM 👍

**Review by JoshuaKGoldberg — DISMISSED** [review]
Hell yeah!!

**Comment by bradzacher** [comment]
> You would need to add this to the config reference docs otherwise LGTM

@Josh-Cena what docs are you referring to, sorry?
I searched for all spreads and cleaned them up.

I didn't explicitly mention this behaviour in the docs - but we could do if we wanted.

**Comment by bradzacher** [comment]
I'm going to merge this as is -- we can always follow-up to add more docs later.

**Pull request merged**
