### PR TITLE
test: one snapshot per fixture test

### PR DESCRIPTION
**Pull request by armano2**
This is alternative approach to ticket #1142 and change proposed in #1152

Main difference is that this code does not require generation of additional files (test per file) but extends jest functionality by allowing us to provide path to generated snapshot

Changes:
In test files i added one property (path): https://github.com/typescript-eslint/typescript-eslint/pull/1491/files#diff-8b3fe597033edf9c839ecff70500df9e

In test utils from ts-estree i added small piece of code to split snapshots:
https://github.com/typescript-eslint/typescript-eslint/pull/1491/commits/e4722e847e2719c4e13ffb036f154f62dc0692f7#diff-c976a68babc2637f35c7d6074d995843R41-R47

### CODE REVIEW

**Comment by bradzacher** [comment]
what's the runtime like?
The biggest problem with #1152 is the perf hit:

- parser:
  - base: ~12s
  - #1152: ~120s
- typescript-estree:
  - base: ~40s
  - #1152: ~120s

**Comment by armano2** [comment]
for some reason its not started here, but on my local env difference is +-10sec

**Comment by armano2** [comment]
CI is complaining about path that i used `./snapshot/**/*`

**Comment by bradzacher** [comment]
Surprising that it's so much faster. It must be because it circumvents the checks to clean up the snapshot afterward.

**Comment by armano2** [comment]
i played yesterday a little with this plugin and it seems that i can make it work with jest update (but i will have to do small modification to this plugin)

**Pull request closed without merging**
