### PR TITLE
fix(eslint-plugin): [ban-types] add option extendDefaults

### LINKED ISSUE #686: [ban-types] Default options are never removed
**Repro**

```js
module.exports = {
    parser: '@typescript-eslint/parser',
    plugins: ['@typescript-eslint'],
    rules: {
        '@typescript-eslint/ban-types': [
            'error',
            {
                types: {
                    Omit: 'Prefer `OmitStrict`.',
                },
            },
        ],
    },
};
```

```TS
// Don't use 'Object' as a type. Use Record<string, any> instead
type Foo1 = Object;
// Don't use 'Boolean' as a type. Use boolean instead
type Foo2 = Boolean;
// Don't use 'Number' as a type. Use number instead
type Foo3 = Number;
```

**Expected Result**
No errors, because I am overriding the [default options](https://github.com/typescript-eslint/typescript-eslint/blob/e325b728098f73b98ada8ec05ea0175403c80d1f/packages/eslint-plugin/src/rules/ban-types.ts#L83).

**Actual Result**
Each line errors. It is not possible to disable the default options.

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.11.0` |
| `@typescript-eslint/parser`        | `1.11.0` |
| `TypeScript`                       | `3.5.2` |
| `ESLint`                           | `6.0.1` |
| `node`                             | `8.15.1` |
| `npm`                              | `6.9.0` |

### PR DESCRIPTION
**Pull request by threehams**
Special-case `ban-types` rule to replace default options instead of merging if `extendDefaults` is set to `false`.

Fixes #686.

### CODE REVIEW

**Comment by threehams** [comment]
We might just be dancing around the issue of the `Object` message and fixer here. The primitive constructor type messages and fixers are a good default any project. `Object`, though, doesn't really have one universal way to fix it. Usage of it could be from someone really looking for behavior like `object`, or could be from someone not wanting to figure out the real structure of an object and just throwing in something that's effectively `any`. I've seen both usages in a Flow project.

The [official recommendation](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types) is to use `object` which I'd agree with, but is probably the wrong fix in most cases. `Record` is a pretty unsound "just trust me" type even without the `any` mixed in, so we're just auto-fixing "any" to "almost any" there.

If the message were more generic and it didn't auto-fix, then this seems like a good use for the [suggestions API](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions), though it would require ESLint 6.7.

**Comment by glen-84** [comment]
This is related to #848, where the fixer for `Object` is removed (but `Record<string, unknown>` is still "suggested").

**Comment by threehams** [comment]
In that case, I'll add extendDefaults here since it'll be taken care of in that PR.

This change could take a little longer, it's not as clear how to do it without adding more one-off code in here. Maybe necessary though.

**Comment by bradzacher** [comment]
I think this is definitely a one-off use case. This rule is an edge case.

Thinking about it, if you add `extendDefaults` with a default value of `true`, then this is no longer a breaking change - as it wouldn't meaningfully change it from the way it works currently.

**Comment by HolgerJeromin** [comment]
> Thinking about it, if you add extendDefaults with a default value of true, then this is no longer a breaking change - as it wouldn't meaningfully change it from the way it works currently.

I think this would be the best option.
Friendly ping to @threehams :)

**Comment by threehams** [comment]
Updated code, tests, docs. Edited description as this is no longer a breaking change.

**Pull request merged**
