### PR TITLE
chore: bump eslint-plugin-jest for eslint v8 support

### PR DESCRIPTION
**Pull request by SimenB**

### CODE REVIEW

**Comment by bradzacher** [comment]
There is also a local patch which hacked support that you can delete with this!

https://github.com/typescript-eslint/typescript-eslint/blob/v5/patches/eslint-plugin-jest+24.4.0.patch

**Comment by SimenB** [comment]
> There is also a local patch which hacked support that you can delete with this!
> 
> [https://github.com/typescript-eslint/typescript-eslint/blob/v5/patches/eslint-plugin-jest+24.4.0.patch](https://github.com/typescript-eslint/typescript-eslint/blob/v5/patches/eslint-plugin-jest+24.4.0.patch?rgh-link-date=2021-09-17T07%3A13%3A26Z)

I believe I already do so? 😅 

image

**Comment by bradzacher** [comment]
Sorry! I'm on mobile and I completely missed that.. it blended into the header

**Review by bradzacher — APPROVED** [review]
thanks!

**Pull request merged**
