### PR TITLE
feat(eslint-plugin): add extension rule `comma-dangle`

### LINKED ISSUE #710: [comma-dangle] does not check enum declarations
**Repro**

```JSON
{
  "rules": {
    "comma-dangle": ["error", "always-multiline"]
  }
}
```

```TS
enum MyEnum {
    MY_VALUE,
    MY_OTHER_VALUE
}
```

**Expected Result**

Some kind of error on line three of the test file, since there is no trailing comma after the final enum member.

**Actual Result**

No error is reported.

**Additional Info**

Ideally, this would happen with no extra config, where typescript-eslint would somehow “plug into” eslint’s [comma-dangle](https://eslint.org/docs/rules/comma-dangle) rule. That said, its [current implementation](https://github.com/eslint/eslint/blob/93633c2b3716b17816bcb3dc221c49b75db41317/lib/rules/comma-dangle.js) doesn’t look like it invites this; for example, it [immediately throws away option members other than `arrays`/`objects`/`imports`/`exports`/`functions`](https://github.com/eslint/eslint/blob/93633c2b3716b17816bcb3dc221c49b75db41317/lib/rules/comma-dangle.js#L42-L71), so it’s not clear how typescript-eslint could have separate options for `enums` here. A separate, TypeScript-specific rule seems more likely (I’m not sure if there are any other syntax constructs besides enums that support dangling commas). In that case, of course, the separate rule would need to be mentioned in the repro to make it work – but I couldn’t find any existing rule that would provide this.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.12.0` |
| `@typescript-eslint/parser`        | `1.12.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.0.1` |
| `node`                             | `12.6.0` |
| `npm`                              | `6.9.0` |

### PR DESCRIPTION
**Pull request by yeonjuan**
fixes #710

### CODE REVIEW

**Comment by yeonjuan** [comment]
@bradzacher Oh. it's my bad. Thanks :)

**Comment by ashlinchak** [comment]
@bradzacher Is it possible to merge this PR to the master?

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md#addressing-feedback-and-beyond

When I've got time to review larger feature PRs, I'll get to it.
I've been swamped the last few weeks with the v4 release and the fixes that were required for it.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for your contribution!

**Pull request merged**
