### PR TITLE
feat(eslint-plugin): [no-type-alias] support tuples

### LINKED ISSUE #720: [no-type-alias] unhandled type - shouldn't happen
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-type-alias": ["error", { "allowAliases": "in-unions" }]
  }
}
```

```TS
// Actually, I'm using this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7172b31badc3df45f4386400606dbe24437e3d5a/types/gl-matrix/index.d.ts#L49, but this is enough to trigger the error
class Vec2 extends Float32Array {
    public constructor() {
        super(2);
    }
}

type Vec2orArray = Vec2 | [number, number];
```

**Expected Result**

No linter error since unions are explicitly allowed.

**Actual Result**

Error: `Unhandled in union types are not allowed.eslint(@typescript-eslint/no-type-alias)`

**Additional Info**

Apparently, this hits a case not handled in the rule implementation, see https://github.com/typescript-eslint/typescript-eslint/blob/6be0d811fd7d28fe96a8632da4cd4e81cb517617/packages/eslint-plugin/src/rules/no-type-alias.ts#L243

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `1.12.0` |
| `@typescript-eslint/parser`        | `1.12.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `5.16.0` |
| `node`                             | `12.6.0` |
| `npm`                              | `6.9.0` |

### PR DESCRIPTION
**Pull request by ankeetmaini**
Fixes #720

### CODE REVIEW

**Comment by ankeetmaini** [comment]
Thanks @bradzacher, updated the PR :)

**Comment by ckknight** [comment]
Can we also have a test for `readonly` tuples?

**Comment by ankeetmaini** [comment]
```ts
if (type.node.type === AST_NODE_TYPES.TSTypeOperator) {
  if (
    (['keyof', 'readonly'].includes(type.node.operator) &&
    type.node.typeAnnotation &&
    type.node.typeAnnotation.type === 'TSTupleType'
  ) {
    return true;
  }
}

```

> type.node.typeAnnotation.type === 'TSTupleType'

TS is throwing on this line `This condition will always return 'false' since the types 'AST_NODE_TYPES.TSTypeAnnotation' and '"TSTupleType"' have no overlap.ts(2367)`

How else can I ascertain that `TSTypeOperator`'s contains a tuple type? I checked the AST too, it seems valid https://astexplorer.net/#/gist/149c54ba8d9a45dace62a4aac639f613/79446ea665c469c0e03fe7a74fdeb35ac7bbcde5

**Comment by bradzacher** [comment]
try `AST_NODE_TYPES.TSTupleType`

**Comment by ankeetmaini** [comment]
It fails with that too. :(

**Comment by bradzacher** [comment]
it probably needs to be added to the base types then.
I doubt it was added in all the correct places when tuples were released.

I.e. to this union
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/ts-estree/ts-estree.ts#L399-L435

**Comment by bradzacher** [comment]
The types were wrong for `TSTypeOperator`. I fixed them for you on this branch.

**Comment by ankeetmaini** [comment]
@bradzacher thanks, I've updated the tests and rebased with master.

**Pull request merged**
