### PR TITLE
feat(eslint-plugin): [no-unsafe-argument] add rule

### LINKED ISSUE #791: New set of rules: `no-unsafe-*`
These rules are all implemented - one final case remains to be implemented: `no-unsafe-argument` to catch when you're passing `any` into an argument. (See https://github.com/typescript-eslint/typescript-eslint/issues/791#issuecomment-593836301)

-----

Create a rule which uses type information to determine when you're inadvertently breaking type safety by using an any, potentially without knowing.

Often libraries (or even the typescript defs themselves) can have weak(/lazy) types which return `any`. If you're not careful, you can inadvertently introduce `any`s within your codebase, leading to bugs that aren't caught by the compiler.

Examples:
```ts
const foo = Object.create(null);
//    ^^^ error: variable declaration implicitly typed as any
const bar = x.prop;
//    ^^^ error: variable declaration implicitly typed as any
const baz = (1 as any);
//    ^^^ error: variable declaration implicitly typed as any
const buzz = [];
//    ^^^^ error: variable declaration implicitly typed as any[]

let bam: any = 1; // no error, as it's **explicitly** any

   function foo(arg: string) {
// ^^^^^^^^^^^^^^^^^^^^^^^^^ error: function return type is implicitly any
     if (someCondition) {
       return 'str';
     }

     return bam;
//   ^^^^^^^^^^^  error: return statement implicitly returns any
   }

foo(x.prop);
//  ^^^^^^ error: passed function argument implicitly typed as any

for (const fizz of bar) {}
//   ^^^^^^^^^^ error: variable declaration implicitly typed as any
for (let i = foo; i < 10; i += 1) {}
//       ^ error: variable declaration implicitly typed as any

// variable decls, returns, arguments, assignment expressions, ifs... 
```

Should also check assignments:
```ts
    bam = foo;
//  ^^^^^^^^^^ error: assignment expression implicitly uses as any
const clazz = new Clazz();
      clazz.foo = foo;
//    ^^^^^^^^^^^^^^^^ error: assignment expression implicitly uses as any
    foo += foo;
//  ^^^^^^^^^^^ error: assignment expression implicitly uses any
    foo++;
//  ^^^^^^ error: update expression implicitly uses any
```

Maybe also check things boolean things like if/while/etc?
```ts
if (foo) {}
//  ^^^ error: if condition implicitly typed as any
while (foo) {}
//     ^^^ error: while condition implicitly typed as any
do { } while (foo)
//            ^^^ error: do...while condition implicitly typed as any
switch (foo) {
//      ^^^ error: switch discriminate implicitly typed as any
    case bar:
//       ^^^ error: case test implicitly typed as any
      break;
}
```

Should also provide an option to go strict with property access to help with finding the source of an any via property access):
```ts
type Obj = {
  foo: {
    [k: string]: any;
    bar: {
      baz: string;
    };
  };
};

declare const x: Obj;

const y = x.foo.bam.baz;
//        ^^^^^^^^^ error: property access implicitly returns any
//    ^ error: variable declaration implicitly typed as any

const z: string = x.foo.bam.baz;
//                ^^^^^^^^^ error: property access implicitly returns any

const { baz } = x.foo.bam;
//              ^^^^^^^^^ error: property access implicitly returns any
//      ^^^ error: destructured variable implicitly typed as any
```

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #791

This adds a new rule which just checks the passing of arguments.
This case is a lot more complex than most cases due to spread arguments.

### CODE REVIEW

**Comment by G-Rath** [comment]
@bradzacher do you think this could be another one worth extending in `eslint-plugin-jest`, to have it ignore the `any` of `expect` async matchers?

i.e

```
expect(mockMessageReactor.prototype.react).toHaveBeenCalledWith(
  message,
  expect.arrayContaining<ReactionAction>([
    ['heavy_multiplication_x', true]
  ])
);
```

I know I can satisfy this by casting to `unknown` (or stronger), but in this context such a cast is typically very meaningless.

In saying that, I am casting for properties:

```
expect(mockSlackReactionsApi.remove).toHaveBeenCalledWith({
  name: expect.any(String) as string,
  timestamp: '1',
  channel: '#my-channel'
});
```
------

Curious on if you have any opinions on if this is something extending :)

**Comment by bradzacher** [comment]
this rule checks arguments using out `isUnsafeAssignment` function.

https://github.com/typescript-eslint/typescript-eslint/blob/cb2256168c67e0383083673a5afe77076de49da5/packages/eslint-plugin/src/util/types.ts#L418-L471

Which will allow assignments of `any` to either `any` or `unknown`.
So as long as the jest expect functions are typed as receiving `any` or `unknown`, then it should just work.

**Comment by bradzacher** [comment]
But it looks like there is a bug in the rule.

The jest function is typed as:
```ts
declare function toHaveBeenCalledWith<E extends any[]>(...params: E): void;
```

So at typecheck type, when called with `toHaveBeenCalledWith(1 as any)`, the type of `params` isn't `any[]`, it's `[any]`.. which isn't handled right now

**Comment by G-Rath** [comment]
> So as long as the jest expect functions are typed as receiving any or unknown, then it should just work.

which (if I remember and understand everything correctly) they're not - they're typed to receive `any[]` (where appropriate).

So:

```
expect(captureExceptionSpy).toHaveBeenCalledWith(expect.any(Error));
```

Gets

> ESLint: Unsafe argument of type `any` assigned to a parameter of type `[any]`.(@typescript-eslint/no-unsafe-argument)

(that could be what you mean by `[any]` not being handled right now).

**Comment by fabb** [comment]
shouldn't the new rule be added to the `recommended-requiring-type-checking` preset?

**Comment by bradzacher** [comment]
Changes to the recommended sets is a breaking change.

**Pull request merged**
