### PR TITLE
fix(typescript-estree): change `source` of ExportNamedDeclaration to Literal from Expression

### PR DESCRIPTION
**Pull request by sosukesuzuki**
`source` of `ExportNamedDeclaration` is `Literal` in [estree](https://github.com/estree/estree/blob/master/es2015.md#exportnameddeclaration).

If this is your intention, close this.

### CODE REVIEW

**Comment by bradzacher** [comment]
This is actually currently done on purpose.
The TS parser is incredibly forgiving - and so it gives us a bad AST.
We don't currently enforce the AST matches the ESTree structure - so in this case `import foo from bar` is valid code in our parser (as is `export { foo } from 1 + 1`.

We have two options:
1) wait until we've done #1852 and thus have parser errors for bad code
2) add validation in this diff to enforce that it is a string literal.

I'm happy with either - depends on if you've got time to do the extra work for (2).

**Comment by sosukesuzuki** [comment]
@bradzacher  Thanks you for telling me. 

> I'm happy with either - depends on if you've got time to do the extra work for (2).

I can work for implement option (2).

However, one question. Why `source` of `ImportDeclaration` is `Literal`? We can specify any expression to `source` of `ImportDeclaration` same as `ExportNamedDeclaration`.

**Comment by sosukesuzuki** [comment]
I've pushed commits to add assertion for module specifiers, but I'm not sure it is correct way.

**Review by bradzacher — APPROVED** [review]
LGTM - thanks for this!

**Pull request merged**
