### PR TITLE
test(ast-spec): snapshot codeframe of error

### PR DESCRIPTION
**Pull request by fisker**
## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

During upgrade parser to v6 in Prettier, I found some error location should be improved, but before that, let's make the error visible?

### CODE REVIEW

**Review by bradzacher — COMMENTED** [review]
this is a great idea!
I wonder if we should be capturing an end as well as part of the `TSError`?

That way we could throw errors on ranges instead of just on single characters.
Looks like code-frame also supports an end range, so we would even be able to snapshot it.

WDYT?

**Comment by fisker** [comment]
> I wonder if we should be capturing an end as well as part of the TSError?

Prettier throws errors include a start and an end, see [this diff](https://github.com/prettier/prettier/actions/runs/4301173716/jobs/7498092190#step:5:33).
I hope to merge this one first, and change the errors to add more information later.

**Comment by fisker** [comment]
@bradzacher Don't know how to fix [this](https://github.com/typescript-eslint/typescript-eslint/actions/runs/4310317455/jobs/7518637062#step:4:38), can you help?

**Review by bradzacher — APPROVED** [review]

**Comment by bradzacher** [comment]
oops - i didn't see the error before merging 🤦

**Comment by bradzacher** [comment]
Should be fixed by f98afd2eaddab2a74f22f737d89aa89147c7fc9b

**Pull request merged**
