### PR TITLE
fix(typescript-estree): fix identifier tokens typed as `Keyword`

### PR DESCRIPTION
**Pull request by lydell**
As in #681 and #750, the `of` keyword wasn't correctly handled in the parser with respect to variable names, so the token it created was typed as Keyword instead of Identifier.

Fixes https://github.com/lydell/eslint-plugin-simple-import-sort/issues/33

### CODE REVIEW

**Comment by armano2** [comment]
@bradzacher list of keyword is a little big 
```
        FirstKeyword = 76,
        LastKeyword = 151,
```

Keyword that are allowed as identifiers
- `FromKeyword`
- `NamespaceKeyword`

**Comment by armano2** [comment]
typescript actually exposes us more values that we could use for this:

```ts
        FirstReservedWord = 76,
        LastReservedWord = 111,
        FirstKeyword = 76,
        LastKeyword = 151,
        FirstFutureReservedWord = 112,
        LastFutureReservedWord = 120,
```

**Comment by lydell** [comment]
@armano2 Feel free to push something to this branch if you want to. I’m not sure what your code snippets mean yet.

**Comment by armano2** [comment]
in SyntaxKind there are special values that represents boundries of types that can be used to do range check, for example i think in this case we should do something like this instead (not sure tho)

```ts
  if ('originalKeywordKind' in token && token.originalKeywordKind) {
    if (token.originalKeywordKind === SyntaxKind.NullKeyword) {
      return AST_TOKEN_TYPES.Null;
    } else if (
      token.originalKeywordKind > SyntaxKind.LastFutureReservedWord &&
      token.originalKeywordKind <= SyntaxKind.LastKeyword
    ) {
      return AST_TOKEN_TYPES.Identifier;
    }
    return AST_TOKEN_TYPES.Keyword;
  }
```

**Comment by bradzacher** [comment]
This is the list of keywords which typescript allows as identifiers without throwing an error:
```
        // Strict mode reserved words
        implements,
        interface,
        let,
        package,
        private,
        protected,
        public,
        static,
        yield,
        // Contextual keywords
        abstract,
        as,
        asserts,
        any,
        async,
        await,
        boolean,
        constructor,
        declare,
        get,
        infer,
        is,
        keyof,
        module,
        namespace,
        never,
        readonly,
        require,
        number,
        object,
        set,
        string,
        symbol,
        type,
        undefined,
        unique,
        unknown,
        from,
        global,
        bigint,
        of,
```
[repl](https://www.typescriptlang.org/play/?allowUnreachableCode=true&allowUnusedLabels=true#code/JYWwDg9gTgLgBAbwFB1W1B6DcBKBTAZzygDc8ATOAd2nIJXTQCMo8BDAawBoHG4BjNkR59UgmPwAWI0fwA2QgjL78IAOwIxljVWpjA1AVzzb05PE0MBzK8VNpzAMzaG5W3o3Ny8MEx7MQ9qh4csL+aHhGIEFweAAekLAx8b5qdDHOoX6icI4GbHJyAJ4Z0BmGavz66jHAjrXg0O45BrUaMGyVeBD14ahqeFQxRoUxrDCGUGoxBIZgdn1wBFTAEtKLMJLAShuSUBBDG1DGMTBQJRtF8z0xJGxQtxDA5DFUW96vq+s5WHAAymdgFU4CAIOY4KwiKQKNRaPQWuBvCBIjAdi09MRnPxsqJvM1RGA2PwOGxbDEwFBgHdfOT9r4qhRyYYmHIgTMOvp+DEisAQi9Fr8AMLqXxxCYFOAcPBFGhQOiLNhMTRQIn4vhCGKKYiozVqC45IRFSqaqhsVYxJgQCDeToxXTKwxVMqLczye44vi2NWMAyOBYtNGiKVFG6LUHkVwexhqNjIgiE7HDPBkB6LVhscjqYpjPAAR0MwFYw0MICY-tEECYACs8FUZj52ZS1FYZkVS9bTlco+gKk4DIzFhVgPnu2gKhw1AdpotHPtoosrHJKwULcArAZvehQwBfXJzuAAcgPAG4kEA)

Which suggests the range you'd want to check instead is `SyntaxKind.FirstFutureReservedWord` to `SyntaxKind.LastKeyword`

**Comment by armano2** [comment]
```ts
LastReservedWord = 111, // Reserved words
LastFutureReservedWord = 120 // Strict mode reserved words
```

**Comment by armano2** [comment]
i did some digging and it looks like it should be something more like this:

```ts
  // Need two checks for keywords since some are also identifiers
  if ('originalKeywordKind' in token && token.originalKeywordKind) {
    if (token.originalKeywordKind === SyntaxKind.NullKeyword) {
      return AST_TOKEN_TYPES.Null;
    } else if (
      token.originalKeywordKind >= SyntaxKind.FirstKeyword &&
      token.originalKeywordKind <= SyntaxKind.LastFutureReservedWord
    ) {
      return AST_TOKEN_TYPES.Keyword;
    }
  }
```

we actually do not want to return identifier here as in JSX context it should be JSXIdentifier,

**Comment by bradzacher** [comment]
> we actually do not want to return identifier here as in JSX context it should be JSXIdentifier,

I think you're mixing up the two?
This not for the AST nodes - this is for the AST tokens.

The AST node should come out as an `Identifier` or `JSXIdentifier`, which happens correctly right now.
This logic is handled by the core converter code.

The AST token should always come out as an `Identifier`, which it does not right now - the keywords come out as a `Keyword` token.
This logic is handled separately from the core converter code, and the change here is fixing just that logic.

For example,
https://astexplorer.net/#/gist/6d1195acc2d3398734dc8cef95ecf464/8b5616f2530c5a348beb98a33b54e1a9b2c2760b

Click on the `of` in both cases, and note that the AST node is `JSXIdentifier`, and Identifier respectively, but in both cases the AST token is incorrectly `Keyword`

**Comment by lydell** [comment]
Pushed an update. Hopefully I got it right. Let me know what you think.

**Comment by bradzacher** [comment]
The code you've got LGTM.

----

Now that you've got me thinking about this:
```ts
const foo = { get bar() { return 1 } };
//            ^^^ should this be an Identifier token or a Keyword token?
```

Both `babel-eslint` and `espree` both label the above `get` as an `Identifier` token, but shouldn't it be a keyword? Super strange - I'm okay with us going with the consensus there.

**Comment by bradzacher** [comment]
I've raised https://github.com/eslint/espree/issues/428 and I'll chat with the eslint team there, and we can follow up to correct the logic in a later PR if needs be.
Otherwise - this LGTM.

**Pull request merged**
