### PR TITLE
chore(type-utils)!: remove IsNullableTypeOptions interface

### LINKED ISSUE #8931: Enhancement: Remove IsNullableTypeOptions from type-utils
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Following #8089: we noticed that the `IsNullableTypeOptions` interface is never actually used in the places it's taken in, such as the `isNullableType` function later in the file:

https://github.com/typescript-eslint/typescript-eslint/blob/85ae4a8977149583b0c501e092a927b1435e68d2/packages/type-utils/src/predicates.ts#L9-L18

We wanted to delete the unused interface, but doing so would be a breaking change. Now that we're working on v8 it's time - let's delete the code! 🔪 

### Additional Info

Note that the PR for this should be targeted against the `v8` branch.

💖

### PR DESCRIPTION
**Pull request by thuchede**
## PR Checklist

- [x] Addresses an existing open issue: fixes #8931
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Remove @deprecated `IsNullableTypeOptions` interface and its usage in `isNullableType`

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Great thanks! 🚀

**Comment by JoshuaKGoldberg** [comment]
Whoops, I forgot to add `BREAKING CHANGE:` to the start of this PR's description. Noting to self that we'll need to manually edit this into the changelog.

**Comment by bradzacher** [comment]
@JoshuaKGoldberg you also left the `!` in the title which might break the semantic generator!

**Comment by JoshuaKGoldberg** [comment]
😬.

**Comment by bradzacher** [comment]
We probably need to see if we can configure the PR title action to ban the `! `

**Comment by JoshuaKGoldberg** [comment]
#9027

**Comment by JoshuaKGoldberg** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/9789, too 📝

**Pull request merged**
