### PR TITLE
feat: TypeScript 4.6

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## PR Checklist

Sorry I have not created an issue for this.

-   [x] Addresses an existing issue: fixes https://github.com/typescript-eslint/typescript-eslint/issues/4471
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

[TypeScript 4.6 has been released:tada:](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/)

This PR updates `typescript` to 4.6.

Also, fixes some tests for `typescript-estree` to match the fixes on the TypeScript side.

### CODE REVIEW

**Review by bradzacher — CHANGES_REQUESTED** [review]
Thanks for this! Could you also please run `yarn generate:lib` within `typescript-estree`?

https://github.com/typescript-eslint/typescript-eslint/blob/3ea09477debec9f1593e4d3857e153570b488f4d/packages/scope-manager/package.json#L36

**Review by bradzacher — COMMENTED** [review]
We can also just bump the peer dep ranges as there's no new features to handle from our side (according to the change log)

**Comment by sosukesuzuki** [comment]
@bradzacher 

> We can also just bump the peer dep ranges as there's no new features to handle from our side (according to the change log)

Sorry what does "peer dep ranges" mean?

**Review by bradzacher — APPROVED** [review]
thanks for doing this!

**Comment by bradzacher** [comment]
OOPS! Missed your comment.

> Sorry what does "peer dep ranges" mean?

Should just be this right here:

https://github.com/typescript-eslint/typescript-eslint/blob/56a09e98f171662d25ae2692be703a8bbbd3a3a5/packages/typescript-estree/src/parser.ts#L33

This is where we validate the TS version you're using. I forgot that we don't actually have a hard peer dependency range for TS in the package (they're all `"*"`)

**Comment by sosukesuzuki** [comment]
Why netlify on CI was failed..?

**Comment by bradzacher** [comment]
It's not your fault. The build is just flaky.

**Review by bradzacher — APPROVED** [review]
thanks for doing this!

**Pull request merged**
