### PR TITLE
docs: show importing configs in shared configs page

### LINKED ISSUE #9471: Docs: show importing configs in shared configs page
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now in https://typescript-eslint.io/users/configs, we never fully show how to use one of the preset configs. We show using them as a property of some `tseslint` object, but not how to actually create that object.

The configs page does link to other pages, but it's a little annoying & confusing to have to retain the convention & memory in your own. I'd suggest we include a little refresher blurb on the top:

```diff
## Getting Started

See [Getting Started > Quickstart](../getting-started/Quickstart.mdx) first to set up your ESLint configuration file.
[Packages > typescript-eslint](../packages/TypeScript_ESLint.mdx) includes more documentation on the `tseslint` helper.

+ ```ts
+ import tseslint from 'typescript-eslint';
+
+ export default tseslint.config(
+   // ...
+ );
+ ```

### Projects Without Type Checking
```

### Affected URL(s)

https://typescript-eslint.io/users/configs

💖 

This came out of a pairing with @Tobbe going over migrating Redwood from legacy config to flat config. Therefore:

Co-authored-by: @Tobbe

### PR DESCRIPTION
**Pull request by yaodada123**
## PR Checklist

- [x] Addresses an existing open issue:  fixes #9471
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

**Comment by yaodada123** [comment]
This is my first time to contribute to the project. I hope to get guidance and correction, so that I can make better contributions in the future

**Review by kirkwaiblinger — APPROVED** [review]
@yaodada123 Thanks for your first contribution to typescript-eslint!

The title issue was just a matter of adding a space in `docs:show` to be `docs: show`. Normally I'd suggest to look in the CI logs, since it gives an error message of why the title is invalid.... but in this case, the error message there was very vague and unhelpful 😆 so i went ahead and fixed it for you.

This PR will get merged when another team member has a chance to look at it and approve it.

Thanks again!

Thank you meme

**Comment by kirkwaiblinger** [comment]
Oh, also - for future reference, please keep the magic "fixes #XXXX" text in the description template. That's how the PR autocloses the issue 🙂 You can read more how that works on the [github docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Review by JoshuaKGoldberg — APPROVED** [review]
Yup, this is great - thanks! 🙌

**Pull request merged**
