### PR TITLE
feat(eslint-plugin): Add BigInt object type to default ban-types list

### PR DESCRIPTION
**Pull request by tduyduc**
## PR Checklist

-   [x] ~Addresses an existing open issue: fixes #000~ No issues have been created about this feature
-   [x] ~That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)~ No issues have been created about this feature
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

The pull request title says it all: to add `BigInt` type to the default list of banned types, given that `bigint` is a primitive type (just like `boolean`, `string`, `number`, and `symbol`).

The `ban-types` rule source code and the rule documentation have been changed.

### CODE REVIEW

**Comment by Josh-Cena** [comment]
It is impossible to construct a wrapper object of type `BigInt`, so `BigInt` and `bigint` are literally the same type, contrary to `number` or `boolean`.

**Comment by bradzacher** [comment]
In TS `Number` and `number` are really just aliases for the same type. They behave in exactly the  same way as far as I can tell - both are structurally typed and thus accept anything that looks like a `Number` - be it `Number`, `number` or a custom type that looks like `Number`.

The same probably goes for `String` and `Boolean`, and I would assume `BigInt` follows the same pattern.

**Comment by Josh-Cena** [comment]
Ugh, I see we ban `Symbol` as well, even when there's no danger. I see the reasoning.

**Review by JoshuaKGoldberg — APPROVED** [review]
Yup this makes sense, thanks!

**Comment by tduyduc** [comment]
> It is impossible to construct a wrapper object of type `BigInt`, so `BigInt` and `bigint` are literally the same type, contrary to `number` or `boolean`.

Boxed objects of `symbol`s and `bigint`s cannot be instantiated via `new Symbol()` or `new BigInt(1n)`, but can via `Object(Symbol())` and `Object(1n)` explicitly. Of course we won't need them generally all the time.




> 99.99999% of the time you don't want the capital version of the type, nor should you be constructing a wrapper object. Which is why the rule points people at using the lowercase type for the primitives.

It is also worth noting that the boxed primitive types can screw up TypeScript type guards. This can be a problem should we face bigger unions of types.

```typescript
declare var x: BigInt | bigint | undefined;
if (x instanceof Object) {
  x; // is BigInt (object)
} else if (typeof x === 'bigint') {
  x; // is bigint (primitive)
}
```

**Comment by Josh-Cena** [comment]
Oh I wasn't aware of the narrowing issue. It makes much more sense then 👍

**Pull request merged**
