### PR TITLE
feat(eslint-plugin): [no-unsafe-array-reduce] Add rule

### PR DESCRIPTION
**Pull request by asmundg**
Add rule for protecting against unsafe array reduce calls.

The type of `{}` is `{}`. Any object is assignable to `{}`. `{}` is assignable to
any indexed type (`{[key in string]: whatever}`).

A reduce call with an empty object initializer and no type signature,
will infer the `{}` type for the accumulator and result of the reduce
expression. Since anything is assignable to `{}`, this means the reduce
function is essentially unchecked. The result of the expression can then
also be assigned to an incompatible type without raising any errors.

This rule warns if a reduce call takes an empty object as the initial
value and has no type signatures.

### CODE REVIEW

**Comment by bradzacher** [comment]
I'm curious what the motivation behind this rule is.
With `noImplicitAny` turned on, attempting to do an index access on a variable typed as `{}` results in a TS error:

```ts
  const x = ['a'].reduce((acc, cur) => acc[cur], {});
//                                     ^^^^^^^^
// Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
//  No index signature with a parameter of type 'string' was found on type '{}'.(7053)
```

Additionally, `{}` has no properties, so you can't do `.` member access on it.

It seems fairly safe without a lint rule.
There is also #1707, which is similar to this rule.

**Comment by asmundg** [comment]
See https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBAZiEAuGBvGBtA1gUwJ4wCWYM0ATsQOYC6A-CuVTAL4wC8mARLnp9QHRkcAEwCuwHAApJAQ2DAANDGCiyASnYA+GJPT99cxZhVlqKAIws1S1MzUAoewHonMAEqiSUQgFscMABU8AAccAFEyMhAyewQQfh5afmgZMigIAHVCKAALSU5ONSA for a minimal example of how untyped reduce with a `{}` initial value can blow up at runtime.

You're right that you can't read indexes of the `{}` type, but you can assign to its indexes and you can assign it to another indexed type, bypassing the type checking in a way that none of the strict compiler options will catch.

#1707 is related, but it deals with _where_ the type argument is provided. Which seems like more of an aesthetic issue than requiring there to be a type argument like we do here.

**Comment by bradzacher** [comment]
I don't think creating a rule that just handles the case of an array reduce is a good solution to this, as this can happen in more  places than just a reduce.

```ts
let x: {} = {};
x = { ...x, a: 1 };
const y: Record<string, string> = x;
```

The specific problem here is that `{}` can receive any object-like type, and be similarly assigned to any object-like type. 
So a better solution would be to have a rule that bans the assignment of an `{}` typed value anywhere, to help catch this unsafety.

**Comment by asmundg** [comment]
I agree in principle. This is reduce-oriented since 
1. That's where I've seen people make this mistake
2. I'm not sure how a rule banning assignment of the `{}` type would be implemented

If you have some pointers on 2. that's definitely something worth looking into. :)

**Comment by bradzacher** [comment]
Sorry, this got lost in my notifications.

This could actually live in the `no-unsafe-*` rules.
We could treat `{}` as an additional unsafe type (same as those rules treat `any`).
That would save you having to implement it from ground up!

**Pull request closed without merging**
