### PR TITLE
chore: get the TypeScript version range from root package.json

### LINKED ISSUE #6389: Repo: Automate version ranges in website's Versioning.md
### Suggestion

From https://github.com/typescript-eslint/typescript-eslint/pull/6251#discussion_r1090119075: we have hardcoded version ranges in _Versioning.md_:

https://github.com/typescript-eslint/typescript-eslint/blob/66708d737855174ef7fe53c0023c4d78497d2e4f/docs/maintenance/Versioning.md#L45

Let's use some kind of Docusaurus<>React component shenanigan(s) to automate this. Supported version ranges should be sourced from our `package.json`s.

### PR DESCRIPTION
**Pull request by auvred**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6389
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

The goal of this PR is to refactor all possible places where the TypeScript version/version range is hardcoded and might be taken from the root `package.json`.

I found the following places (but there may be a few more here):

- [x] **Typescript version range in `docs/users/Dependency_Versions.mdx`** https://github.com/typescript-eslint/typescript-eslint/blob/d89b8472e554d9f4184a5a78d2b8cacc6790efd2/docs/users/Dependency_Versions.mdx#L19 It looks exactly the same as before, but now it has become dynamic 

- [x] **Available TypeScript versions in the playground (thanks to https://github.com/typescript-eslint/typescript-eslint/issues/6389#issuecomment-1444614016)** 
  
  Now it contains only versions that satisfy version range from root `package.json`
  

- [x] **Typescript version range in `docs/users/Versioning.mdx`**
  
  ~Will be~ Removed in https://github.com/typescript-eslint/typescript-eslint/pull/7343 https://github.com/typescript-eslint/typescript-eslint/blob/d89b8472e554d9f4184a5a78d2b8cacc6790efd2/docs/users/Versioning.mdx#L51

- _[Postponed]_ **Probably this range also should be taken from the root `package.json`** (Maybe I'm wrong)
  https://github.com/typescript-eslint/typescript-eslint/blob/d89b8472e554d9f4184a5a78d2b8cacc6790efd2/packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts#L5-L9 But the only thing that prevents this from being done is `"rootDir": "."` in the `tsconfig.json`
  https://github.com/typescript-eslint/typescript-eslint/blob/d89b8472e554d9f4184a5a78d2b8cacc6790efd2/packages/typescript-estree/tsconfig.json#L5 https://github.com/typescript-eslint/typescript-eslint/blob/d89b8472e554d9f4184a5a78d2b8cacc6790efd2/packages/typescript-estree/tsconfig.build.json#L6
  So we can't just import `package.json` from the repository root. Is there any other way do get this done? Or this constant and range in `package.json` must be independent?

- _[Postponed]_ **Also not sure what to do with this list** 
   
  Should it also be updated automatically? https://github.com/typescript-eslint/typescript-eslint/blob/d89b8472e554d9f4184a5a78d2b8cacc6790efd2/packages/typescript-estree/src/version-check.ts#L14-L23

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
For the hardcodings that are making things more difficult, I think it's ok to skip them for now. We can always file a followup issue to revisit. I'd rather get this partially fixed than wait on weird intricacies.

Worst case scenario, I bet `website-eslint` could include version ranges...

**Comment by auvred** [comment]
Hi! I looked through the `website-eslint` and didn't find anything there at all about the typescript versions.

So, should I skip last two tasks for now?

**Comment by JoshuaKGoldberg** [comment]
Yeah let's skip for now

**Review by JoshuaKGoldberg — APPROVED** [review]
💯 love it, thanks @auvred!

I can file a followup issue on the postponed stuff.

**Pull request merged**
