### PR TITLE
fix(type-utils): ensure external sources don't match for the `FileSpecifier`

### LINKED ISSUE #6819: Bug: v6 `typeMatchesSpecifier` `FileSpecifier` checks in node modules
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### Playground Link

_No response_

### Repro Code

```typescript
typeMatchesSpecifier(
  type,
  {
    from: "file",
    name: "RegExp",
  },
  parserServices.program)
```

### ESLint Config

_No response_

### tsconfig

_No response_

### Expected Result

It shouldn't find this type (as I haven't defined it).

### Actual Result

I finds it in "node_modules/.pnpm/typescript@5.0.3/node_modules/typescript/lib/lib.es5.d.ts".

### Additional Info

I would expect a `FileSpecifier` to ignore node module files by default.
`typescript/lib/*.d.ts` files should only match with a `LibSpecifier` and other files in node module to only match with a `PackageSpecifier`.

Maybe `FileSpecifier` needs an extra property like `ignorePath` or `ignoreGlob` that defaults to `"node_modules"`.
Or alternatively, `path` could be made a glob that defaults to selecting files not in `"node_modules"`.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `6.0.0-alpha.106` |
| `@typescript-eslint/parser`            | `6.0.0-alpha.106` |
| `@typescript-eslint/scope-manager`     | `6.0.0-alpha.106` |
| `@typescript-eslint/typescript-estree` | `6.0.0-alpha.106` |
| `@typescript-eslint/type-utils`        | `6.0.0-alpha.106` |
| `@typescript-eslint/utils`             | `6.0.0-alpha.106` |
| `TypeScript`                           | `5.0.3` |
| `ESLint`                               | `8.36.0` |
| `node`                                 | `18.15.0` |

### PR DESCRIPTION
**Pull request by RebeccaStevens**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6819
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This is an alternative to #6860 (closes #6860).

### CODE REVIEW

**Comment by RebeccaStevens** [comment]
@marekdedic How's this approach look to you?

**Comment by marekdedic** [comment]
Hi, thanks for the alternative proposal!

Reading quickly through this, I see this mainly builds on the `ts.getEffectiveTypeRoots()` function, which I didn't know before - quick googling led me here - I understand this description so that this would exclude all types declared in some `@types/...` package - however, if I understand it correctly, the type roots *don't include* folders for packages that ship their own types - so for example types from the `vue` package would still be found. Is that correct or am I missing something?

**Comment by marekdedic** [comment]
Oh actually, I see `isSourceFileFromExternalLibrary` there as well (previously thought that was the *default* library instead of external...) - reading the source code of that, I am confused - wouldn't this function alone do exactly what we want it to do - exclude stuff from `node_modules`? Or does that not include `@types/...` packages - then I'd understand the type roots bit :D

Sorry, if this does what I think it does then it's great, but as you see, I'm not that well versed with TS internals :/

**Comment by RebeccaStevens** [comment]
This approach actually reply more on `program.isSourceFileFromExternalLibrary(declaration)`.

`ts.getEffectiveTypeRoots()` is a little extra to support custom type root paths. The function will return `[/absolute/path/to/project/node_modules/@types]` unless `typeRoots` is specified in the `tsconfig.json` file.

**Comment by marekdedic** [comment]
Hmm, yes, that's what I thought in my second comment, sorry for the confusion. I am still not 100% why the type roots are needed - if `program.isSourceFileFromExternalLibrary(declaration)` supports custom `node_modules` location, then typeRoots wouldn't be needed, right? And if it does, then this will be a half-measure - `@types/` packages will be excluded, regular packages wouldn't, right?

Anyway, apart from this, LGTM.

**Comment by marekdedic** [comment]
Could you please add a test for this?

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Test coverage please? I see a missing line 😄

**Comment by marekdedic** [comment]
Oh, and just for the original question - IMHO, I prefer this to the alternative PR #6860

**Comment by JoshuaKGoldberg** [comment]
This was unintentionally auto-closed when we merged the `v6` branch 🙃 it'll be recreated.

**Comment by JoshuaKGoldberg** [comment]
👋 Hey @RebeccaStevens! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

**Comment by JoshuaKGoldberg** [comment]
Closing this PR as it's been stale for a while without activity. Feel free to reopen @RebeccaStevens if you have time - but no worries if not!

If anybody wants to drive it forward, please do post your own PR - and if you use this as a start, consider adding a co-author at the end of your PR description. Thanks! 😊

**Pull request closed without merging**
