### PR TITLE
fix(utils): removed `TRuleListener` generic from the `createRule`

### LINKED ISSUE #5032: Bug: Created rules using `RuleCreator` are not portable
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### Playground Link

_No response_

### Repro Code

```typescript
const createRule = ESLintUtils.RuleCreator(name => {
  const ruleName = parsePath(name).name

  return `${REPO_URL}/blob/@emotion/eslint-plugin@${version}/packages/eslint-plugin/docs/rules/${ruleName}.md`
})

// it isn't a problem with `createRule<never[], keyof typeof messages>({`
createRule({
  name: __filename,
  meta: {
    docs: {
      description: 'Ensure vanilla emotion is not used',
      recommended: false
    },
    messages: {
      vanillaEmotion: 'Vanilla emotion should not be used'
    },
    schema: [],
    type: 'problem'
  },
  defaultOptions: [],
  create(context) {
    return {
      ImportDeclaration(node) {
        if (node.source.value === '@emotion/css') {
          context.report({
            node: node.source,
            messageId: 'vanillaEmotion'
          })
        }
      }
    }
  }
})
```

### ESLint Config

_No response_

### tsconfig

_No response_

### Expected Result

A definition file for a library utilizing this util should be generated just fine.

### Actual Result

We get an error like this one:
> TS2742: The inferred type of 'rules' cannot be named without a reference to '@typescript-eslint/utils/node_modules/@typescript-eslint/types/dist/generated/ast-spec'. This is likely not portable. A type annotation is necessary.

I've diagnosed this and the problem is that the final `RuleModule` contains a reference to `TRuleListener` and its type contains references to types from another packages:
https://github.com/typescript-eslint/typescript-eslint/blob/ed7b5f61d93799fec3e38a87935ab9caa3abe279/packages/utils/src/eslint-utils/RuleCreator.ts#L95

I've also figured out a workaround - we need to provide generic params explicitly, to disable the inference for the third generic param (`TRuleListener`) and just use its default. The workaround in practice can be checked out here: https://github.com/emotion-js/emotion/pull/2761/files/79848d3a5ff7fa5338d31a27fb94951ea15071fa

I wonder though... why the `TRuleListener` is a generic? Does it have to be referenced in `RuleModule`? I would have assumed that a rule should be rather opaque to the consumer 🤔 (at least in relation to what kind of AST types does it process and stuff like that) 

cc @JoshuaKGoldberg, funny enough that I've stumbled upon this issue just after this recent conversation on Twitter: https://twitter.com/JoshuaKGoldberg/status/1526969335717191692 😅 

### Additional Info

_No response_

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/utils`             | `5.25.0` |
| `TypeScript`                           | `4.5.5` |
| `ESLint`                               | `^7.10.0` |

### PR DESCRIPTION
**Pull request by Andarist**
BREAKING CHANGE:
Removes generic parameter from public API

## PR Checklist

-   [x] Addresses an existing open issue: fixes #5032
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

I've dropped `TRuleListener` generic from the public-facing API~. So it no longer should be inferred with types coming from other packages.

This generic is still present in the `RuleModule` and in some other things as it seems that it's useful there for extending base rules (which kinda is like an internal thing, from what I understand).

### CODE REVIEW

**Review by JoshuaKGoldberg — DISMISSED** [review]
LGTM! If this solves your use case then 💯.

I suspect you could probably also remove the `TRuleListener`s from `CLIEngine.ts` and `Rule.ts`, but no worries if that's left for another day.

**Comment by JoshuaKGoldberg** [comment]
NB, #5037 discusses when we should release the next major version. If anybody reading this feels strongly that this change shouldn't have to wait 5 months then please mention there. 🙂

**Comment by Andarist** [comment]
> I suspect you could probably also remove the TRuleListeners from CLIEngine.ts and Rule.ts, but no worries if that's left for another day.

Done. I had to leave it in the `RuleModule` type in `Rule.ts` though (that's the core of why it's needed in the first place).

**Review by JoshuaKGoldberg — APPROVED** [review]
Just re-approving for paperwork purposes 🙂

**Comment by bradzacher** [comment]
@scamden why do you have tsconfig references to the internal plugin? Plugins really shouldn't export any usable types or API because they are only consumed indirectly via the untyped ESLint config.

For a working example we have an internal plugin in this repo that works just fine.

**Comment by scamden** [comment]
we depend on the package in package.json as a pnpm workspace dep (so we can use the rules in each packages eslintrc). we also use an automated tool the creates the tsconfgi refs based on any pnpm workspace dependencies: https://github.com/Bessonov/set-project-references

also we do in fact need the ref i think cause otherwise `tsc --build` won't know to rebuild the eslint-plugin package from those that depend on it to add to their eslintrc's, plz tell me i'm wrong :)

**Comment by scamden** [comment]
@bradzacher ping on the above. also any word on when this can be merged?

**Comment by scamden** [comment]
just another ping on this @bradzacher do you all compile using `tsc --build` option? i believe references are necessary for this to function

**Comment by JoshuaKGoldberg** [comment]
@scamden per [our contributing guide](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md#pull-requests), please don't comment on open PRs asking for updates. We're a volunteer team with limited resources or budget. This PR is on the list and we'll get to it when we can.

That being said, I started work on making a new v6 version (#5883) and hope to get this in soon, perhaps in the next week or so.

**Comment by scamden** [comment]
apologies! and thanks for your work! i was just answering this question

>  If anybody reading this feels strongly that this change shouldn't have to wait 5 months then please mention there. 🙂

as an anybody who saw a more immediate need. and i now see the "there" that i missed initially as well. my bad. thanks again!

**Comment by bradzacher** [comment]
@scamden

We do use project references and we do use `--build`, but we don't have any packages that depend on our plugins, so there is no need for the plugins to be compiled with declarations.

It seems like your workspace trades-off a lighter build without declarations in favour of automated configuration?

I definitely understand the desire to use that package to manage project references! It just seems like it's doing the wrong thing by making your production code build "depend on" your dev-only eslint plugins.

Generally I'd recommend just making the plugin build a pre-step for your lint command rather than doing the build implicitly via project references.

**Comment by scamden** [comment]
> We do use project references and we do use `--build`, but we don't have any packages that depend on our plugins, so there is no need for the plugins to be compiled with declarations.

if you're using --build that builds referenced projects, if the eslint plugin is a referenced project it has to have `composite : true` which auto-enables declarations. if it's not a referenced project it it won't get built by --build, so maybe you are building it independently? point is if we want to use --build to auto build the things we have to build declarations whether dependents need them or not. 

Either way, I realized I could solve this by explicitly declaring the return type to be  `ReturnType<typeof createRule>` so we are unblocked. Thanks for the attention and for all the excellent work on this plugin!

**Pull request merged**
