### PR TITLE
fix(eslint-plugin)!: [explicit-member-accessibility] Stop checking parameter properties

### LINKED ISSUE #617: [explicit-member-accessibility] Override off not respected for constructor parameter properties
**Repro**

```js
{
  "rules": {
    "no-parameter-properties.md": "off",
    "@typescript-eslint/explicit-member-accessibility": ["error", {
      accessibility: "no-public",
      overrides: {
        constructors: "off",
      }
    }],
  }
}
```

```TS
class Foo {
  constructor(public bar) { ... }
}
```

**Expected Result**
No error.

**Actual Result**
Error.
```
error    Public accessibility modifier on parameter property foo
@typescript-eslint/explicit-member-accessibility
```

**Additional Info**

**Versions**

```
    "@typescript-eslint/eslint-plugin": "^1.10.2",
    "@typescript-eslint/parser": "^1.10.2",
    "typescript": "^3.5.1",
    "eslint": "^5.16.0",
```

Was able to work around by setting default to off and overriding on for properties and methods.

### LINKED ISSUE #857: [explicit-member-accessibility] parameterProperties: 'explicit' not working as expected
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/explicit-member-accessibility": ["error", {
      "accessibility": "explicit"
    }]
  }
}
```

or

```JSON
{
  "rules": {
    "@typescript-eslint/explicit-member-accessibility": ["error", {
      "accessibility": "off",
      "overrides": { "parameterProperties": "explicit" }
    }]
  }
}
```

```TS
export class WithParameterProperty {
  public constructor(readonly value: string) {}
}
```

**Expected Result**
An error that the parameter property `value` needs an accessibility modifier like `private`, `protected`, or `public`

**Actual Result**
No error

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.0.0` |
| `@typescript-eslint/parser`        | `2.0.0` |
| `TypeScript`                       | `3.5.3` |
| `ESLint`                           | `6.1.0` |
| `node`                             | `12.6.0` |
| `npm`                              | `6.9.0` |

### PR DESCRIPTION
**Pull request by ankeetmaini**
BREAKING CHANGE: changes rule config

Fixes #617
Fixes #857

### CODE REVIEW

**Comment by ankeetmaini** [comment]
I am not sure why coverage went down. I added the test cited in the issue and worked my way of figuring out the solution. I am not sure if my approach is correct. Do let me know! Thanks :)

**Comment by ankeetmaini** [comment]
@bradzacher thanks, I didn't know about it! I've removed the selector, edited some failing tests and rebased the PR with master.

**Comment by ankeetmaini** [comment]
Done!

**Comment by ankeetmaini** [comment]
I've to update the doc as well. Will do that and update here shortly.

**Comment by ark120202** [comment]
Parameter properties also can be declared with a `readonly` modifier:

```ts
class Foo {
  constructor(readonly bar: string) {}
}
```

So the change there should be:
```diff
-if (paramPropCheck === 'no-public' && node.accessibility === 'public') {
+if (paramPropCheck === 'no-public' && node.accessibility === 'public' && !node.readonly) {
```

It also currently doesn't enforce it with `explicit`, but that's a different issue.

**Comment by JamesHenry** [comment]
@ankeetmaini we are currently preparing the v2 release (i.e. breaking changes are currently eligible to be merged) when do you think you will have chance to make the change suggested by @ark120202?

**Comment by ankeetmaini** [comment]
I totally missed the above comment, apologies. So for the above mentioned change, I'll have to undo the removal of `parameterProperties `, correct? Just confirming.

**Comment by bradzacher** [comment]
yes, I was wrong, sorry.
I completely forgot about the `readonly` only case.

Unless I'm mistaken - these should be the states:

valid when `parameterProperties: 'off'`:
- `private/protected/public foo`
- `private/protected/public readonly foo`
- `readonly foo`

valid when `parameterProperties: 'explicit'`:
- `private/protected/public foo`
- `private/protected/public readonly foo`
invalid:
- `readonly foo`

valid when `parameterProperties: 'no-public'`:
- `private/protected/public foo`
- `private/protected readonly foo`
- `readonly foo`
invalid:
- `public readonly foo`

**Comment by ankeetmaini** [comment]
Closing this in favour of #912

**Pull request closed without merging**
