### PR TITLE
Update comma-dangle.md

### PR DESCRIPTION
**Pull request by be-codified**
Added note for 404 link.

## PR Checklist

-   [ ] Addresses an existing open issue: fixes #000
-   [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [ ] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

### CODE REVIEW

**Review by bradzacher — DISMISSED** [review]
We should instead just update the link to point at the correct URL.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Ah, thanks for noticing this!

A more user-helpful fix would be to correct the link to https://eslint.org/docs/rules/comma-dangle. Could you do that instead please?

**Comment by be-codified** [comment]
@JoshuaKGoldberg sure, I have also added anchor for options. Keep up the good work.

**Review by JoshuaKGoldberg — APPROVED** [review]
Thanks!

**Comment by bradzacher** [comment]
@JoshuaKGoldberg dont forget to update the commit message before merging next time!

**Comment by Josh-Cena** [comment]
GH quirk: if there are multiple commits in the branch, the squash-merge commit's message would take the PR title; otherwise, the commit message would be that single commit's message. Regardless, I would recommend always normalizing the PR title as well.

**Comment by JoshuaKGoldberg** [comment]
Oop sorry, yes!

**Pull request merged**
