### PR TITLE
chore(eslint-plugin): remove support for eslint 5

### LINKED ISSUE #2465: Drop support for ESLint v5
Most users have migrated off of v5 by this point, and I think a year back is far enough for us to support.
Supporting old versions restricts which APIs we can use, and makes it harder to build extension rules as we have to take care to fill in missing messageIds ourselves.

ESLint v6.0.0 was released 21 June 2019 - over 1 year ago.
ESLint v5.0.0 was released 22 June 2018 - over 2 years ago. This version predates the official forming of this project.

### PR DESCRIPTION
**Pull request by thomasmichaelwallace**
Resolves #2465 

As far as I understood the issue, you don't think this is a breaking change (what with v5 being very old).

Following the issue I compared against eslint 6.8 (latest) to see what messageIds weren't set then, so as to avoid regressing #2451.

### CODE REVIEW

**Comment by bradzacher** [comment]
Thanks for doing this!

I didn't label it as such, but it is a breaking change - any change in the supported dependencies is a breaking change (even if people *should* have upgraded their deps by now).
We can leave this on ice until we are ready for the next major.

**Comment by thomasmichaelwallace** [comment]
No worries - I did suspect as much. Feel free to @thomasmichaelwallace me when the time comes for v5, I'd be happy to tackle any issues updating the branch for merge.

It'd be awesome if you could label the PRs [hacktoberfest-accepted](https://hacktoberfest.digitalocean.com/details#details) in the interim. (Sorry to ask, it's annoying they put this on the maintainers; if it's a hassle, it's not a problem.)

**Comment by armano2** [comment]
we should also look at changes done in #2917 and most likely some of them can be removed

**Comment by bradzacher** [comment]
Unfortunately with eslint v8 they hid all of their utils - so we can't leverage them - so we're stuck with the changes from #2917

**Review by bradzacher — APPROVED** [review]
thanks for this! we can finally merge this in :)

**Review by bradzacher — APPROVED** [review]

**Pull request merged**
