### PR TITLE
feat(eslint-plugin): add rule `no-unused-type-properties`

### PR DESCRIPTION
**Pull request by eltonio450**
Hello everyone,

I tried to implement a rule to disallow unused type properties (https://github.com/typescript-eslint/typescript-eslint/issues/1529)

Our use case is to catch forgotten props when refactoring a React component, but I guess there are plenty of others. I included the example in the doc, but I copy paste it here: 

```
type MyProps = {
  a: string,
  b: string //forgotten and now unused props
}


// Error: Destructuring does not use all of the properties of the type MyProps, you should either remove the properties from the type or use Omit<MyProps, ...> to explicitly exclude the properties.',

const MyComp = ({ a } : MyProps) => {
    return <div>{a}</div>
}
```

This is my first rule, so this PR is a draft (but working !). 

I have a few questions :

### Config:
- about the requiresTypechecking options : I am not really sure if I have to enable it or not...
- I could not really test my rule by linking @typescript-eslint/eslint-plugin package in some of my projects, did I miss something ? Should it work as any other package ?

### Coding style: 
- I saw that many rules don't use arrow function : is there a reason ? Should I comply to this or it does not matter ?
- are there some shared AST_NODE_TYPES typecheckers somewhere in the package ?

### The rule itself
- I am not sure which case should I handle. For example, should I handle Omit or not ? Does this require to enable the requiresTypeChecking option ?
- I did not include the case where the type is exported, not sure if it makes sense
- should I include interface declaration in the check ?

I hope this rule makes sense and will be merged someday, feel free to share your remarks, I'll be glad to make the corrections !

All the best

[EDIT : deleting some questions, as I have found the answer while trying to increase coverage :)]

### CODE REVIEW

**Comment by eltonio450** [comment]
Hello,

@bradzacher what is the next step ? I think a good first one would be you to tell me if we should include interfaces in this rule :

```typescript
interface MyProps {
  a: string,
  b: string //forgotten and now unused props
}


// Error: Destructuring does not use all of the properties of the interface MyProps, you should either remove the properties from the type or use Omit<MyProps, ...> to explicitly exclude the properties.',

const MyComp = ({ a } : MyProps) => {
    return <div>{a}</div>
}
```

I lack a bit of experience to really see if it fits in the spirit of a typescript rule.

If yes, I need a few more days to adapt the rule and messages

Thank you

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md#addressing-feedback-and-beyond

**Comment by eltonio450** [comment]
oopsi, sorry, I did not mean to be pushy or so 😢 , the question was real, and since the last time it took me two months to address your advice, I was like, ok, let's ask in advance this time 😄 

if you have time in advance to give a piece of advice on this interface thing, great, if not, it will wait for the complete review 👍 

thank you!

**Comment by eltonio450** [comment]
Good guess for the eslint react repo, thank you :) :

I did not know we could write typescript specific rules, but yes, it's possible ! And even better, a rule for this use case exists: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md (I thought it was specific to dynamic propTypes 😢 )

turns it it does not work (https://github.com/yannickcr/eslint-plugin-react/issues/2569) but that's another story I guess 

As for the PR, is it worth finalizing it based on your remarks ? I think the path is pretty clear now, thank you for the information, but does it add value ? If yes, I'll try do finish asap

For the type checkers, I have three functions in my PR : 

```
//TODO(question): are there type checker somewhere ?
function isProperty(
  property: TSESTree.Property | TSESTree.RestElement,
): property is TSESTree.Property {
  return property.type === AST_NODE_TYPES.Property;
}

function isObjectPattern(
  param: TSESTree.Parameter,
): param is TSESTree.ObjectPattern {
  return param.type === AST_NODE_TYPES.ObjectPattern;
}

function isTypeAliasDeclaration(
  item: TSESTree.Statement,
): item is TSESTree.TSTypeAliasDeclaration {
  return item.type === AST_NODE_TYPES.TSTypeAliasDeclaration;
}
```

And I was wondering if I missed some shared utilities somewhere 

Thank you !

**Comment by bradzacher** [comment]
> For the type checkers, I have three functions in my PR :

Oh I get you, no we don't have ones for those.

All utilities are available via the `utils` namespace.

We can always add more to https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/src/ast-utils/predicates.ts if we want those.

---

> As for the PR, is it worth finalizing it based on your remarks ?

I don't think it does make sense to progress with this PR.
I think it would be better to fix the mentioned bug in the `eslint-plugin-react` rule, and use that rule instead.

Chances are you could probably also discuss with the maintainers and consume type information in that rule to make it more accurate (after first fixing the bug)

**Comment by eltonio450** [comment]
ok, closing then :)

thank you for your help along the process 👍

**Pull request closed without merging**
