### PR TITLE
feat(typescript-estree): experimental option to cache type checking APIs

### LINKED ISSUE #6425: Enhancement: Investigate caching type checking APIs
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-estree

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Continuing from https://github.com/typescript-eslint/typescript-eslint/pull/6404#discussion_r1092793414: we've been talking off-and-on for ages now about adding a thin layer of caching around TypeScript's type checking APIs.

> do we want to do a weakmap memo on these? Eg
> 
> ```ts
> function memoize<TNode, TRet>(fn: (node: TNode) => TRet): (node: TNode) => TRet {
>   const cache = new WeakMap<TNode, TRet>();
> 
>   return (node) => {
>     const cachedRet = cache.get(node);
>     if (cachedRet) {
>       return cachedRet;
>     }
> 
>     const newRet = fn(node);
>     cachedRet = cache.set(node, newRet);
>     return newRet;
>   };
> }
> ```
> 
> That would allow us to enforce that if two rules request the exact same node then we'll 100% use a fast path.
> 
> Doing a quick look at the implementation of `getTypeAtLocation` - it doesn't do any fast caching, so it does do a bunch of work.
> 
> IDK if this sort of thing would actually save any real time though - would be worth a test. Maybe we can file an issue to look at this later?

### Additional Info

This'll require performance testing. Does it actually speed things up? Does it cause out-of-memory issues on our repo? Let's find out!

Strong candidate for including in the `v6` betas. I'd like to get real world user testing to make sure this doesn't explode anybody.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #6425
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Applies a thin memoization layer on top of `getSymbolAtLocation` and `getTypeAtLocation`.

[hyperfine](https://github.com/sharkdp/hyperfine) measurements are not very promising:

<table>
<thead>
<tr>
<th>Package</th>
<th><code>v6</code></th>
<th>Memoizing shortcut API</th>
<th>Memoizing type checker</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>eslint-plugin</code></td>
<td><code>21.467 s ±  0.096 s</code></td>
<td><code>21.465 s ±  0.121 s</code></td>
<td><code>26.675 s ±  0.096 s</code></td>
</tr>
<tr>
<td><code>typescript-estree</code></td>
<td><code>11.755 s ±  0.052 s</code></td>
<td><code>11.983 s ±  0.113 s</code></td>
<td><code>12.128 s ±  0.045 s</code></td>
</tr>
</tbody>
</table>

I'm betting I'll want to add caching around the native type checker (`checker.getContextualType`) too.

I'll probably want to add an `EXPERIMENTAL_` option so we can put this in v6 and get easier real world testing.

Co-authored-by: @bradzacher

### CODE REVIEW

**Comment by bradzacher** [comment]
> [hyperfine](https://github.com/sharkdp/hyperfine) measurements are not very promising:

What's the command you used to grab the hyperfine measurement?
I've been raw-dogging the entire codebase lint run via `./node_modules/.bin/eslint .` (to work around yarn and ensure i run eslint directly).

Do we have a bigger type-aware codebase we can test on?
Maybe we can just turn on every single rule in our codebase for the test run to increase the possibility of cache hits (I know we're fairly conservative in our type-aware linting ATM).

**Comment by JoshuaKGoldberg** [comment]
`yarn lint --skip-nx-cache` - it's deep in the edit history. I do want to do more thorough checking, including on the codebase as a whole. And there might be more type checker APIs that should be cached.

**Comment by JoshuaKGoldberg** [comment]
@bradzacher not-very-promising news on this:
* Running `time MEMOIZE_TYPE_CHECKING_APIS=true yarn lint --skip-nx-cache` takes ~60 seconds for me - same as `time yarn lint`
* Running `time MEMOIZE_TYPE_CHECKING_APIS=true yarn lint-many` runs out of memory (instead of taking ~110 seconds)

I think it'd make sense to ship this change, since it's small and additive and labeled as `EXPERIMENTAL_`. Thoughts?

**Comment by JoshuaKGoldberg** [comment]
This was unintentionally auto-closed when we merged the `v6` branch 🙃 it'll be recreated.

**Comment by JoshuaKGoldberg** [comment]
I'm more hopeful about the `EXPERIMENTAL_useProjectService` parser option (#6754). Closing this for now.

If someone does think this PR would benefit them, feel free to post an explanation why! We can always re-open - or even better, _you_ the reader can open it and take ownership.

**Pull request closed without merging**
