### PR TITLE
chore: ask for lib/Node/npm versions in parser issue template

### PR DESCRIPTION
**Pull request by kaicataldo**
Thought this could yield useful information up front so that maintainers have to spend less time chasing down this info if it's relevant.

### CODE REVIEW

**Comment by kaicataldo** [comment]
Any idea why the `check-format` npm script might be failing? It doesn't seem to be outputting anything, and Prettier should have run over this file during the pre-commit hook.

**Comment by JamesHenry** [comment]
It's outputting:

```.github/ISSUE_TEMPLATE/typescript-eslint-parser.md```

**Comment by kaicataldo** [comment]
Yeah, I'm not sure why `lint-staged` isn't formatting `.github/ISSUE_TEMPLATE/typescript-eslint-parser.md` when it's run. I ended up adding an npm script and was going to ask about it - great minds! This should be ready to go now.

**Comment by JamesHenry** [comment]
Thanks!

**Pull request merged**
