### PR TITLE
chore(ts-estree): draft of estree structure (replacement for ESTreeNode)

### PR DESCRIPTION
**Pull request by armano2**

### CODE REVIEW

**Comment by bradzacher** [comment]
I started doing this by hand on my plugin types branch!

https://github.com/typescript-eslint/typescript-eslint/pull/120/files/e44fba51ff881b642a3a96232488c3380ffabf2b..9bfbb86125c1d7c4ebe200ef1adec6462f0673e8

**Comment by armano2** [comment]
during generation i'm able to group nodes (i have functionality for this)

**Comment by bradzacher** [comment]
That's awesome! But we'd have to go through the typescript AST to find out all of the reusable type groupings they use, then map those types in ESTree nodes. It's simple to do, but it's far from a trivial thing time-wise, so it's probably better left till after.

Anyways, we'd probably want to do a manual pass over these types to triple check they aren't missing anything from our conversion logic in `convert.ts`.

**Comment by armano2** [comment]
this is first step, i have in plans to use types in converter itself

this PR is to your branch not to master

**Comment by bradzacher** [comment]
I didn't notice that. Awesome, feel free to merge it in.
I'll reconcile the two lists, delete mine and keep plugging through the logic.
I'm about 1/3 of the way through.

**Pull request merged**
