### PR TITLE
chore: update husky v9 and prepare scripts for v10

### LINKED ISSUE #9688: Bug: .husky/_/_/husky.sh: No such file or directory
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

When committing, Husky fails. The commit goes through, but pre-commit hooks like Prettier are not run.

```
$ git add -A && git commit -m test                                      
.husky/pre-commit: line 2: .husky/_/_/husky.sh: No such file or directory
.husky/commit-msg: line 2: .husky/_/_/husky.sh: No such file or directory
[main 984380a1d] test
 1 file changed, 2 insertions(+)
```

### Reproduction Repository Link

https://github.com/typescript-eslint/typescript-eslint

### Repro Steps

1) clone the repo
2) `yarn`
3) edit a file
4) add and commit
5) note that any changes you made are not prettied

### Versions

- `node`: `22.1.0`
- `yarn`: `3.8.2`

### PR DESCRIPTION
**Pull request by Kenneth-Sills**
## PR Checklist

- [X] Addresses an existing open issue: fixes #9688
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken
    - Formatted, Linted, Proofread, and Type-Checked.
    - Passes dogfooding (no `--no-verify` needed to make this PR).

## Overview

Husky v9.1.1 removed support for shebangs, the need to manually call any implementation scripts, and improved performance by running `npx` commands directly instead of through a separate instance of Node.

This was intended to be seamless, with Husky automatically migrating the scripts, but tools like Renovate disable Husky execution and it accidentally started to break our project setup instead. This version bump to 9.1.4 brings back support, removing the need to spam `--no-verify`.

I've also:

- Removed the `.husky/commit-msg` script that does nothing.
- Removed the unnecessary `.husky/.gitignore` (Husky maintains its own `*` one under `.husky/_/`.
- Updated the remaining `.husky/pre-commit` script to prepare it for Husky v10, which will officially remove support for shebangs and manual implementation script calls.

This DOES NOT affect end-users, just maintainers.

### CODE REVIEW

**Review by JoshuaKGoldberg — DISMISSED** [review]
What a great cleanup! Pity it took a little console erroring to get here 😄 but very excited to remove so many files. Thanks!

**Review by kirkwaiblinger — DISMISSED** [review]
Thanks!

**Comment by reduckted** [comment]
Another husky change: the `husky install` command is deprecated.

https://github.com/typicode/husky/releases/tag/v9.0.1

> Removed `husky install`. Use `husky` or `husky some/dir` for the same functionality (deprecation notice to be added).

I'm not sure if you want to fix it in this PR, but thought I'd mention it. 😄 

https://github.com/typescript-eslint/typescript-eslint/blob/a0c70e96067a0af5193520d703f1a716467d40e2/tools/scripts/postinstall.mts#L39

**Comment by JoshuaKGoldberg** [comment]
Good call, thanks @reduckted!

**Comment by JoshuaKGoldberg** [comment]
The husky issue was really annoying to me so I went ahead and made the install change just now and merged. Thanks all!

**Pull request merged**
