### PR TITLE
fix(eslint-plugin): [rules] Only enable rules on typescript files and include dot files

### PR DESCRIPTION
**Pull request by chrisblossom**
Typescript rules should only be enabled on typescript files. This is important for repositories with both normal JS and TS.

I ran into this problem when creating a universal eslint config for my projects.  Typescript eslint rules were being enabled on normal javascript files causing a missing typescript dependency eslint error. I've [manually imported them as a solution](https://github.com/chrisblossom/eslint-config/blob/99fac9db5cabc586fbfec0e1dca7060955017443/lib/typescript.js), added [Typescript detection script](https://github.com/chrisblossom/eslint-config/commit/f0992b44fea7b6ca8233c6d856188a72835ba577) but I think this should be fixed here.

This PR also enables overrides on `.dot` files for eslint < v6. See: https://github.com/eslint/eslint/pull/11225 and https://github.com/eslint/eslint/issues/11201

I've been meaning to put a PR in for sometime now, but https://github.com/typescript-eslint/typescript-eslint/issues/501#issuecomment-513580519 motivated me to put in now because this is might be considered a breaking change.

Looks to close https://github.com/typescript-eslint/typescript-eslint/issues/109
Similar: https://github.com/typescript-eslint/typescript-eslint/issues/615

### CODE REVIEW

**Comment by bradzacher** [comment]
Thank you for your contribution!

I don't think this is the correct way to do things.
Doing so will make it very hard for people to adjust the recommended config.

Consider the following case:

```cjson
{
  "extends": ["plugin:@typescript-eslint/recommended"],
  "rules": {
    // disable recommended rule
    "@typescript-eslint/ban-types": "off"
  }
}
```

The user's disabling of the `ban-types` rule will do nothing, because the `override` within the recommended config takes precedence, because it is more specific.

This means that instead a user has to know that the recommended config uses overrides, and use overrides themselves:

```cjson
{
  "extends": ["plugin:@typescript-eslint/recommended"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", ".*.ts", ".*.tsx"],
      "rules": {
        // disable recommended rule
        "@typescript-eslint/ban-types": "off"
      }
    }
  ]
}
```

This is obviously a sub-optimal experience, especially for those that have pure TS codebases.

---

I think that this is better fixed in user-land.
You can handle your mixed codebase within your config file, by only applying our recommended config to your `\.ts(x)?` files (as per https://github.com/typescript-eslint/typescript-eslint/issues/109#issuecomment-502531008, eslint6 now supports this)

```
{
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", ".*.ts", ".*.tsx"],
      "extends": ["plugin:@typescript-eslint/recommended"],
    }
  ]
}
```

**Comment by chrisblossom** [comment]
Thanks for the quick response! Also, I didn't see the previous discussion until after I submitted he PR.

I think it is unexpected behavior that the recommended rules run on `.js`, including changing the `parser` and `sourceType` for `.js` files.

Your concern about how an end user has to override has been [fixed in v6](https://eslint.org/docs/user-guide/migrating-to-6.0.0#-overrides-in-an-extended-config-file-can-now-be-overridden-by-a-parent-config-file).

I propose I modify this PR to use `overrides` for [eslint >= v6](https://eslint.org/docs/developer-guide/nodejs-api#cliengineversion) and the previous behavior for older versions. I think that would solve everyone's concerns and work as expected moving forward.

**Comment by chrisblossom** [comment]
@bradleyayers What are your thoughts about what I proposed? If this isn't wanted no problem please close, I've solved it already for myself just wanted to help others.

**Comment by bradzacher** [comment]
I wasn't sure. Might be worth getting comments from some of the eslint peeps

cc @typescript-eslint/eslint-team

**Comment by phaux** [comment]
I don't see any reason why somebody would want to disable typescript rules for js files. They might be not as useful, but they're still beneficial.

**Comment by bradzacher** [comment]
Hey there - sorry it's been so long.
I've had a think about this, and I think it's best if we don't do this, because it would affect many of our userbase.

As mentioned - the rules all work fine on JS code (there are only a v small list of exceptions, like `explicit-function-return-type`).
Additionally, there are many users that use these rules on things like markdown files, and vue files, which means they wouldn't be able to use the recommended sets.

None the less, thanks for the contribution!

**Pull request closed without merging**
