### PR TITLE
chore: declare TypeScript as an optional peerDependency

### PR DESCRIPTION
**Pull request by dstaley**
This PR adds TypeScript as an optional peer dependency for `@typescript-eslint/eslint-plugin`. This modification is necessary to get `@typescript-eslint/eslint-plugin` working with Yarn v2, and is one of two packages that need this modification so that the TypeScript version of `create-react-app` can work with Yarn v2.

Optional peer dependencies work as expected in Yarn and pnpm, and will be supported in npm once a [server-side fix](https://github.com/npm/cli/pull/224#issuecomment-524002488) is deployed.

Other relevant issues: yarnpkg/berry/pull/475

### CODE REVIEW

**Comment by bradzacher** [comment]
Thanks for opening this.
This should also be done for `typescript-estree`.

We were planning on doing this ourselves, but we wanted to wait until the fix landed and was well rolled out within `npm`.

**Comment by arcanis** [comment]
@dstaley @bradzacher Can you at least add the `peerDependenciesMeta` without `peerDependencies` for now? Yarn will interpret it as an implicit peer dependency on `*`, and npm won't print warnings about it.

**Comment by bradzacher** [comment]
That's awesome! I didn't know that it did that.
I think we can definitely add the meta by itself without delaying.
Happy to accept a PR, or I'll raise one tonight.

**Comment by dstaley** [comment]
@bradzacher explicit dependencies have been removed!

**Comment by arcanis** [comment]
Awesome, thank you both! 🥳

**Comment by bradzacher** [comment]
FYI - we missed the release by a bit, so this will officially release next monday.
But it will release on the canary tag within a few minutes.

**Pull request merged**
