### PR TITLE
feat(eslint-plugin): add no-implicit-this-methods rule

### PR DESCRIPTION
**Pull request by Retsam**
Copying description from the readme here for convenience.  This rule closes a class of potential runtime errors when dealing with `this` keywords.

# No implicit `this` type for methods

This rule requires that all class and object methods that use the `this` keyword must explicitly specify the `this` type, so that the typescript compiler will ensure that the function is always called with the right `this`. For example:

```ts
class Example {
  value = 'val';
  implicit() {
    return this.value.toUpperCase();
  }
  explicit(this: this) {
    return this.value.toUpperCase();
  }
}
const implicit = new Example().implicit;
implicit(); // Runtime error, but not a compiler error
const explicit = new Example().explicit;
explicit(); // Compile error
```

The compiler has a built-in `--noImplicitThis` option, but it allows `this` to be implicit in classes and object methods.

### CODE REVIEW

**Comment by glen-84** [comment]
Adding `this: this` to _every_ method of _every_ class seems like a lot of effort/noise for potentially not a lot of benefit. I don't think that I'd use this rule myself.

I feel like maybe such rules should start as suggestion issues, to gather feedback/upvotes from the community before implementation. There are a certain set of rules that are perhaps too specific for general usage, and should maybe be included in separate packages.

**Comment by Retsam** [comment]
@glen-84 It may be worth clarifying that it's not every method: it's only methods that use `this` that aren't already written as arrow function properties - at least in our codebase that left relatively few methods where this rule applied; (though admittedly we widely use arrow functions properties because we've been bitten by the `this` in the past).

I'd defend this rule's inclusion in the main typescript-eslint package, as it closes one of the few sources of runtime errors I've found in strict Typescript - but I'm fine with moving this to a suggestion issue and gathering feedback in the meantime.  (I don't feel the time spent implementing it is wasted, if it doesn't get used here I'll likely move the code elsewhere)

**Comment by glen-84** [comment]
> ... it's only methods that use this that aren't already written as arrow function properties

That's most methods in the codebases that I've worked on.

---

Doesn't the `unbound-method` rule cover this? (if you ignore the fairly large number of issues)

I prefer the idea of flagging unbound methods and fixing only those cases, as opposed to requiring _all_ methods to be declared this way, even if they're never called without the correct `this`.

Anyway, this is just my opinion, other developers may also want this rule.

**Comment by Retsam** [comment]
This does do fairly similar things to `unbound-method`, but I think this method is a little more reliable: it insists on a little more noise when declaring methods, but there won't be false positives on usage, and it doesn't rely on type information - it just enforces the code is written in such a way that the typescript compiler will do the right checks.

Would it change opinions at all if this rule had an auto-fixer?  That would make it much easier for existing codebases to adopt this change.

**Comment by glen-84** [comment]
> Would it change opinions at all if this rule had an auto-fixer?

Not for me personally.

**Comment by glen-84** [comment]
@bradzacher,

I think your questions have already been answered (?).

> Which leads me to the question - why would I use this rule instead of unbound-method?

> This does do fairly similar things to unbound-method, but I think this method is a little more reliable: it insists on a little more noise when declaring methods, but there won't be false positives on usage, and it doesn't rely on type information - it just enforces the code is written in such a way that the typescript compiler will do the right checks.

---

> Out of curiosity - may I ask why you use methods instead of arrow functions for this case?

> It may be worth clarifying that it's not every method: it's only methods that use this that aren't already written as arrow function properties - at least in our codebase that left relatively few methods where this rule applied; (though admittedly we widely use arrow functions properties because we've been bitten by the this in the past).

**Comment by bradzacher** [comment]
Kind of does.

The latter one is still open - you mention you had "relatively few methods where this rule applied", what were those cases and why couldn't they be arrow functions instead?

---

The former, I get not wanting to use type information, but I don't think this is an amazing alternative, due to the "pass as argument" hole I mentioned earlier.

I'd rather false positives which I can assess and silence, rather than false negatives which are missed and cause production bugs.

I wonder if a better rule would be - "always use an arrow function if referencing `this`"

**Comment by Retsam** [comment]
Yeah, after playing with this rule a bit more, I'm not satisfied with it myself.  I also discovered the "pass as argument" hole, and found a few annoying edge cases.  (e.g. it's a little non-trivial to annotate the type of `this` when dealing with generic classes)

Our codebase has a few places where we've specifically avoided arrow functions for memory reasons - places where we create thousands of instances and the memory pressure of each instance having its own copies of every method was noticeable, compared to a single shared instance on the prototype - but that's probably an anomaly.  

I'm still not a huge fan of `unbound-method`'s solution either; but I don't think this approach panned out, either.  

Thanks for the discussion and the feedback!

**Comment by OliverJAsh** [comment]
> passing a method with a `this: this` to a function will not trigger any errors

Note that if you define `this: void` on the receiver then you will get an error:

```ts
function acceptsStringFn(this: void, fn: () => string): string {
  return fn();
}

// runtime *and* compile-time errors
acceptsStringFn(new Example().explicit);
```

But I think it's a very big ask that:

1. all class methods must have `this: this` *and*
2. all higher-order functions that may receive class methods as a parameter must have `this: void`.

Ideally TypeScript would infer `this: this` for class methods (https://github.com/microsoft/TypeScript/issues/36100, https://github.com/microsoft/TypeScript/issues/35451), but that would only get half us of the way—we'd still need to add `this: void` to "receivers".

**Comment by bradzacher** [comment]
That's interesting, I haven't ever used the `this` argument, so I didn't know you could explicitly declare no `this` context.

I wouldn't completely be opposed to a rule which enforces that _every single function_ includes a `this` argument.

I'm not sure if people would use it (because it's a weird thing to require), but it seems like it could be a pretty useful rule if it had a fixer for _all_ cases.

**Comment by Retsam** [comment]
Ah, I didn't realize that either.  I think you've got an error in the example, though.  I think it's supposed to be 

```ts
function acceptsStringFn(fn: (this: void) => string): string
```

not

```ts
function acceptsStringFn(this: void, fn: () => string): string
```

---

I guess in theory, a slightly more useful version of this linter rule would also check that higher order functions specify `this: void`?  

Though, in my experience the biggest mistake in terms of `this` is `.then`, which would require mucking with DOM types.  I wonder if `this: void` introduces any performance penalties in the way that `this: this` does, if not, perhaps the typescript team could be convinced to add `this: void` to stuff like `Promise#then`.

(Also, sorry, I guess I could have saved you some time if I had linked #microsoft/TypeScript#35451 here)

**Comment by OliverJAsh** [comment]
> I wonder if `this: void` introduces any performance penalties in the way that `this: this` does, if not, perhaps the typescript team could be convinced to add `this: void` to stuff like `Promise#then`.

I was also curious about this. If there is no `this` type, they could default to `void` 🤔 It might be worth filing an issue to see what they think?

**Pull request closed without merging**
