### PR TITLE
feat(eslint-plugin): [no-unused-expressions] support satisfies expressions

### LINKED ISSUE #9275: Bug: [no-unused-expressions] false negative on satisfies expression
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play#ts=5.4.5&fileType=.tsx&code=IwAgzghgLglmBmMCmYQDsCuBbARkgTgNwBQQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tidmUQAm9AB7FoKZJQ5NUGSImjQO0SODABfEOqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
1 satisfies number;
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-unused-expressions": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Error

### Actual Result

No error

### Additional Info

This was discovered while working on https://github.com/typescript-eslint/typescript-eslint/pull/9199. I will send a PR when that doc PR is merged.

### PR DESCRIPTION
**Pull request by Josh-Cena**
## PR Checklist

- [x] Addresses an existing open issue: fixes #9275
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

### CODE REVIEW

**Review by JoshuaKGoldberg — DISMISSED** [review]
Great! 🚀 

(once the tests are passing)

**Comment by Josh-Cena** [comment]
We are discussing what to do in #9275. We disagree on whether it should be an option or just ignored

**Comment by JoshuaKGoldberg** [comment]
👋 just checking in @Josh-Cena, is there anything we should do with this?

**Comment by Josh-Cena** [comment]
Closing until we reach a conclusion.

**Pull request closed without merging**
